# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  _if = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "if";
      version = "0.1.0.0";
      sha256 = "078lg8b6n4bhlhh6ax4k4n8k8fk7hiwcnzyr4h9zbq6vczl77xi8";
      libraryHaskellDepends = [ base ];
      description = "(?) and (?>) conditional operator";
      license = lib.licenses.bsd3;
    }
  ) { };

}
