# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  ACME = callPackage (
    {
      mkDerivation,
      base,
      list-extras,
      mtl,
      random,
      random-shuffle,
      void,
    }:
    mkDerivation {
      pname = "ACME";
      version = "0.0.0.1";
      sha256 = "103mil8lixg0v2wjizy0pqyy9ywbmrk56mc0n37wwvz0qkjaqnds";
      revision = "1";
      editedCabalFile = "0c02gd5adgcfryd8fygbhxw0ps455l3v1d8knn8rbga067j9jqm7";
      libraryHaskellDepends = [
        base
        list-extras
        mtl
        random
        random-shuffle
        void
      ];
      description = "Essential features";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-all-monad = callPackage (
    {
      mkDerivation,
      base,
      transformers,
    }:
    mkDerivation {
      pname = "acme-all-monad";
      version = "0.1.0.0";
      sha256 = "1qay7m16yjsjg8anbinkagb2v8r67k5wsppkrwyskn9jcb1wnbgv";
      libraryHaskellDepends = [
        base
        transformers
      ];
      description = "A monad which is powerful enough to interpret any action";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-box = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-box";
      version = "0.0.0.0";
      sha256 = "0n6mawj9kq6s84j4yxwqabhni7kzgvhmhxi9dw1mrwnxkh5ial8v";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [ base ];
      executableHaskellDepends = [ base ];
      testHaskellDepends = [ base ];
      description = "A full featured empty project";
      license = lib.licenses.bsd3;
      mainProgram = "acme-box";
    }
  ) { };

  acme-cadre = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-cadre";
      version = "0.1";
      sha256 = "1nclcq48r547rgmd4h0hf498z27d15lp4da9yb3a3sy7qk6m92bi";
      libraryHaskellDepends = [ base ];
      description = "car, cdr and more";
      license = lib.licenses.publicDomain;
    }
  ) { };

  acme-circular-containers = callPackage (
    {
      mkDerivation,
      base,
      containers,
      doctest,
      doctest-discover,
      graph-wrapper,
    }:
    mkDerivation {
      pname = "acme-circular-containers";
      version = "0.1.0.0";
      sha256 = "1xngqlx0avn84qx696hjm8cdqqs9p0ls90kklkz5rs48fbcma3pr";
      revision = "3";
      editedCabalFile = "0zpjfk5wwkhl3sql8lrp6j8h731j6ms0cqmjs1hzz24iiwwkj7bj";
      libraryHaskellDepends = [
        base
        containers
        graph-wrapper
      ];
      testHaskellDepends = [
        base
        containers
        doctest
        doctest-discover
        graph-wrapper
      ];
      description = "Spineless containers which are fast to read but inefficient to update";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  acme-cofunctor = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-cofunctor";
      version = "0.1.1.0";
      sha256 = "0ydlnp0bbl5haci3a5x59sj2biylmpkqwzy749fhp8jn1cr8fg4x";
      libraryHaskellDepends = [ base ];
      description = "A Cofunctor is a structure from category theory dual to Functor";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-colosson = callPackage (
    {
      mkDerivation,
      base,
      random,
    }:
    mkDerivation {
      pname = "acme-colosson";
      version = "0.1";
      sha256 = "0mfnav0wb0ks365n3kghaic6nasp3qaznhmsdccx35h164ixj9vc";
      libraryHaskellDepends = [
        base
        random
      ];
      description = "Determines whether it is numberwang";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-comonad = callPackage (
    {
      mkDerivation,
      base,
      comonad,
    }:
    mkDerivation {
      pname = "acme-comonad";
      version = "0.1.0.0";
      sha256 = "1sc0alwdgfls18y4q4y0qkbzqm4fgzd9yv6dwwnzw3472vsz2x8s";
      libraryHaskellDepends = [
        base
        comonad
      ];
      description = "A more efficient dualization";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-cuteboy = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-cuteboy";
      version = "0.1.0.0";
      sha256 = "1x21mvm1n6cka07c3d3w8ycp84gx58af1nvpsfcaa7sccj13jvj9";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [ base ];
      executableHaskellDepends = [ base ];
      description = "Maybe gives you a cute boy";
      license = lib.licenses.publicDomain;
      mainProgram = "CuteBoy";
    }
  ) { };

  acme-cutegirl = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-cutegirl";
      version = "0.2.0.0";
      sha256 = "1vvhfncnrq4pbzrgq45kannqv1c029b96lvi1qzwvzf513rqfb3z";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [ base ];
      executableHaskellDepends = [ base ];
      description = "Maybe gives you a cute girl";
      license = lib.licenses.gpl3Only;
      mainProgram = "CuteGirl";
    }
  ) { };

  acme-default = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-default";
      version = "0.1.0";
      sha256 = "0hkx2zpk3w9vh1jdhpwkd7x7hwr3zf5z9n6f30rjrbyqmxnicpip";
      libraryHaskellDepends = [ base ];
      description = "A class for types with a distinguished aesthetically pleasing value";
      license = lib.licenses.asl20;
    }
  ) { };

  acme-dont = callPackage (
    {
      mkDerivation,
      base,
      tasty,
      tasty-hunit,
    }:
    mkDerivation {
      pname = "acme-dont";
      version = "1.2";
      sha256 = "0pi5xdbsbbrl6g23v41505vgzv5mr6l9r9iwv6l2gg6vzmsk42r7";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        tasty
        tasty-hunit
      ];
      description = "A \"don't\" construct";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-flipping-tables = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-flipping-tables";
      version = "0";
      sha256 = "1xl5gwc67acg47fdkgrn7sjvvvnc4sjf5vifph0jb3c7gv93n757";
      libraryHaskellDepends = [ base ];
      description = "Stop execution with rage";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-functors = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-functors";
      version = "0.1.0.1";
      sha256 = "0blzbrlg033vfy8v225sw0nhaacc1pb0zq9vsh1wafadfwmpi6ig";
      libraryHaskellDepends = [ base ];
      description = "The best applicative functors";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-grawlix = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-grawlix";
      version = "0.1.0.2";
      sha256 = "170cvi3b13wb8imfz3yc3323v2dnyhrr080syjqam477ahwggwsn";
      libraryHaskellDepends = [ base ];
      description = "More readable names for commonly used symbols";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-hq9plus = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-hq9plus";
      version = "0.1";
      sha256 = "0da4ysj74fmhcbbvxxfb6w97pr870518k90vwnc3z8kglj1ni187";
      libraryHaskellDepends = [ base ];
      description = "An embedded DSL for the HQ9+ programming language";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-http = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      extensible-exceptions,
      mtl,
      network,
      pretty,
    }:
    mkDerivation {
      pname = "acme-http";
      version = "0.2.3";
      sha256 = "11xxl1var2xdai8s70343s9glx0lrd1fa3d63jaysggcrhg9kl62";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        extensible-exceptions
        mtl
        network
        pretty
      ];
      description = "fastest Haskell PONG server in the world";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-inator = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-inator";
      version = "0.1.0.0";
      sha256 = "1h1vdzqarrmb8sl6y6250h6fia4rxi9vz4i4sj7km7nyk3778zyk";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [ base ];
      executableHaskellDepends = [ base ];
      description = "Evil inventions in the Tri-State area";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "evilplan";
      broken = true;
    }
  ) { };

  acme-io = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-io";
      version = "0.1.0.1";
      sha256 = "091czdcbydc75ndaw2ns8cncxa6ihlvclhrbcz9vp29kvhf483cb";
      libraryHaskellDepends = [ base ];
      description = "The only true way to do IO in Haskell!";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-iot = callPackage (
    {
      mkDerivation,
      base,
      ghc-prim,
      mtl,
      transformers,
    }:
    mkDerivation {
      pname = "acme-iot";
      version = "0.1.0.1";
      sha256 = "0y43prc9ykkbyvrq879ys753cijphmya7ig1m3v1g7fwyy9n23gx";
      libraryHaskellDepends = [
        base
        ghc-prim
        mtl
        transformers
      ];
      description = "IO monad transformer";
      license = lib.licenses.mit;
    }
  ) { };

  acme-kitchen-sink = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-kitchen-sink";
      version = "0.1.0.0";
      sha256 = "0b587ryd63zyap7c3a1dnm25y0k9a6i2sx26xzg0wrq8hfh0f815";
      libraryHaskellDepends = [ base ];
      description = "A place for dumping that does-not-feel-right code while you improve it";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-left-pad = callPackage (
    {
      mkDerivation,
      base,
      text,
    }:
    mkDerivation {
      pname = "acme-left-pad";
      version = "3.0";
      sha256 = "039pz5lw3p8iy1gaijvbc8296djxcziw70a0rnw0iz3iy29w1fmc";
      libraryHaskellDepends = [
        base
        text
      ];
      description = "free your haskell from the tyranny of npm!";
      license = lib.licenses.agpl3Only;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-lolcat = callPackage (
    {
      mkDerivation,
      base,
      parsec,
      random,
      random-shuffle,
      text,
    }:
    mkDerivation {
      pname = "acme-lolcat";
      version = "0.1.1";
      sha256 = "08issbr9lgc2saqvgs80sxl1sgi7ig5jg6iykv1g1zl5k1kv2a32";
      libraryHaskellDepends = [
        base
        parsec
        random
        random-shuffle
        text
      ];
      description = "LOLSPEAK translator";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-lookofdisapproval = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-lookofdisapproval";
      version = "0.1";
      sha256 = "194xvcab14bs3b3nrayxp4z3da60afxa9cmip58mkms5016kwhis";
      libraryHaskellDepends = [ base ];
      description = "Express your disapproval";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-memorandom = callPackage (
    {
      mkDerivation,
      base,
      MemoTrie,
      random,
    }:
    mkDerivation {
      pname = "acme-memorandom";
      version = "0.0.3";
      sha256 = "1l6kxmdb7fi47ldfpcqbl6h4dnzw6zw0ahxmvx6sxwxm3x4hynhi";
      libraryHaskellDepends = [
        base
        MemoTrie
        random
      ];
      description = "Memoized random number generation";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-microwave = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-microwave";
      version = "0.1.0.2";
      sha256 = "136lwxcimj241nq9l0x7icxk1q9xz826sg07d40yj87shir52j39";
      libraryHaskellDepends = [ base ];
      description = "The eighth wonder of the world, kitchen math!";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-miscorder = callPackage (
    {
      mkDerivation,
      base,
      random,
    }:
    mkDerivation {
      pname = "acme-miscorder";
      version = "0.1.0.0";
      sha256 = "180fs64vlbxb2700qq8hzzz82kkmpknakkbk66ddkk1pdl7nm0j4";
      libraryHaskellDepends = [
        base
        random
      ];
      description = "Miscellaneous newtypes for orderings of discutable use";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-missiles = callPackage (
    {
      mkDerivation,
      base,
      stm,
    }:
    mkDerivation {
      pname = "acme-missiles";
      version = "0.3";
      sha256 = "0nvkgdj04i21gq5k541an8zjz0hzzy7dpi384yrhcyh14jsxhqz5";
      libraryHaskellDepends = [
        base
        stm
      ];
      description = "Cause serious international side effects";
      license = lib.licenses.publicDomain;
    }
  ) { };

  acme-mutable-package = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
    }:
    mkDerivation {
      pname = "acme-mutable-package";
      version = "0";
      sha256 = "16da6pkkdr2g77dn3n4v9x6mwi6yz3xlpisvpn0id2xz0bayipmr";
      revision = "4";
      editedCabalFile = "1154vbz0yar1xd8jn2v2dl5fc2pkawwp93yd0g5dcrb9bbx6pagf";
      setupHaskellDepends = [
        base
        Cabal
      ];
      libraryHaskellDepends = [ base ];
      description = "A mutable package";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-not-a-joke = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      base16-bytestring,
      bytestring,
      cryptohash-sha256,
      filepath,
      jose,
      lens,
      text,
      time,
      wreq,
    }:
    mkDerivation {
      pname = "acme-not-a-joke";
      version = "0.1.0.0";
      sha256 = "016zaz5mlbj9v1mwx8208azgvazdz7ng2g6971kjmsp3jxdp27v5";
      libraryHaskellDepends = [
        aeson
        base
        base16-bytestring
        bytestring
        cryptohash-sha256
        filepath
        jose
        lens
        text
        time
        wreq
      ];
      description = "implements ACME clients (rfc-8555)";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-now = callPackage (
    {
      mkDerivation,
      base,
      time,
    }:
    mkDerivation {
      pname = "acme-now";
      version = "1.0.0.1";
      sha256 = "0lnrsndx7r00b7vgh9jmp5j635m4pb2bzx0lfhqidkzfc2llzwsm";
      libraryHaskellDepends = [
        base
        time
      ];
      description = "An interface to the philosophical and metaphysical \"now\"";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-numbersystem = callPackage (
    {
      mkDerivation,
      base,
      template-haskell,
    }:
    mkDerivation {
      pname = "acme-numbersystem";
      version = "0.3.0.0";
      sha256 = "1p5rdssdmds6yqgv3yvlh835h180h9q9430j8i6qrhygqn8lmv87";
      libraryHaskellDepends = [
        base
        template-haskell
      ];
      description = "Define the less than and add and subtract for nats";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-omitted = callPackage (
    {
      mkDerivation,
      base,
      hspec,
    }:
    mkDerivation {
      pname = "acme-omitted";
      version = "3.0.0.0";
      sha256 = "1b0202ikrg81m1v99ax93v60n21aw9anzwsa4hwkfjdn3rhcwrj9";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        hspec
      ];
      description = "A name for omitted definitions";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-one = callPackage (
    { mkDerivation }:
    mkDerivation {
      pname = "acme-one";
      version = "0.0.2";
      sha256 = "11sgx648g5594w8m8x8r25x7s61jyyxazp5dcfyglvhc7zlrrvbb";
      doHaddock = false;
      description = "The identity element of package dependencies";
      license = lib.licenses.publicDomain;
    }
  ) { };

  acme-operators = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-operators";
      version = "0.2.0.0";
      sha256 = "1wf12iphv12srygdvhy7xyja453dzjmm6kd9l2qp00fx986zd01w";
      libraryHaskellDepends = [ base ];
      description = "Operators of base, all in one place!";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-php = callPackage (
    {
      mkDerivation,
      acme-left-pad,
      base,
    }:
    mkDerivation {
      pname = "acme-php";
      version = "0.0.5";
      sha256 = "1kjfpihicb6f3kn5gzr0ya8f73g4y3kvw7y4plv67cpbc1icnpjl";
      libraryHaskellDepends = [
        acme-left-pad
        base
      ];
      description = "The flexibility of Haskell and the safety of PHP";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  acme-pointful-numbers = callPackage (
    {
      mkDerivation,
      base,
      split,
    }:
    mkDerivation {
      pname = "acme-pointful-numbers";
      version = "0.1.2.4";
      sha256 = "02gml2db5vigkwkx99lqzjkpfaqdc74x16bgdx62kf7r3nn37my9";
      libraryHaskellDepends = [
        base
        split
      ];
      description = "Make more than one point in numeric literals";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-realworld = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-realworld";
      version = "0.1.1";
      sha256 = "0ffhichjhhic7d5cjypmd2zmcq0dpqiz5ygsw0y67v83hry0vf8r";
      libraryHaskellDepends = [ base ];
      description = "Primitives for manipulating the state of the universe";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-safe = callPackage (
    {
      mkDerivation,
      acme-dont,
      base,
    }:
    mkDerivation {
      pname = "acme-safe";
      version = "0.1.0.0";
      sha256 = "0bmv45b3v45967gdvsy37xfw6x50qpl8234y20m3nc48f4nf0z68";
      libraryHaskellDepends = [
        acme-dont
        base
      ];
      description = "Safe versions of some infamous haskell functions such as fromJust";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  acme-schoenfinkel = callPackage (
    {
      mkDerivation,
      base,
      QuickCheck,
      test-framework,
      test-framework-quickcheck2,
      test-framework-th,
    }:
    mkDerivation {
      pname = "acme-schoenfinkel";
      version = "0.1.1";
      sha256 = "0jvbrivxpq8jb5rhz6j3pxx2g3d0ckviprp4iza31d6ik7cpk8ad";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        QuickCheck
        test-framework
        test-framework-quickcheck2
        test-framework-th
      ];
      description = "Proper names for curry and uncurry";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-smuggler = callPackage (
    {
      mkDerivation,
      base,
      hspec,
    }:
    mkDerivation {
      pname = "acme-smuggler";
      version = "1.1.1.0";
      sha256 = "0w4m213dcn07hxbnmkbrg2xgfdv9hlfz72ax9pcinswc10zwph1q";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        hspec
      ];
      description = "Smuggle arbitrary values in arbitrary types";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-strfry = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
    }:
    mkDerivation {
      pname = "acme-strfry";
      version = "0.1";
      sha256 = "1r6xnkyx22khzq6hlb8bk0fnbb6hlwbf12wajhx8vcxa7bkhh8lb";
      libraryHaskellDepends = [
        base
        bytestring
      ];
      description = "A binding to the glibc strfry function";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-stringly-typed = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "acme-stringly-typed";
      version = "1.0.0.0";
      sha256 = "18wvsvdmbwh9dcawiy4f9pn4vg98kdq9zxc37sz7dpmaigimw16f";
      revision = "1";
      editedCabalFile = "0i5hark97zl45iyiijxj07d2pg112kh3jcmjmscpbss5l5n02h23";
      libraryHaskellDepends = [ base ];
      description = "Stringly Typed Programming";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-strtok = callPackage (
    {
      mkDerivation,
      base,
      mtl,
    }:
    mkDerivation {
      pname = "acme-strtok";
      version = "0.1.0.3";
      sha256 = "1anj8yygzcqkl4nwqwbrmwsqda84qcl8yzq7pgx2b7p895xcfa68";
      libraryHaskellDepends = [
        base
        mtl
      ];
      description = "A Haskell port of the C/PHP strtok function";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-this = callPackage (
    {
      mkDerivation,
      base,
      template-haskell,
    }:
    mkDerivation {
      pname = "acme-this";
      version = "0.1.0.0";
      sha256 = "16zmjrf849m066mnj7rlc10jcddy31ck83mg0b7pmn4cvp95q8k5";
      revision = "1";
      editedCabalFile = "1xizmz9yyhxkkaynlk9x0l1nv5maz0shk3d1ipaphc9c6q4b1mjq";
      libraryHaskellDepends = [
        base
        template-haskell
      ];
      description = "import This";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-timemachine = callPackage (
    {
      mkDerivation,
      base,
      ghc-prim,
      mtl,
      transformers,
    }:
    mkDerivation {
      pname = "acme-timemachine";
      version = "0.0.1.0";
      sha256 = "1dfwn0n4hg6zs4ikz6jzkn2spwsvchs1jgq7662aq4ljyp7f1rvb";
      libraryHaskellDepends = [
        base
        ghc-prim
        mtl
        transformers
      ];
      description = "An easy way to perform and unperform IO and other stateful actions";
      license = lib.licenses.bsd3;
    }
  ) { };

  acme-year = callPackage (
    {
      mkDerivation,
      base,
      criterion,
      time,
    }:
    mkDerivation {
      pname = "acme-year";
      version = "2024";
      sha256 = "03lr3risfh1fz546krx16776wfxavygbm8d6yaqaa36caa1s05k2";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        time
      ];
      benchmarkHaskellDepends = [
        base
        criterion
      ];
      description = "Get the current year";
      license = lib.licenses.publicDomain;
    }
  ) { };

  acme-zalgo = callPackage (
    {
      mkDerivation,
      array,
      base,
      random,
    }:
    mkDerivation {
      pname = "acme-zalgo";
      version = "0.1.2.1";
      sha256 = "1yd3xrdkxf3hgapi4w5vg79nxmw8y5rnyki5pqi00mca9wjspdhz";
      revision = "2";
      editedCabalFile = "1l2m9hh6mbc59h17z17gcfzgza25jj912d413pw1q37r3v4y0a1c";
      libraryHaskellDepends = [
        array
        base
        random
      ];
      description = "A somewhat flexible Zalgo̐ te̳͜x̥̖̉̓͞t̍̌̔ ̀̃t̴̢̞̜͓̝r̶̬̆̂̒͟á̧̡͎͔̯̰̕n̹̾̓ͬͦ̍͘ṡ̢͓͉ͮ͆l̠̖̹̗̳̖̽̌ͤ͞a͚̭͙̹̲ͭͩt͈͐o̢̭͇͍̟͐ͬ̾ͪ͜r͇.̸̅ͭ̐̀̊ͨ͛";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  acme-zero = callPackage (
    { mkDerivation }:
    mkDerivation {
      pname = "acme-zero";
      version = "0.0.2";
      sha256 = "06d4hpda8qwwq9wzkgx6fpiq39l1md8sfm9hnvh4r95xyg5q53f6";
      doHaddock = false;
      description = "The absorbing element of package dependencies";
      license = lib.licenses.publicDomain;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
