# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  affine = callPackage (
    {
      mkDerivation,
      alg,
      base,
    }:
    mkDerivation {
      pname = "affine";
      version = "0.1.1.0";
      sha256 = "094h5b5l755sm79mr47dm5brp2jvfd2g0mdz23mcw1pz57lm0c8i";
      revision = "1";
      editedCabalFile = "1avxd17y9k0afqjgb8gq254a6ys7dpncgiyrp6mxbngdcvjyahyc";
      libraryHaskellDepends = [
        alg
        base
      ];
      description = "Affine spaces (generalized)";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  affine-invariant-ensemble-mcmc = callPackage (
    {
      mkDerivation,
      base,
      containers,
      mwc-random,
      primitive,
      split,
      vector,
    }:
    mkDerivation {
      pname = "affine-invariant-ensemble-mcmc";
      version = "0.2.0.0";
      sha256 = "116ln9zf4n0xy95nyyb3kwhg7ds36m793ys5yd5ha74vqf48gvk5";
      libraryHaskellDepends = [
        base
        containers
        mwc-random
        primitive
        split
        vector
      ];
      description = "General-purpose sampling";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  affinely-extended = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "affinely-extended";
      version = "0.1.0.0";
      sha256 = "1bldljkgsb9v7ss3l87mm4r9wjpp3z02hjnfdnp84pmaj0b34vam";
      libraryHaskellDepends = [ base ];
      license = lib.licenses.mit;
    }
  ) { };

}
