# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  air-extra = callPackage (
    {
      mkDerivation,
      air,
      array,
      base,
      bytestring,
      containers,
      directory,
      filepath,
      parallel,
      parsec,
      regexpr,
      text,
      time,
    }:
    mkDerivation {
      pname = "air-extra";
      version = "2015.5.4";
      sha256 = "07k01yjr9kj5q0dr871w9jmf23sdd75xrwgldsrkpppfc8kvnd97";
      libraryHaskellDepends = [
        air
        array
        base
        bytestring
        containers
        directory
        filepath
        parallel
        parsec
        regexpr
        text
        time
      ];
      description = "air-extra";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  air-spec = callPackage (
    {
      mkDerivation,
      base,
      hspec,
      text,
    }:
    mkDerivation {
      pname = "air-spec";
      version = "2013.7.1";
      sha256 = "0s4y2805nmfydzxgr5lnhmyzkb6rh9mx2kpvzqqgyh4jvccdnwfx";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        hspec
        text
      ];
      description = "air spec helper";
      license = lib.licenses.bsd3;
    }
  ) { };

  air-th = callPackage (
    {
      mkDerivation,
      air,
      base,
      template-haskell,
    }:
    mkDerivation {
      pname = "air-th";
      version = "2014.11.17";
      sha256 = "0rhp56qvwiwlrs7pvpbslybvlp4xnllfjab6pap2chxgywas34pq";
      libraryHaskellDepends = [
        air
        base
        template-haskell
      ];
      description = "air";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
