# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  annihilator = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "annihilator";
      version = "0.1.0.0";
      sha256 = "00f0pyf2fxdvwwz9bz3mpp7db39p1m83frvlif74kp0y1x8r20yp";
      libraryHaskellDepends = [ base ];
      description = "Semigroups with annihilators and utility functions";
      license = lib.licenses.bsd3;
    }
  ) { };

}
