# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  antagonist = callPackage (
    {
      mkDerivation,
      antisplice,
      base,
      chatty,
      chatty-utils,
      ironforge,
      mtl,
      shakespeare,
      text,
      time,
      time-locale-compat,
      yesod,
      yesod-auth,
    }:
    mkDerivation {
      pname = "antagonist";
      version = "0.1.0.30";
      sha256 = "1bgsal1030ydg05pn5xd8gdnpm68pmd135n52dqh5cwhjmhzc0g6";
      revision = "1";
      editedCabalFile = "0hm0flgi9h1y84pspr2921skwybrs490yazbs8pz8wi0bhvfg1bc";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        antisplice
        base
        chatty
        chatty-utils
        mtl
        shakespeare
        text
        time
        time-locale-compat
        yesod
        yesod-auth
      ];
      executableHaskellDepends = [
        antisplice
        base
        chatty
        chatty-utils
        ironforge
        mtl
        shakespeare
        text
        time
        time-locale-compat
        yesod
        yesod-auth
      ];
      description = "A web interface to Antisplice dungeons";
      license = lib.licenses.agpl3Only;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "ironforge-yesod";
    }
  ) { };

}
