# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  assembler = callPackage (
    {
      mkDerivation,
      base,
      containers,
      ghc-binary,
      parsec,
    }:
    mkDerivation {
      pname = "assembler";
      version = "0.0.1";
      sha256 = "1crwfndk7qci5id132s9f57i3kslxcdcqpymsykm1460x5nd42qs";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
        ghc-binary
        parsec
      ];
      executableHaskellDepends = [
        base
        containers
        ghc-binary
        parsec
      ];
      description = "Haskell Assembler";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "has";
      broken = true;
    }
  ) { ghc-binary = null; };

  assert-failure = callPackage (
    {
      mkDerivation,
      base,
      pretty-show,
      text,
    }:
    mkDerivation {
      pname = "assert-failure";
      version = "0.1.3.0";
      sha256 = "0lbx22agc2rq119yf2d0fy5cchfbgvjln1w147iiwgvrqd0xgyff";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        pretty-show
        text
      ];
      description = "Syntactic sugar improving 'assert' and 'error'";
      license = lib.licenses.bsd3;
    }
  ) { };

  assert4hs = callPackage (
    {
      mkDerivation,
      base,
      data-default,
      pretty-diff,
      tasty,
      text,
    }:
    mkDerivation {
      pname = "assert4hs";
      version = "0.0.0.1";
      sha256 = "141ic9k4v5qqx64ksy925ksscs2dyixqp3bpxk9rfz6m2mam5091";
      libraryHaskellDepends = [
        base
        data-default
        pretty-diff
        text
      ];
      testHaskellDepends = [
        base
        data-default
        pretty-diff
        tasty
        text
      ];
      description = "A set of assertion for writing more readable tests cases";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  assert4hs-core = callPackage (
    {
      mkDerivation,
      base,
      data-default,
      hspec,
      hspec-discover,
      pretty-diff,
      text,
    }:
    mkDerivation {
      pname = "assert4hs-core";
      version = "0.1.0";
      sha256 = "09jp2j4l17ry2v4hnmj5l81dmwqrgf9hszdpc5ybxp0h3h2l6xj2";
      libraryHaskellDepends = [
        base
        data-default
        pretty-diff
        text
      ];
      testHaskellDepends = [
        base
        data-default
        hspec
        hspec-discover
        pretty-diff
        text
      ];
      testToolDepends = [ hspec-discover ];
      description = "A set of assertion for writing more readable tests cases";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  assert4hs-hspec = callPackage (
    {
      mkDerivation,
      assert4hs-core,
      base,
      hspec,
      HUnit,
    }:
    mkDerivation {
      pname = "assert4hs-hspec";
      version = "0.1.0";
      sha256 = "1mb6zhzr78ydfgx14d2h5xrnq1dppsxyqb9hhhc65j1r7y08glbj";
      libraryHaskellDepends = [
        assert4hs-core
        base
        hspec
        HUnit
      ];
      testHaskellDepends = [
        assert4hs-core
        base
        hspec
        HUnit
      ];
      description = "integration point of assert4hs and hspec";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  assert4hs-tasty = callPackage (
    {
      mkDerivation,
      assert4hs-core,
      base,
      tasty,
    }:
    mkDerivation {
      pname = "assert4hs-tasty";
      version = "0.1.0";
      sha256 = "1x53ai0ssk0kakp9ims19a6v5rnxiqlwnp3d07n6ji3lmwrdmy1j";
      libraryHaskellDepends = [
        assert4hs-core
        base
        tasty
      ];
      testHaskellDepends = [
        assert4hs-core
        base
        tasty
      ];
      description = "Provider for tasty runner to run assert4hs tests";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  assertions = callPackage (
    {
      mkDerivation,
      ansi-terminal,
      base,
      containers,
      interpolate,
      process,
    }:
    mkDerivation {
      pname = "assertions";
      version = "0.1.0.4";
      sha256 = "1b2p6b6brk0b1hq264i20bpdhdaq4xdzcqp7gzvfy1s5q3zwjzj8";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        ansi-terminal
        base
        containers
      ];
      testHaskellDepends = [
        base
        interpolate
        process
      ];
      description = "A simple testing framework";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  asset-bundle = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      directory,
      filepath,
    }:
    mkDerivation {
      pname = "asset-bundle";
      version = "0.1.0.2";
      sha256 = "1c0678qjkr1q3pi20ch05k8ri4zxcc1drc4j44fvb1sz7b8y260c";
      libraryHaskellDepends = [
        base
        Cabal
        directory
        filepath
      ];
      description = "A build-time Cabal library that bundles executables with assets";
      license = lib.licenses.bsd3;
    }
  ) { };

  asset-map = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      containers,
      filepath,
      hspec,
      template-haskell,
      th-lift-instances,
    }:
    mkDerivation {
      pname = "asset-map";
      version = "0.1.0.0";
      sha256 = "0c33ghr2wd9dr153zpcmifdysfw39x3bhzz49wy9vm81a7rmw9kg";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        containers
        filepath
        template-haskell
        th-lift-instances
      ];
      testHaskellDepends = [
        base
        hspec
      ];
      description = "Asset map support for the JavaScript broccoli-asset-rev library";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
