# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  authenticate = callPackage (
    {
      mkDerivation,
      aeson,
      attoparsec,
      attoparsec-aeson,
      base,
      blaze-builder,
      bytestring,
      case-insensitive,
      conduit,
      containers,
      html-conduit,
      http-conduit,
      http-types,
      network-uri,
      resourcet,
      text,
      transformers,
      unordered-containers,
      xml-conduit,
    }:
    mkDerivation {
      pname = "authenticate";
      version = "1.3.5.2";
      sha256 = "1lsa5fgwxrz87l94d7whag2gpg0f3bxfn0244mi0byl6j5zpl0wp";
      libraryHaskellDepends = [
        aeson
        attoparsec
        attoparsec-aeson
        base
        blaze-builder
        bytestring
        case-insensitive
        conduit
        containers
        html-conduit
        http-conduit
        http-types
        network-uri
        resourcet
        text
        transformers
        unordered-containers
        xml-conduit
      ];
      description = "Authentication methods for Haskell web applications";
      license = lib.licenses.mit;
    }
  ) { };

  authenticate-kerberos = callPackage (
    {
      mkDerivation,
      base,
      process,
      text,
    }:
    mkDerivation {
      pname = "authenticate-kerberos";
      version = "1.0.0";
      sha256 = "06k8xi9n44xq63dpmcv4l0vg35y19dk5x1ibyay05w58k4kv4fdq";
      libraryHaskellDepends = [
        base
        process
        text
      ];
      description = "Authentication methods for Haskell web applications";
      license = lib.licenses.bsd3;
    }
  ) { };

  authenticate-ldap = callPackage (
    {
      mkDerivation,
      base,
      LDAP,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "authenticate-ldap";
      version = "0.0.3";
      sha256 = "1wsx43l7jl40jpzhiv2fjc1mnpsaaryrjpqaiyqsn3ahacsy4ly5";
      libraryHaskellDepends = [
        base
        LDAP
        text
        transformers
      ];
      description = "LDAP authentication for Haskell web applications";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  authenticate-oauth = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      blaze-builder,
      bytestring,
      crypto-pubkey-types,
      data-default,
      http-client,
      http-types,
      random,
      RSA,
      SHA,
      time,
      transformers,
      transformers-compat,
    }:
    mkDerivation {
      pname = "authenticate-oauth";
      version = "1.7";
      sha256 = "0y4v46rn0cvm0sr1v8qq1zgzllrlrr3ji5gij1xprgf1zsazcvvl";
      revision = "1";
      editedCabalFile = "198xm2qdaqwg2m9kgrkw5gdk2bh19mmj6c4d5fsbpcjnhxlh6axg";
      libraryHaskellDepends = [
        base
        base64-bytestring
        blaze-builder
        bytestring
        crypto-pubkey-types
        data-default
        http-client
        http-types
        random
        RSA
        SHA
        time
        transformers
        transformers-compat
      ];
      description = "Library to authenticate with OAuth for Haskell web applications";
      license = lib.licenses.bsd3;
    }
  ) { };

  authinfo-hs = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      network,
      text,
    }:
    mkDerivation {
      pname = "authinfo-hs";
      version = "0.1.0.0";
      sha256 = "1jv0y4y2ig8dx95xw3zbxc1h9mv3wi3r8xqx00llmf2qs6wgdlp5";
      libraryHaskellDepends = [
        attoparsec
        base
        network
        text
      ];
      description = "Password querying for .authinfo";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  authoring = callPackage (
    {
      mkDerivation,
      ansi-wl-pprint,
      base,
      citation-resolve,
      containers,
      data-default,
      haskell-src-meta,
      HaTeX,
      lens,
      mtl,
      parsers,
      safe,
      template-haskell,
      text,
      transformers,
      trifecta,
    }:
    mkDerivation {
      pname = "authoring";
      version = "0.3.4";
      sha256 = "0jfxgrbkcqpfcvg1jk7ysd74bq7xjlvzqamnr3qg4ib9zg6yw0k4";
      libraryHaskellDepends = [
        ansi-wl-pprint
        base
        citation-resolve
        containers
        data-default
        haskell-src-meta
        HaTeX
        lens
        mtl
        parsers
        safe
        template-haskell
        text
        transformers
        trifecta
      ];
      description = "A library for writing papers";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
