# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  azure-acs = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      bytestring,
      conduit,
      conduit-extra,
      connection,
      http-conduit,
      http-types,
      network,
      time,
    }:
    mkDerivation {
      pname = "azure-acs";
      version = "0.0.1.1";
      sha256 = "09gv4ym6nxx5854m40p06pxvxrqfhmadxlb0d72pji6hk180yg5l";
      libraryHaskellDepends = [
        attoparsec
        base
        bytestring
        conduit
        conduit-extra
        connection
        http-conduit
        http-types
        network
        time
      ];
      description = "Windows Azure ACS";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  azure-email = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      base64-bytestring,
      bytestring,
      cryptonite,
      exceptions,
      http-client,
      http-client-tls,
      lens-aeson,
      microlens,
      RSA,
      text,
      time,
      uuid,
      wreq,
    }:
    mkDerivation {
      pname = "azure-email";
      version = "0.1.0.0";
      sha256 = "108xfmq9mb8fxy06six0id7sf8rpazknqx4plk93fl34xyrwald5";
      libraryHaskellDepends = [
        aeson
        base
        base64-bytestring
        bytestring
        cryptonite
        exceptions
        http-client
        http-client-tls
        lens-aeson
        microlens
        RSA
        text
        time
        uuid
        wreq
      ];
      description = "send email with microsoft azure";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  azure-functions-worker = callPackage (
    {
      mkDerivation,
      aeson,
      async,
      base,
      bytestring,
      Cabal,
      containers,
      directory,
      filepath,
      glabrous,
      http-types,
      http2-client,
      http2-client-grpc,
      http2-grpc-proto-lens,
      http2-grpc-types,
      lens-family,
      lens-family-core,
      mtl,
      network-uri,
      optparse-applicative,
      proto-lens-protobuf-types,
      proto-lens-protoc,
      proto-lens-runtime,
      proto-lens-setup,
      raw-strings-qq,
      stm,
      text,
      time,
    }:
    mkDerivation {
      pname = "azure-functions-worker";
      version = "0.0.0.0";
      sha256 = "0035kmxfnb121mg38xzbyxphwg2r4x63chlywl67b9nz1pwp828x";
      setupHaskellDepends = [
        base
        Cabal
        proto-lens-setup
      ];
      libraryHaskellDepends = [
        aeson
        async
        base
        bytestring
        containers
        directory
        filepath
        glabrous
        http-types
        http2-client
        http2-client-grpc
        http2-grpc-proto-lens
        http2-grpc-types
        lens-family
        lens-family-core
        mtl
        network-uri
        optparse-applicative
        proto-lens-protobuf-types
        proto-lens-runtime
        raw-strings-qq
        stm
        text
        time
      ];
      libraryToolDepends = [ proto-lens-protoc ];
      testHaskellDepends = [ base ];
      description = "Azure Functions Worker";
      license = lib.meta.getLicenseFromSpdxId "MIT";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  azure-service-api = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      case-insensitive,
      certificate,
      crypto-pubkey-types,
      http-conduit,
      hxt,
      hxt-xpath,
      pretty,
      resourcet,
      tls,
      tls-extra,
      transformers,
    }:
    mkDerivation {
      pname = "azure-service-api";
      version = "0.1.0.0";
      sha256 = "09wb94k8f8wgcdx036x2fzixck7cbv739rrh299m7awbl4i3mfhg";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        case-insensitive
        certificate
        crypto-pubkey-types
        http-conduit
        hxt
        hxt-xpath
        pretty
        resourcet
        tls
        tls-extra
        transformers
      ];
      description = "Haskell bindings for the Microsoft Azure Service Management API";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  azure-servicebus = callPackage (
    {
      mkDerivation,
      aeson,
      async,
      attoparsec,
      azure-acs,
      base,
      bytestring,
      case-insensitive,
      conduit,
      connection,
      http-client,
      http-conduit,
      http-types,
      network,
      text,
    }:
    mkDerivation {
      pname = "azure-servicebus";
      version = "0.1.6.0";
      sha256 = "1ig8af14m11di9fis6s5hxmfqh7hc40c3bqyighnpi25xnv7mm13";
      libraryHaskellDepends = [
        aeson
        async
        attoparsec
        azure-acs
        base
        bytestring
        case-insensitive
        conduit
        connection
        http-client
        http-conduit
        http-types
        network
        text
      ];
      description = "Haskell wrapper over Microsoft Azure ServiceBus REST API";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  azurify = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      bytestring,
      case-insensitive,
      cmdargs,
      conduit,
      data-default,
      directory,
      http-conduit,
      http-date,
      http-types,
      hxt,
      hxt-unicode,
      network,
      old-locale,
      SHA,
      text,
      time,
      transformers,
      unix-compat,
      utf8-string,
    }:
    mkDerivation {
      pname = "azurify";
      version = "0.4.0.5";
      sha256 = "0nqkpizqiwv7wfs1bgl8q13aaqnc9wjh8gs6fyiklplnjdcpqf9g";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        base64-bytestring
        bytestring
        case-insensitive
        conduit
        data-default
        http-conduit
        http-date
        http-types
        hxt
        hxt-unicode
        network
        old-locale
        SHA
        text
        time
        transformers
        unix-compat
        utf8-string
      ];
      executableHaskellDepends = [
        base
        base64-bytestring
        bytestring
        case-insensitive
        cmdargs
        conduit
        data-default
        directory
        http-conduit
        http-date
        http-types
        hxt
        hxt-unicode
        network
        old-locale
        SHA
        text
        time
        transformers
        unix-compat
        utf8-string
      ];
      description = "A simple library for accessing Azure blob storage";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "azurify";
      broken = true;
    }
  ) { };

}
