# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  bdcs = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-pretty,
      base,
      bytestring,
      codec-rpm,
      cond,
      conduit,
      conduit-combinators,
      conduit-extra,
      containers,
      content-store,
      cpio-conduit,
      cryptonite,
      directory,
      esqueleto,
      exceptions,
      filepath,
      gi-gio,
      gi-glib,
      gi-ostree,
      gitrev,
      hspec,
      http-conduit,
      HUnit,
      lifted-base,
      listsafe,
      memory,
      monad-control,
      monad-logger,
      monad-loops,
      mtl,
      network-uri,
      ostree,
      parsec,
      parsec-numbers,
      persistent,
      persistent-sqlite,
      persistent-template,
      regex-pcre,
      resourcet,
      split,
      string-conversions,
      tar,
      tar-conduit,
      temporary,
      text,
      time,
      typed-process,
      unix,
      unordered-containers,
      xml-conduit,
    }:
    mkDerivation {
      pname = "bdcs";
      version = "0.6.1";
      sha256 = "1q81ic3jpcjjnbvbww7qabfy6byvlhwsvs0pf7y8a0sm4i0sqj8g";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        codec-rpm
        cond
        conduit
        conduit-combinators
        conduit-extra
        containers
        content-store
        cpio-conduit
        cryptonite
        directory
        esqueleto
        exceptions
        filepath
        gi-gio
        gi-glib
        gi-ostree
        gitrev
        http-conduit
        lifted-base
        listsafe
        memory
        monad-control
        monad-logger
        mtl
        network-uri
        parsec
        parsec-numbers
        persistent
        persistent-sqlite
        persistent-template
        regex-pcre
        resourcet
        split
        string-conversions
        tar
        tar-conduit
        temporary
        text
        time
        typed-process
        unix
        unordered-containers
        xml-conduit
      ];
      libraryPkgconfigDepends = [ ostree ];
      executableHaskellDepends = [
        aeson
        aeson-pretty
        base
        bytestring
        cond
        conduit
        content-store
        directory
        filepath
        lifted-base
        monad-logger
        monad-loops
        mtl
        network-uri
        persistent-sqlite
        regex-pcre
        text
        time
        typed-process
      ];
      testHaskellDepends = [
        aeson
        base
        bytestring
        codec-rpm
        cond
        conduit
        conduit-combinators
        containers
        directory
        esqueleto
        filepath
        gi-gio
        gi-glib
        hspec
        HUnit
        listsafe
        monad-logger
        mtl
        parsec
        parsec-numbers
        persistent
        persistent-sqlite
        persistent-template
        resourcet
        text
        time
        unix
      ];
      description = "Tools for managing a content store of software packages";
      license = lib.licenses.lgpl21Only;
      hydraPlatforms = lib.platforms.none;
    }
  ) { inherit (pkgs) ostree; };

  bdcs-api = callPackage (
    {
      mkDerivation,
      aeson,
      async,
      base,
      bdcs,
      bifunctors,
      bytestring,
      concurrent-extra,
      cond,
      containers,
      directory,
      extra,
      filepath,
      gi-ggit,
      gi-gio,
      gi-glib,
      gitrev,
      haskell-gi-base,
      hspec,
      htoml,
      http-client,
      http-media,
      http-types,
      libgit2-glib,
      monad-logger,
      monad-loops,
      mtl,
      network,
      persistent,
      persistent-sqlite,
      resourcet,
      semver,
      servant-client,
      servant-options,
      servant-server,
      split,
      stm,
      string-conversions,
      string-qq,
      tar,
      temporary,
      text,
      time,
      transformers,
      unix,
      uuid,
      wai,
      wai-cors,
      warp,
    }:
    mkDerivation {
      pname = "bdcs-api";
      version = "0.1.3";
      sha256 = "1pjcbw7z79bvmyik6ykjha388gdcjb2h1bf3csc2yjy1g87qmq05";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        async
        base
        bdcs
        bifunctors
        bytestring
        concurrent-extra
        cond
        containers
        directory
        extra
        filepath
        gi-ggit
        gi-gio
        gi-glib
        gitrev
        haskell-gi-base
        htoml
        http-media
        http-types
        monad-logger
        monad-loops
        mtl
        network
        persistent
        persistent-sqlite
        resourcet
        semver
        servant-options
        servant-server
        split
        stm
        string-conversions
        tar
        temporary
        text
        time
        transformers
        unix
        uuid
        wai
        wai-cors
        warp
      ];
      libraryPkgconfigDepends = [ libgit2-glib ];
      executableHaskellDepends = [ base ];
      testHaskellDepends = [
        aeson
        base
        bdcs
        bytestring
        cond
        directory
        filepath
        hspec
        http-client
        monad-loops
        servant-client
        servant-server
        string-conversions
        string-qq
        temporary
        text
        time
        wai
        warp
      ];
      description = "BDCS API Server";
      license = lib.licenses.gpl3Only;
      badPlatforms = lib.platforms.darwin;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "bdcs-api-server";
    }
  ) { inherit (pkgs) libgit2-glib; };

}
