# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  beautifHOL = callPackage (
    {
      mkDerivation,
      array,
      base,
      haskell98,
      mtl,
    }:
    mkDerivation {
      pname = "beautifHOL";
      version = "0.11";
      sha256 = "15k41z1p8h0b677wba4mqkfszwggkrfcp3n5hbdvdjfiqyx2hbzi";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        array
        base
        haskell98
        mtl
      ];
      description = "A pretty-printer for higher-order logic";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "beautifHOL";
    }
  ) { };

}
