# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  bizzlelude = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      directory,
      mtl,
      pcre-light,
      text,
      validation,
    }:
    mkDerivation {
      pname = "bizzlelude";
      version = "4.20.2.0.1";
      sha256 = "1cawb7wn8qxc67pvhcyv3h0ykjbv3mfm04jbp1nagz6nn6ah7ccb";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        directory
        mtl
        pcre-light
        text
        validation
      ];
      description = "A lousy Prelude replacement by a lousy dude";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  bizzlelude-js = callPackage (
    {
      mkDerivation,
      base,
      containers,
      regexpr,
      text,
    }:
    mkDerivation {
      pname = "bizzlelude-js";
      version = "4.17.2.2";
      sha256 = "14m45gcsbykij506id738zjw7jck14f8rqii0xx5qs5y3wrdwr1g";
      libraryHaskellDepends = [
        base
        containers
        regexpr
        text
      ];
      description = "A lousy Prelude replacement by a lousy dude";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
