# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  blatex = callPackage (
    {
      mkDerivation,
      base,
      blaze-html,
      dates,
      directory,
      HaTeX,
      process,
      split,
      tagsoup,
      text,
    }:
    mkDerivation {
      pname = "blatex";
      version = "0.1.0.9";
      sha256 = "181a3b2wrvgbi0j0nxql1kly215afapc795mc6vy9312mqy6fjdl";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        blaze-html
        dates
        directory
        HaTeX
        process
        split
        tagsoup
        text
      ];
      description = "Blog in LaTeX";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "blatex";
    }
  ) { };

}
