# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  blubber = callPackage (
    {
      mkDerivation,
      base,
      blubber-server,
      bytestring,
      cereal,
      containers,
      gloss,
      network,
      unix,
    }:
    mkDerivation {
      pname = "blubber";
      version = "0.0.1";
      sha256 = "0bc30pw6gvw7i6gh58hhkgx2j432zlh2wh4d41abnkjqygifsxsd";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        blubber-server
        bytestring
        cereal
        containers
        gloss
        network
        unix
      ];
      description = "The blubber client; connects to the blubber server";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "blubber";
    }
  ) { };

  blubber-server = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      cereal,
      containers,
      data-default-class,
      network,
      pandoc,
      process,
      random,
      scotty,
      text,
      transformers,
      unix,
    }:
    mkDerivation {
      pname = "blubber-server";
      version = "0.0.1";
      sha256 = "12f594sl2c2hrxr95bpv911x0bdfpmaflp29mhw2yln2vh64nhj5";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        cereal
        containers
        random
      ];
      executableHaskellDepends = [
        base
        Cabal
        cereal
        containers
        data-default-class
        network
        pandoc
        process
        random
        scotty
        text
        transformers
        unix
      ];
      description = "The blubber server, serves blubber clients";
      license = lib.licenses.agpl3Only;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "blubber-server";
      broken = true;
    }
  ) { };

}
