# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  BoundedChan = callPackage (
    {
      mkDerivation,
      array,
      base,
    }:
    mkDerivation {
      pname = "BoundedChan";
      version = "1.0.3.0";
      sha256 = "0vf4mlw08n056g5256cf46m5xsijng5gvjx7ccm4r132gznyl72k";
      libraryHaskellDepends = [
        array
        base
      ];
      description = "Implementation of bounded channels";
      license = lib.licenses.bsd3;
    }
  ) { };

  bound = callPackage (
    {
      mkDerivation,
      base,
      bifunctors,
      binary,
      bytes,
      cereal,
      comonad,
      deepseq,
      deriving-compat,
      hashable,
      mmorph,
      profunctors,
      template-haskell,
      th-abstraction,
      transformers,
      transformers-compat,
      vector,
      void,
    }:
    mkDerivation {
      pname = "bound";
      version = "2.0.7";
      sha256 = "1wqvanfp826s89qr4a1rc9f0ldsj45j1rwy9x6a894vndgrxm8dj";
      revision = "2";
      editedCabalFile = "024q72p316m3sjqp9a63iwrvdmrgs30a0srzq13jybrz00plhkgv";
      libraryHaskellDepends = [
        base
        bifunctors
        binary
        bytes
        cereal
        comonad
        deepseq
        hashable
        mmorph
        profunctors
        template-haskell
        th-abstraction
        transformers
        transformers-compat
      ];
      testHaskellDepends = [
        base
        deriving-compat
        transformers
        transformers-compat
        vector
        void
      ];
      description = "Making de Bruijn Succ Less";
      license = lib.licenses.bsd3;
    }
  ) { };

  bound-extras = callPackage (
    {
      mkDerivation,
      adjunctions,
      base,
      bound,
      containers,
      deepseq,
      filepath,
      hashable,
      pretty,
      tasty,
      tasty-golden,
      text-short,
      transformers,
      utf8-string,
    }:
    mkDerivation {
      pname = "bound-extras";
      version = "0.0.3";
      sha256 = "1apzrjalgdsjcx0c3251hfwgqw5ard3vxqm6zfg3f9wlfy58vp6q";
      libraryHaskellDepends = [
        base
        bound
        deepseq
        hashable
        transformers
      ];
      testHaskellDepends = [
        adjunctions
        base
        bound
        containers
        filepath
        pretty
        tasty
        tasty-golden
        text-short
        transformers
        utf8-string
      ];
      description = "ScopeH and ScopeT extras for bound";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  bound-gen = callPackage (
    {
      mkDerivation,
      base,
      bound,
      monad-gen,
      mtl,
    }:
    mkDerivation {
      pname = "bound-gen";
      version = "0.1.0.2";
      sha256 = "1il4vb497d0195mhvra5djkn3mbdzd8dmcnffpqh1pv1pj8n8hwp";
      libraryHaskellDepends = [
        base
        bound
        monad-gen
        mtl
      ];
      description = "Unwrap Scope's with globally fresh values";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  bound-simple = callPackage (
    {
      mkDerivation,
      base,
      hspec,
      transformers,
    }:
    mkDerivation {
      pname = "bound-simple";
      version = "0.2.0.0";
      sha256 = "0vsqbgb75d20sqis9wk00z301hw5kjknszgd0k07rhymhcja0v5j";
      libraryHaskellDepends = [
        base
        transformers
      ];
      testHaskellDepends = [
        base
        hspec
      ];
      description = "A lightweight implementation of 'bound'";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  bounded-array = callPackage (
    {
      mkDerivation,
      array,
      base,
    }:
    mkDerivation {
      pname = "bounded-array";
      version = "0.1.0.0";
      sha256 = "0zv5a82rm6hwikgls2hw9d18igvfgw655s5pw5h1xbwcv1d8d0ji";
      revision = "4";
      editedCabalFile = "1fagylzqlzrz5dmxnnfbcqswzl32yyv7ndyrjy93mq2810r1m903";
      libraryHaskellDepends = [
        array
        base
      ];
      description = "Arrays with a value for every index";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  bounded-qsem = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "bounded-qsem";
      version = "0.1.0.4";
      sha256 = "01685572n8w477pd1zgffyi988xnzy3ci8ym5c1zcs6ibc4aa07k";
      libraryHaskellDepends = [ base ];
      description = "Bounded quantity semaphores";
      license = lib.licenses.mit;
    }
  ) { };

  bounded-queue = callPackage (
    {
      mkDerivation,
      base,
      containers,
      deepseq,
      tasty,
      tasty-hunit,
    }:
    mkDerivation {
      pname = "bounded-queue";
      version = "1.0.0";
      sha256 = "18jlkdzfkw0v6ifz8fzqkzagc3g97kg13ng8yldq869casnmcw5d";
      libraryHaskellDepends = [
        base
        containers
        deepseq
      ];
      testHaskellDepends = [
        base
        tasty
        tasty-hunit
      ];
      description = "A strict, immutable, thread-safe, single-ended, bounded queue";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  bounded-tchan = callPackage (
    {
      mkDerivation,
      base,
      stm,
    }:
    mkDerivation {
      pname = "bounded-tchan";
      version = "0.2.3";
      sha256 = "12c78dz3y1ly05hckd9pf0j4fpknk383qyb5yrhps4sc2m3i9k9w";
      libraryHaskellDepends = [
        base
        stm
      ];
      description = "Bounded Transactional channels (queues)";
      license = lib.licenses.bsd3;
    }
  ) { };

  boundingboxes = callPackage (
    {
      mkDerivation,
      base,
      lens,
    }:
    mkDerivation {
      pname = "boundingboxes";
      version = "0.2.3";
      sha256 = "0r3mffqxqadn8qklq3kr0ggirkficfj8ic1fxgki2zrc5jm4f2g8";
      revision = "1";
      editedCabalFile = "0qz1bnci5bhb8zqc2dw19sa0k9i57fyhhdh78s3yllp3aijdc3n6";
      libraryHaskellDepends = [
        base
        lens
      ];
      description = "A generic boundingbox for an arbitrary vector";
      license = lib.licenses.bsd3;
    }
  ) { };

}
