# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  c10k = callPackage (
    {
      mkDerivation,
      base,
      network,
      unix,
    }:
    mkDerivation {
      pname = "c10k";
      version = "0.5.0";
      sha256 = "1i62ilk95p1vjyk7gl1fv7lwq6yk3ysfn3v1bbyfpabf97gzr0d9";
      revision = "1";
      editedCabalFile = "1hdkhwjm9dskq9lv08dj92i9navsy6dppk36ilr91ci5gxdphd0n";
      libraryHaskellDepends = [
        base
        network
        unix
      ];
      description = "C10k server library using prefork";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
