# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  cgi-undecidable = callPackage (
    {
      mkDerivation,
      base,
      cgi,
      mtl,
    }:
    mkDerivation {
      pname = "cgi-undecidable";
      version = "3000.0.0";
      sha256 = "1xh3q0s7398gd3513ycxypnj0m9jn0kdbb7459dsb459kbvzdpab";
      libraryHaskellDepends = [
        base
        cgi
        mtl
      ];
      description = "Undecidable instances for the cgi package";
      license = lib.licenses.bsd3;
    }
  ) { };

  cgi-utils = callPackage (
    {
      mkDerivation,
      base,
      cgi,
      containers,
      mtl,
      random,
    }:
    mkDerivation {
      pname = "cgi-utils";
      version = "0.2.1";
      sha256 = "0msljq31bz40hsrhhq9qhxrgmdlqq32l3ykcy4wviv8kmc3dic7p";
      revision = "1";
      editedCabalFile = "0lnx7n8pagi3pw57cz4nz01lhfjmsyhk3z3kwgfrmdyrb3kb276z";
      libraryHaskellDepends = [
        base
        cgi
        containers
        mtl
        random
      ];
      description = "Simple modular utilities for CGI/FastCGI (sessions, etc.)";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
