# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  ChasingBottoms = callPackage (
    {
      mkDerivation,
      array,
      base,
      containers,
      mtl,
      QuickCheck,
      random,
      syb,
    }:
    mkDerivation {
      pname = "ChasingBottoms";
      version = "1.3.1.17";
      sha256 = "0713mgd71dix9dq1i812ydahcacfpsxmciqxwhg4qj0migyc4ymg";
      revision = "1";
      editedCabalFile = "1xz1wpi3k2bzgxnai38840z18hk03ha4xdgjvjg5g8dlja946dih";
      libraryHaskellDepends = [
        base
        containers
        mtl
        QuickCheck
        random
        syb
      ];
      testHaskellDepends = [
        array
        base
        containers
        mtl
        QuickCheck
        random
        syb
      ];
      description = "For testing partial and infinite values";
      license = lib.licenses.mit;
    }
  ) { };

  chaselev-deque = callPackage (
    {
      mkDerivation,
      abstract-deque,
      abstract-deque-tests,
      array,
      atomic-primops,
      base,
      containers,
      ghc-prim,
      HUnit,
      test-framework,
      test-framework-hunit,
      transformers,
      vector,
    }:
    mkDerivation {
      pname = "chaselev-deque";
      version = "0.5.0.5";
      sha256 = "1x2301faqkchkzrvbnganly341jilvg1fmx6lazgbs98cbazhn2d";
      libraryHaskellDepends = [
        abstract-deque
        array
        atomic-primops
        base
        ghc-prim
        transformers
        vector
      ];
      testHaskellDepends = [
        abstract-deque
        abstract-deque-tests
        array
        atomic-primops
        base
        containers
        ghc-prim
        HUnit
        test-framework
        test-framework-hunit
        vector
      ];
      description = "Chase & Lev work-stealing lock-free double-ended queues (deques)";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  chassis = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      comonad,
      composite-base,
      containers,
      distributive,
      extra,
      first-class-families,
      path,
      profunctors,
      text,
      time,
      vinyl,
    }:
    mkDerivation {
      pname = "chassis";
      version = "0.0.6.0";
      sha256 = "0lb2hkyzyq7rm3h6s5n16v4zvqsan98p3k3a1fig9gf61538rkvy";
      libraryHaskellDepends = [
        base
        bytestring
        comonad
        composite-base
        containers
        distributive
        extra
        first-class-families
        path
        profunctors
        text
        time
        vinyl
      ];
      description = "Polykinded Prelude Kernel";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
