# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  chez-grater = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-pretty,
      attoparsec,
      base,
      bytestring,
      case-insensitive,
      containers,
      file-embed,
      file-path-th,
      hashable,
      hspec,
      http-client,
      http-client-tls,
      http-types,
      network-uri,
      optparse-applicative,
      QuickCheck,
      scalpel,
      text,
      unordered-containers,
    }:
    mkDerivation {
      pname = "chez-grater";
      version = "0.1.2";
      sha256 = "0i84fsgh7dsay1p2rw86fxrqasz7w8czfz5jri4ry4ac47ag0mf7";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        attoparsec
        base
        case-insensitive
        containers
        hashable
        http-client
        http-client-tls
        http-types
        network-uri
        QuickCheck
        scalpel
        text
        unordered-containers
      ];
      executableHaskellDepends = [
        aeson
        aeson-pretty
        base
        bytestring
        case-insensitive
        network-uri
        optparse-applicative
        text
      ];
      testHaskellDepends = [
        attoparsec
        base
        bytestring
        case-insensitive
        containers
        file-embed
        file-path-th
        hspec
        http-client
        network-uri
        text
      ];
      description = "Parse and scrape recipe blogs";
      license = lib.meta.getLicenseFromSpdxId "MIT";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "chez-grater";
      broken = true;
    }
  ) { };

}
