# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  chiasma = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      bytestring,
      composition,
      containers,
      exon,
      extra,
      first-class-families,
      lens,
      parsec,
      parsers,
      path,
      polysemy,
      polysemy-conc,
      polysemy-log,
      polysemy-plugin,
      polysemy-process,
      polysemy-time,
      prelate,
      prettyprinter,
      prettyprinter-ansi-terminal,
      random,
      text,
      transformers,
      typed-process,
      uuid,
    }:
    mkDerivation {
      pname = "chiasma";
      version = "0.10.1.0";
      sha256 = "09nsi5lksmbwqxy76h122kzp23632gvfbngs1vilmqhcf6zrbbg5";
      libraryHaskellDepends = [
        attoparsec
        base
        bytestring
        composition
        containers
        exon
        extra
        first-class-families
        lens
        parsec
        parsers
        path
        polysemy
        polysemy-conc
        polysemy-log
        polysemy-plugin
        polysemy-process
        polysemy-time
        prelate
        prettyprinter
        prettyprinter-ansi-terminal
        random
        text
        transformers
        typed-process
        uuid
      ];
      description = "A tmux client for Polysemy";
      license = lib.meta.getLicenseFromSpdxId "BSD-2-Clause-Patent";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  chiasma-test = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      chiasma,
      chronos,
      exon,
      hedgehog,
      lens,
      path,
      path-io,
      polysemy,
      polysemy-chronos,
      polysemy-conc,
      polysemy-log,
      polysemy-plugin,
      polysemy-process,
      polysemy-test,
      polysemy-time,
      prelate,
      tasty,
      tasty-hedgehog,
      text,
      typed-process,
    }:
    mkDerivation {
      pname = "chiasma-test";
      version = "0.10.1.0";
      sha256 = "0gyr4im2f8x335q3svvyr7lrf5z6ypln764spz986qf5ibg4arrb";
      libraryHaskellDepends = [
        base
        bytestring
        chiasma
        chronos
        exon
        hedgehog
        path
        path-io
        polysemy
        polysemy-chronos
        polysemy-conc
        polysemy-log
        polysemy-plugin
        polysemy-process
        polysemy-test
        polysemy-time
        prelate
        text
        typed-process
      ];
      testHaskellDepends = [
        base
        chiasma
        hedgehog
        lens
        path-io
        polysemy
        polysemy-chronos
        polysemy-plugin
        polysemy-test
        prelate
        tasty
        tasty-hedgehog
      ];
      description = "Testing tools for chiasma";
      license = lib.meta.getLicenseFromSpdxId "BSD-2-Clause-Patent";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
