# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  cofunctor = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "cofunctor";
      version = "0.1.0.1";
      sha256 = "0xn4k1c7l9z3g0slbwvlfg9kpfq8jbk0qf9363qz7azv7ks1149p";
      libraryHaskellDepends = [ base ];
      description = "DEPRECATED: use the \"contravariant\" package";
      license = lib.licenses.bsd3;
    }
  ) { };

}
