# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  count = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "count";
      version = "0.0.1";
      sha256 = "1az2vr1rjq4pfgzswwbwgfq4kcb8kq759vn5kl7ghzaqr7b6vkgx";
      libraryHaskellDepends = [ base ];
      description = "Bijective mappings between values and possibly infinite prefixes of [0..]";
      license = lib.licenses.bsd3;
    }
  ) { };

  countable = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      silently,
      tasty,
      tasty-golden,
      tasty-hunit,
    }:
    mkDerivation {
      pname = "countable";
      version = "1.2";
      sha256 = "119v5ms4nyxikfwlmz71qk9gqp53zkpyxc6wm3qp5bm9b6n1ff47";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        bytestring
        silently
        tasty
        tasty-golden
        tasty-hunit
      ];
      description = "Countable, Searchable, Finite, Empty classes";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  countable-inflections = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      exceptions,
      hspec,
      pcre-utils,
      QuickCheck,
      regex-pcre-builtin,
      text,
    }:
    mkDerivation {
      pname = "countable-inflections";
      version = "0.3.0";
      sha256 = "1imi7csng0q6qmwz2ii4j33nwcmiyzi072nvgh36a3lgi0ja6q9x";
      libraryHaskellDepends = [
        base
        bytestring
        exceptions
        pcre-utils
        regex-pcre-builtin
        text
      ];
      testHaskellDepends = [
        base
        hspec
        QuickCheck
        text
      ];
      description = "Countable Text Inflections";
      license = lib.licenses.mit;
    }
  ) { };

  countdown-numbers-game = callPackage (
    {
      mkDerivation,
      base,
      doctest-exitcode-stdio,
      doctest-lib,
      non-empty,
      optparse-applicative,
      QuickCheck,
      utility-ht,
    }:
    mkDerivation {
      pname = "countdown-numbers-game";
      version = "0.0.0.1";
      sha256 = "1warpkqimxjvqrm1jq4nbj3g3bz009alklqs46dh23p3lrgcif61";
      revision = "1";
      editedCabalFile = "05106icwf7kvnwj5109yim2xyx8q5lxvccbn2dqb0q571h5v1a5q";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        non-empty
        optparse-applicative
        utility-ht
      ];
      testHaskellDepends = [
        base
        doctest-exitcode-stdio
        doctest-lib
        non-empty
        QuickCheck
        utility-ht
      ];
      description = "Solve problems from the number round of the Countdown game show";
      license = lib.licenses.bsd3;
      mainProgram = "countdown-numbers-solve";
    }
  ) { };

  counter = callPackage (
    {
      mkDerivation,
      base,
      containers,
    }:
    mkDerivation {
      pname = "counter";
      version = "0.1.0.2";
      sha256 = "0jc34nrbzxzilrr1s2k7krrp9g5xc40hpf2srw6mccfrcsyacsnc";
      libraryHaskellDepends = [
        base
        containers
      ];
      description = "An object frequency counter";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  country = callPackage (
    {
      mkDerivation,
      aeson,
      attoparsec,
      base,
      bytebuild,
      bytehash,
      byteslice,
      bytestring,
      compact,
      contiguous,
      criterion,
      deepseq,
      hashable,
      primitive,
      primitive-unlifted,
      QuickCheck,
      quickcheck-classes,
      scientific,
      tasty,
      tasty-quickcheck,
      text,
      text-short,
      unordered-containers,
    }:
    mkDerivation {
      pname = "country";
      version = "0.2.5.0";
      sha256 = "195jvf322pg06jmcnibx5dz2hvzrq53893hy6cvh9qhh47axd884";
      libraryHaskellDepends = [
        aeson
        attoparsec
        base
        bytebuild
        bytehash
        byteslice
        bytestring
        contiguous
        deepseq
        hashable
        primitive
        primitive-unlifted
        scientific
        text
        text-short
        unordered-containers
      ];
      testHaskellDepends = [
        base
        byteslice
        primitive
        QuickCheck
        quickcheck-classes
        tasty
        tasty-quickcheck
        text
        text-short
      ];
      benchmarkHaskellDepends = [
        base
        bytehash
        compact
        criterion
        text
      ];
      description = "Country data type and functions";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  country-codes = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      deepseq,
      HTF,
      HUnit,
      shakespeare,
      text,
    }:
    mkDerivation {
      pname = "country-codes";
      version = "0.1.4";
      sha256 = "1ilzknxzppldprxvq6lxc1cn2l91iipfh62i9brjqa0jaicidzz3";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        deepseq
        shakespeare
        text
      ];
      testHaskellDepends = [
        aeson
        base
        HTF
        HUnit
      ];
      description = "ISO 3166 country codes and i18n names";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
