# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  crux = callPackage (
    {
      mkDerivation,
      aeson,
      ansi-terminal,
      async,
      attoparsec,
      base,
      bv-sized,
      bytestring,
      config-schema,
      config-value,
      containers,
      contravariant,
      crucible,
      crucible-debug,
      crucible-syntax,
      directory,
      file-embed,
      filepath,
      generic-lens,
      githash,
      Glob,
      lens,
      libBF,
      lumberjack,
      parameterized-utils,
      prettyprinter,
      raw-strings-qq,
      rme-what4,
      semigroupoids,
      simple-get-opt,
      split,
      terminal-size,
      text,
      time,
      vector,
      what4,
      xml,
      yaml,
    }:
    mkDerivation {
      pname = "crux";
      version = "0.9";
      sha256 = "0jr1xryxw584cd254rj5rlgx02cz8pkch2z2889w8mzi14dkb9h6";
      libraryHaskellDepends = [
        aeson
        ansi-terminal
        async
        attoparsec
        base
        bv-sized
        bytestring
        config-schema
        config-value
        containers
        contravariant
        crucible
        crucible-debug
        crucible-syntax
        directory
        file-embed
        filepath
        generic-lens
        githash
        Glob
        lens
        libBF
        lumberjack
        parameterized-utils
        prettyprinter
        raw-strings-qq
        rme-what4
        semigroupoids
        simple-get-opt
        split
        terminal-size
        text
        time
        vector
        what4
        xml
        yaml
      ];
      description = "Simple top-level library for Crucible Simulation";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  crux-llvm = callPackage (
    {
      mkDerivation,
      aeson,
      attoparsec,
      base,
      base16-bytestring,
      bv-sized,
      bytestring,
      config-schema,
      containers,
      crucible,
      crucible-debug,
      crucible-llvm,
      crucible-symio,
      crux,
      cryptohash-sha256,
      directory,
      extra,
      filepath,
      indexed-traversable,
      lens,
      llvm-pretty,
      llvm-pretty-bc-parser,
      logict,
      lumberjack,
      mtl,
      parameterized-utils,
      prettyprinter,
      process,
      regex-base,
      regex-posix,
      tasty,
      tasty-hunit,
      tasty-sugar,
      text,
      time,
      unix,
      versions,
      websockets,
      what4,
    }:
    mkDerivation {
      pname = "crux-llvm";
      version = "0.12";
      sha256 = "0mhbk96inp6cnwaj580sy2z96dri372jwzkmlkqg5624abf7sbxs";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        aeson
        base
        bv-sized
        bytestring
        config-schema
        containers
        crucible
        crucible-debug
        crucible-llvm
        crucible-symio
        crux
        directory
        filepath
        lens
        llvm-pretty
        llvm-pretty-bc-parser
        logict
        mtl
        parameterized-utils
        prettyprinter
        process
        text
        what4
      ];
      executableHaskellDepends = [
        aeson
        attoparsec
        base
        base16-bytestring
        bytestring
        containers
        crucible
        crucible-llvm
        crucible-symio
        crux
        cryptohash-sha256
        directory
        extra
        filepath
        indexed-traversable
        lens
        lumberjack
        process
        text
        time
        unix
        websockets
        what4
      ];
      testHaskellDepends = [
        base
        bytestring
        containers
        crucible
        crucible-llvm
        crucible-symio
        crux
        directory
        extra
        filepath
        lens
        process
        regex-base
        regex-posix
        tasty
        tasty-hunit
        tasty-sugar
        text
        versions
        what4
      ];
      description = "A verification tool for C programs";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
