# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  csa = callPackage (
    {
      mkDerivation,
      base,
      hedgehog,
      hmatrix,
      tasty,
      tasty-hedgehog,
      tasty-hspec,
    }:
    mkDerivation {
      pname = "csa";
      version = "0.1.0";
      sha256 = "0jnhn4lgj5l466c31h2lwslnal3ypk3ma2j75zw0ghjf35i07qvr";
      libraryHaskellDepends = [
        base
        hmatrix
      ];
      testHaskellDepends = [
        base
        hedgehog
        hmatrix
        tasty
        tasty-hedgehog
        tasty-hspec
      ];
      description = "Connection-set algebra (CSA) library";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
