# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  CTRex = callPackage (
    {
      mkDerivation,
      base,
      containers,
      hashable,
      mtl,
      unordered-containers,
    }:
    mkDerivation {
      pname = "CTRex";
      version = "0.6";
      sha256 = "0cjinznkvdrswbqrsha49b6hch7sjv2qq9xllx780klf01kdahi6";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        containers
        hashable
        mtl
        unordered-containers
      ];
      description = "Open records using closed type families";
      license = lib.licenses.bsd3;
    }
  ) { };

}
