# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  cuckoo = callPackage (
    {
      mkDerivation,
      base,
      blake2,
      bytestring,
      criterion,
      doctest,
      hashable,
      hashes,
      primitive,
      QuickCheck,
      random,
      stopwatch,
    }:
    mkDerivation {
      pname = "cuckoo";
      version = "0.3.1";
      sha256 = "0zyba60p70qfg24vlas0yp9fqwwrpiqksp5jq0p1qrmrcv9jyx6n";
      libraryHaskellDepends = [
        base
        bytestring
        hashes
        primitive
        random
      ];
      testHaskellDepends = [
        base
        blake2
        bytestring
        doctest
        hashable
        stopwatch
      ];
      benchmarkHaskellDepends = [
        base
        bytestring
        criterion
        QuickCheck
        stopwatch
      ];
      doHaddock = false;
      description = "Haskell Implementation of Cuckoo Filters";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  cuckoo-filter = callPackage (
    {
      mkDerivation,
      aeson,
      array,
      base,
      bytestring,
      cereal,
      containers,
      criterion,
      hashable,
      QuickCheck,
      random,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      time,
    }:
    mkDerivation {
      pname = "cuckoo-filter";
      version = "0.2.0.2";
      sha256 = "1yya8r3igwms910xp3cc4y1y34f5yw3yqqy1wy49d4xsi6smyjdc";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        array
        base
        bytestring
        cereal
        containers
        hashable
        time
      ];
      executableHaskellDepends = [
        aeson
        array
        base
        bytestring
        cereal
        containers
        criterion
        hashable
        random
        time
      ];
      testHaskellDepends = [
        aeson
        array
        base
        bytestring
        cereal
        containers
        hashable
        QuickCheck
        tasty
        tasty-hunit
        tasty-quickcheck
        time
      ];
      description = "Pure and impure Cuckoo Filter";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "benchmarks";
      broken = true;
    }
  ) { };

}
