# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  desert = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      directory,
      filepath,
      hspec,
      http-conduit,
      MissingH,
      process,
      transformers,
    }:
    mkDerivation {
      pname = "desert";
      version = "0.1.0.6";
      sha256 = "0ks7rmdpx2pg1k9i1diacys1pk0l1sv0qb9qq7w302dzjghlz13g";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        directory
        filepath
        http-conduit
        MissingH
        process
        transformers
      ];
      executableHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        hspec
      ];
      description = "a simple build tool for OCaml projects";
      license = lib.licenses.bsd3;
      mainProgram = "desert";
    }
  ) { };

}
