# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  dnf-repo = callPackage (
    {
      mkDerivation,
      base,
      curl,
      directory,
      extra,
      filepath,
      Glob,
      http-directory,
      safe,
      simple-cmd,
      simple-cmd-args,
      simple-prompt,
    }:
    mkDerivation {
      pname = "dnf-repo";
      version = "0.6.2";
      sha256 = "0njl38nwvdzfxfq17n99mrri8h1kpymv1hwhwanj75f3y5cq4fq3";
      isLibrary = false;
      isExecutable = true;
      enableSeparateDataOutput = true;
      executableHaskellDepends = [
        base
        curl
        directory
        extra
        filepath
        Glob
        http-directory
        safe
        simple-cmd
        simple-cmd-args
        simple-prompt
      ];
      testHaskellDepends = [
        base
        simple-cmd
      ];
      description = "A dnf wrapper with fine control of enabled repos";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "dnf-repo";
    }
  ) { };

}
