# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  dwarf = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      containers,
    }:
    mkDerivation {
      pname = "dwarf";
      version = "0.23";
      sha256 = "0h6bzh628cz0qnbk4aiz5859r9va99q307scbwzvs1wn3nm6dszl";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
      ];
      description = "Parser for DWARF debug format";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  dwarf-el = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      containers,
      text,
      text-show,
      transformers,
    }:
    mkDerivation {
      pname = "dwarf-el";
      version = "0.3";
      sha256 = "177y84zgl215jivbxifn09w8mdv0k65bxyky0l1hadd64hgp2nq7";
      revision = "1";
      editedCabalFile = "134jqfl7zrk1l6jcv3ws4511x1097yzhn2gi0vcn0bkz6qc8lr3s";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
        text
        text-show
        transformers
      ];
      description = "Parser for DWARF debug format";
      license = lib.licenses.bsd3;
    }
  ) { };

  dwarfadt = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      bytestring-mmap,
      containers,
      dwarf-el,
      elf,
      lens,
      pretty,
      text,
      text-show,
      transformers,
    }:
    mkDerivation {
      pname = "dwarfadt";
      version = "0.6";
      sha256 = "1fzkigzrm6s9060vmxsgw4bwzpfvcxc510ghb1rkqh5gslqszcb0";
      revision = "1";
      editedCabalFile = "0rdydzqy6g24jgddc4sgg1244l9mdkhp1zyjnvjfg0jbrkgqcy73";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        bytestring-mmap
        containers
        dwarf-el
        elf
        lens
        pretty
        text
        text-show
        transformers
      ];
      executableHaskellDepends = [
        base
        containers
        dwarf-el
      ];
      description = "High-level wrapper around the dwarf library";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
