# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  electrs-client = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      envparse,
      generic-pretty-instances,
      GenericPretty,
      hex-text,
      hspec,
      network,
      network-bitcoin,
      SHA,
      text,
      transformers,
      unbounded-delays,
      universum,
      unliftio,
    }:
    mkDerivation {
      pname = "electrs-client";
      version = "0.1.0.0";
      sha256 = "1ywmxc4x5p108hv7l5ymr60alk01mmgnz6dn8h4xcnfnrck6p9b1";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        envparse
        generic-pretty-instances
        GenericPretty
        hex-text
        network
        network-bitcoin
        SHA
        text
        transformers
        unbounded-delays
        universum
        unliftio
      ];
      testHaskellDepends = [
        base
        hspec
        network-bitcoin
      ];
      description = "Electrs client library for Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  electrum-mnemonic = callPackage (
    {
      mkDerivation,
      base,
      tasty,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "electrum-mnemonic";
      version = "0.1.3";
      sha256 = "1xma4x5n1g0bzda32lwwaibwvlxciknk4c2j5qhgi80q9gfjspn0";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        tasty
        tasty-quickcheck
      ];
      description = "easy to remember mnemonic for a high-entropy value";
      license = lib.licenses.gpl3Only;
    }
  ) { };

}
