# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  elsa = callPackage (
    {
      mkDerivation,
      ansi-terminal,
      array,
      base,
      dequeue,
      directory,
      filepath,
      hashable,
      json,
      megaparsec,
      mtl,
      tasty,
      tasty-hunit,
      unordered-containers,
    }:
    mkDerivation {
      pname = "elsa";
      version = "0.3.0.0";
      sha256 = "1gxlcplbqxixahkgmvgrc1754svdmqp4ri1acx3sc4yxnqd1z7h9";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        ansi-terminal
        array
        base
        dequeue
        directory
        filepath
        hashable
        json
        megaparsec
        mtl
        unordered-containers
      ];
      executableHaskellDepends = [
        base
        mtl
      ];
      testHaskellDepends = [
        base
        directory
        filepath
        tasty
        tasty-hunit
      ];
      description = "A tiny language for understanding the lambda-calculus";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "elsa";
    }
  ) { };

}
