# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  ephemeral = callPackage (
    {
      mkDerivation,
      base,
      free,
      numhask,
      profunctors,
    }:
    mkDerivation {
      pname = "ephemeral";
      version = "0.0.2.0";
      sha256 = "06dy7fm9jhis8kipbyw8ca5xz8c880kyibfcfr4mf1ai3kjah7g7";
      libraryHaskellDepends = [
        base
        free
        numhask
        profunctors
      ];
      description = "See readme.md";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  ephemeral-pg = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      directory,
      filepath,
      hashable,
      hasql,
      hspec,
      network,
      process,
      QuickCheck,
      temporary,
      text,
      transformers,
      typed-process,
      unix,
    }:
    mkDerivation {
      pname = "ephemeral-pg";
      version = "0.2.1.0";
      sha256 = "1fcwbmp6rrvx2hzal6nhs6nn7wdp0x119rwnlk9ilixxzx25188g";
      libraryHaskellDepends = [
        base
        bytestring
        directory
        filepath
        hashable
        hasql
        network
        process
        temporary
        text
        transformers
        typed-process
        unix
      ];
      testHaskellDepends = [
        base
        hasql
        hspec
        QuickCheck
        text
      ];
      description = "Temporary PostgreSQL databases for testing";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
