# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  exact-combinatorics = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "exact-combinatorics";
      version = "0.2.0.11";
      sha256 = "0qrhgd468ljpnfciaxzimmn1rhvapcrrsy4wb2r08hn3vjflmd3n";
      libraryHaskellDepends = [ base ];
      description = "Efficient exact computation of combinatoric functions";
      license = lib.licenses.bsd3;
    }
  ) { };

  exact-cover = callPackage (
    {
      mkDerivation,
      base,
      containers,
      tasty,
      tasty-hunit,
    }:
    mkDerivation {
      pname = "exact-cover";
      version = "0.1.0.0";
      sha256 = "0qnnr1ri953jybgifivpkjmnq72n67bm2rmiaqhzx4ck01x0grz4";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
      ];
      testHaskellDepends = [
        base
        containers
        tasty
        tasty-hunit
      ];
      description = "Efficient exact cover solver";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  exact-kantorovich = callPackage (
    {
      mkDerivation,
      base,
      containers,
      extra,
      matrix,
      monad-logger,
      simplex-method,
      tasty,
      tasty-hunit,
    }:
    mkDerivation {
      pname = "exact-kantorovich";
      version = "0.1.0.0";
      sha256 = "0w410cfffq79b1l70nawa0lq82awh0bjicag3x5blz7c0c8wa9f7";
      libraryHaskellDepends = [
        base
        containers
        extra
        matrix
        monad-logger
        simplex-method
      ];
      testHaskellDepends = [
        base
        containers
        tasty
        tasty-hunit
      ];
      description = "Exact Kantorovich distance between finite probability measures";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  exact-pi = callPackage (
    {
      mkDerivation,
      base,
      numtype-dk,
      QuickCheck,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "exact-pi";
      version = "0.5.0.2";
      sha256 = "1xmc3vlzfccrn5szglnxx13akxw2xacgl40kqh0kiw82d58x47a4";
      libraryHaskellDepends = [
        base
        numtype-dk
      ];
      testHaskellDepends = [
        base
        numtype-dk
        QuickCheck
        tasty
        tasty-hunit
        tasty-quickcheck
      ];
      description = "Exact rational multiples of pi (and integer powers of pi)";
      license = lib.licenses.mit;
    }
  ) { };

  exact-real = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      cabal-doctest,
      checkers,
      criterion,
      doctest,
      groups,
      integer-gmp,
      QuickCheck,
      random,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      tasty-th,
    }:
    mkDerivation {
      pname = "exact-real";
      version = "0.12.5.1";
      sha256 = "0zm2rb2zhpf7ipiq4k06ix66ps026y0v83qqh83x5yfqv9hz22c7";
      setupHaskellDepends = [
        base
        Cabal
        cabal-doctest
      ];
      libraryHaskellDepends = [
        base
        integer-gmp
        random
      ];
      testHaskellDepends = [
        base
        checkers
        doctest
        groups
        QuickCheck
        random
        tasty
        tasty-hunit
        tasty-quickcheck
        tasty-th
      ];
      benchmarkHaskellDepends = [
        base
        criterion
      ];
      description = "Exact real arithmetic";
      license = lib.licenses.mit;
    }
  ) { };

  exact-real-positional = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "exact-real-positional";
      version = "0.0.0";
      sha256 = "0qh1aqyi2k7djwqykj888hxjisip9ahg2ap43cj0xmdvfh9p0351";
      libraryHaskellDepends = [ base ];
      description = "Framework for Exact Real Arithmetic in the Positional Number System";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
