# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  fbrnch = callPackage (
    {
      mkDerivation,
      aeson,
      async,
      base,
      bodhi,
      bugzilla-redhat,
      bytestring,
      config-ini,
      copr-api,
      directory,
      either,
      email-validate,
      extra,
      fedora-krb,
      fedora-releases,
      filepath,
      http-conduit,
      http-directory,
      http-query,
      koji,
      network-uri,
      pagure,
      pretty-terminal,
      process,
      rpm-nvr,
      rpmbuild-order,
      safe,
      say,
      select-rpms,
      simple-cmd,
      simple-cmd-args,
      simple-prompt,
      text,
      time,
      typed-process,
      unix,
      utf8-string,
      xdg-basedir,
    }:
    mkDerivation {
      pname = "fbrnch";
      version = "1.7.1";
      sha256 = "1xsq70xpd0qgz0krlmm31b821ir94sc8qa0qpshjlcfja882p11l";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        aeson
        async
        base
        bodhi
        bugzilla-redhat
        bytestring
        config-ini
        copr-api
        directory
        either
        email-validate
        extra
        fedora-krb
        fedora-releases
        filepath
        http-conduit
        http-directory
        http-query
        koji
        network-uri
        pagure
        pretty-terminal
        process
        rpm-nvr
        rpmbuild-order
        safe
        say
        select-rpms
        simple-cmd
        simple-cmd-args
        simple-prompt
        text
        time
        typed-process
        unix
        utf8-string
        xdg-basedir
      ];
      description = "Fedora packager tool to build package branches";
      license = lib.licenses.gpl2Only;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "fbrnch";
    }
  ) { };

  fbrnch_1_8 = callPackage (
    {
      mkDerivation,
      aeson,
      async,
      base,
      bodhi,
      bugzilla-redhat,
      bytestring,
      config-ini,
      copr-api,
      directory,
      either,
      email-validate,
      extra,
      fedora-krb,
      fedora-releases,
      filepath,
      http-conduit,
      http-directory,
      http-query,
      koji,
      network-uri,
      pagure,
      pretty-terminal,
      process,
      rpm-nvr,
      rpmbuild-order,
      safe,
      say,
      select-rpms,
      simple-cmd,
      simple-cmd-args,
      simple-prompt,
      text,
      time,
      typed-process,
      unix,
      utf8-string,
      xdg-basedir,
    }:
    mkDerivation {
      pname = "fbrnch";
      version = "1.8";
      sha256 = "0zl0b8h9mnk86fjq4dbdr5xjgav6ikx9whayvw3cmqdhrx29dw1y";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        aeson
        async
        base
        bodhi
        bugzilla-redhat
        bytestring
        config-ini
        copr-api
        directory
        either
        email-validate
        extra
        fedora-krb
        fedora-releases
        filepath
        http-conduit
        http-directory
        http-query
        koji
        network-uri
        pagure
        pretty-terminal
        process
        rpm-nvr
        rpmbuild-order
        safe
        say
        select-rpms
        simple-cmd
        simple-cmd-args
        simple-prompt
        text
        time
        typed-process
        unix
        utf8-string
        xdg-basedir
      ];
      description = "Fedora packager tool to build package branches";
      license = lib.meta.getLicenseFromSpdxId "GPL-2.0-or-later";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "fbrnch";
    }
  ) { };

}
