# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Finance-Quote-Yahoo = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-conduit,
      network,
      old-locale,
      time,
    }:
    mkDerivation {
      pname = "Finance-Quote-Yahoo";
      version = "0.8.0";
      sha256 = "1d786xkrj0h270mfwxxkfxysmk78xkz2jdj8w1iin3hgy3ramifz";
      libraryHaskellDepends = [
        base
        bytestring
        http-conduit
        network
        old-locale
        time
      ];
      description = "Obtain quote data from finance.yahoo.com";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  Finance-Treasury = callPackage (
    {
      mkDerivation,
      base,
      containers,
      HTTP,
      HTTP-Simple,
      hxt,
      hxt-filter,
      network,
      old-locale,
      time,
    }:
    mkDerivation {
      pname = "Finance-Treasury";
      version = "0.1.2";
      sha256 = "17wxdwj8162c0yawz4anjs6d3fjbhs3b05wk319acblksjx60sal";
      libraryHaskellDepends = [
        base
        containers
        HTTP
        HTTP-Simple
        hxt
        hxt-filter
        network
        old-locale
        time
      ];
      description = "Obtain Treasury yield curve data";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  final = callPackage (
    {
      mkDerivation,
      base,
      stm,
      transformers,
    }:
    mkDerivation {
      pname = "final";
      version = "0.1";
      sha256 = "189vby5ym6hcjpz6y9chlgkyzl8wnndqkhzk7s7qy8mksr3g66f9";
      libraryHaskellDepends = [
        base
        stm
        transformers
      ];
      description = "utility to add extra safety to monadic returns";
      license = lib.licenses.bsd3;
    }
  ) { };

  final-pretty-printer = callPackage (
    {
      mkDerivation,
      ansi-terminal,
      base,
      containers,
      exceptions,
      mtl,
      temporary,
      text,
    }:
    mkDerivation {
      pname = "final-pretty-printer";
      version = "0.1.0.0";
      sha256 = "0p0g73nq7154msvzazkn79fjnkzd939chgmxqdi9xbcpq47zgac2";
      libraryHaskellDepends = [
        ansi-terminal
        base
        containers
        exceptions
        mtl
        temporary
        text
      ];
      description = "Extensible pretty printing with semantic annotations and proportional fonts";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
