# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  flux-monoid = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "flux-monoid";
      version = "1.0.0.0";
      sha256 = "09brqhyv0hdq2df21pk63551ig8xxj68zvjzi46w4f47h2g3bw60";
      libraryHaskellDepends = [ base ];
      description = "A monoid for tracking changes";
      license = lib.licenses.bsd3;
    }
  ) { };

}
