# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  FractalArt = callPackage (
    {
      mkDerivation,
      base,
      directory,
      filepath,
      JuicyPixels,
      libx11,
      mwc-random,
      primitive,
      random,
      vector,
    }:
    mkDerivation {
      pname = "FractalArt";
      version = "0.2.0.3";
      sha256 = "1z50cfy4z7c274j5wma3g7b9rwnq309ra2njjk2r7n9hildzzw6y";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        directory
        filepath
        JuicyPixels
        mwc-random
        primitive
        random
        vector
      ];
      executableSystemDepends = [ libx11 ];
      description = "Generates colorful wallpapers";
      license = lib.licenses.mit;
      mainProgram = "FractalArt";
    }
  ) { inherit (pkgs) libx11; };

  Fractaler = callPackage (
    {
      mkDerivation,
      base,
      FTGL,
      GLFW-b,
      OpenGLRaw,
      parallel,
      random,
      time,
    }:
    mkDerivation {
      pname = "Fractaler";
      version = "3";
      sha256 = "0h6jlrd5wz40pjkqy75mvcgb8bqpqlq7vypy1062kb2cngl8235f";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        FTGL
        GLFW-b
        OpenGLRaw
        parallel
        random
        time
      ];
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "Fractaler";
      broken = true;
    }
  ) { };

  fractal = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "fractal";
      version = "0.0.1";
      sha256 = "0iw5454mi0ms3w62m118rlqr6lr1j9mbxwfj26mlc5p38bq9k7ds";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [ base ];
      description = "Draw Newton, Julia and Mandelbrot fractals";
      license = lib.licenses.bsd3;
      mainProgram = "fractal";
    }
  ) { };

  fractals = callPackage (
    {
      mkDerivation,
      base,
      integer-gmp,
      QuickCheck,
    }:
    mkDerivation {
      pname = "fractals";
      version = "0.1.0.0";
      sha256 = "0jj2y8w5zqh0d093ayaml1shlr0am6lha4n6nm602lik09vs3g1x";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        integer-gmp
        QuickCheck
      ];
      description = "A collection of useful fractal curve encoders";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  fractaltext = callPackage (
    {
      mkDerivation,
      base,
      containers,
      directory,
      filepath,
      free,
      generic-data,
      hedgehog,
      json,
      microlens-platform,
      streaming,
      tasty,
      tasty-discover,
      tasty-hedgehog,
      tasty-hunit,
      text,
      text-short,
      transformers,
      vector,
    }:
    mkDerivation {
      pname = "fractaltext";
      version = "0.1.0";
      sha256 = "11wcldm5m54yxxiranghd7rw03mvqwg3zk5jn6n5cipc1r0rvlb0";
      libraryHaskellDepends = [
        base
        containers
        free
        generic-data
        microlens-platform
        streaming
        text
        text-short
        transformers
        vector
      ];
      testHaskellDepends = [
        base
        containers
        directory
        filepath
        hedgehog
        json
        microlens-platform
        streaming
        tasty
        tasty-hedgehog
        tasty-hunit
        text
        text-short
        vector
      ];
      testToolDepends = [ tasty-discover ];
      description = "Reference implementation of FractalText";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
    }
  ) { };

  fraction = callPackage (
    {
      mkDerivation,
      base,
      semigroups,
    }:
    mkDerivation {
      pname = "fraction";
      version = "0.1.0.6";
      sha256 = "0ajkrp7babip4y0symj65yanyazsazp7lsbbsa3il2b6kp9fwgxd";
      libraryHaskellDepends = [
        base
        semigroups
      ];
      description = "Fractions";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  fractionizer = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "fractionizer";
      version = "0.17.0.0";
      sha256 = "0y2rkbmpzhn0zz273i1lfxv7f270yv89nmacs9m17rhjcj9n7243";
      libraryHaskellDepends = [ base ];
      description = "Numbers in the range [0.005, 1] as a sum of 2, 3, 4 or 5 unit fractions of special types.";
      license = lib.meta.getLicenseFromSpdxId "MIT";
    }
  ) { };

}
