# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Ganymede = callPackage (
    {
      mkDerivation,
      base,
      containers,
      directory,
      filepath,
      mtl,
      parsec,
      transformers,
    }:
    mkDerivation {
      pname = "Ganymede";
      version = "0.0.0.5";
      sha256 = "1fmb6fpdfk21yxrvlgdg32qymzirfbygsq6p4jvm925kvpwqbcwk";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        containers
        directory
        filepath
        mtl
        parsec
        transformers
      ];
      description = "An Io interpreter in Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "ganymede";
      broken = true;
    }
  ) { };

}
