# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  genai-lib = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      containers,
      http-client,
      http-client-tls,
      scientific,
      servant,
      servant-client,
      servant-client-core,
      string-conv,
      text,
      time,
    }:
    mkDerivation {
      pname = "genai-lib";
      version = "2.1.0";
      sha256 = "1plzkp0gjg38m4zl6ijxpqfbbpdn2yi7i1nc6d5wsqa5mbc75svp";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        containers
        http-client
        http-client-tls
        scientific
        servant
        servant-client
        servant-client-core
        string-conv
        text
        time
      ];
      executableHaskellDepends = [
        base
        text
      ];
      description = "A library for interacting with various generative AI LLMs";
      license = lib.meta.getLicenseFromSpdxId "ISC";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
