# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  genprog = callPackage (
    {
      mkDerivation,
      base,
      MonadRandom,
      syb,
      syz,
    }:
    mkDerivation {
      pname = "genprog";
      version = "0.1.0.2";
      sha256 = "1a9b2h4swfwx5zwcyr2zdhxdxi9f68pwpglijxhxb5javjc4dppr";
      libraryHaskellDepends = [
        base
        MonadRandom
        syb
        syz
      ];
      description = "Genetic programming library";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
