# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Get = callPackage (
    {
      mkDerivation,
      base,
      constraints,
      singletons,
    }:
    mkDerivation {
      pname = "Get";
      version = "0.2018.1.10";
      sha256 = "18i6ags8acgi651453g7axw7isiqivjhb4s0nh3lyl87ynqsch6l";
      libraryHaskellDepends = [
        base
        constraints
        singletons
      ];
      testHaskellDepends = [
        base
        constraints
        singletons
      ];
      description = "get stuff out of stuff";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
