# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  GlomeTrace = callPackage (
    {
      mkDerivation,
      array,
      base,
      GlomeVec,
    }:
    mkDerivation {
      pname = "GlomeTrace";
      version = "0.3";
      sha256 = "0n1290ls68fsky3a80fvfdq6bycvmpn3i3kmflq6yn45qa959f0k";
      libraryHaskellDepends = [
        array
        base
        GlomeVec
      ];
      description = "Ray Tracing Library";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  GlomeVec = callPackage (
    {
      mkDerivation,
      array,
      base,
    }:
    mkDerivation {
      pname = "GlomeVec";
      version = "0.2";
      sha256 = "08hyiadkbkmcsd1g51xvxqzp6l94hnqqbz4r6yk0zk29iawq8610";
      libraryHaskellDepends = [
        array
        base
      ];
      description = "Simple 3D vector library";
      license = "GPL";
    }
  ) { };

  GlomeView = callPackage (
    {
      mkDerivation,
      base,
      deepseq,
      GlomeTrace,
      GlomeVec,
      monad-par,
      random,
      SDL,
      time,
      vector,
    }:
    mkDerivation {
      pname = "GlomeView";
      version = "0.3";
      sha256 = "0plglb289gadk8mqxgqj8n25xa6dql2jl0b8cm9v7q5rwykx0kbq";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        deepseq
        GlomeTrace
        GlomeVec
        monad-par
        random
        SDL
        time
        vector
      ];
      description = "SDL Frontend for Glome ray tracer";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "Glome";
    }
  ) { };

  glome-hs = callPackage (
    {
      mkDerivation,
      array,
      base,
      GlomeTrace,
      GlomeVec,
      GLUT,
      haskell98,
      OpenGL,
      parallel,
      random,
      time,
    }:
    mkDerivation {
      pname = "glome-hs";
      version = "0.61";
      sha256 = "069j4xvh5039xkg300h1cwa0lyvkycixasxr8zh4iqyl1g5bcvs8";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        array
        base
        GlomeTrace
        GlomeVec
        GLUT
        haskell98
        OpenGL
        parallel
        random
        time
      ];
      executableHaskellDepends = [
        array
        base
        GlomeTrace
        GlomeVec
        GLUT
        haskell98
        OpenGL
        parallel
        random
        time
      ];
      doHaddock = false;
      description = "ray tracer";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "Glome";
    }
  ) { };

}
