# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  goal-core = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      cassava,
      containers,
      criterion,
      deepseq,
      directory,
      finite-typelits,
      ghc-typelits-knownnat,
      ghc-typelits-natnormalise,
      hmatrix,
      hmatrix-gsl,
      math-functions,
      mwc-probability,
      mwc-random,
      optparse-applicative,
      primitive,
      process,
      vector,
      vector-sized,
    }:
    mkDerivation {
      pname = "goal-core";
      version = "0.20";
      sha256 = "0lqcyllfg0r2dxd6lwil1i4wbdlpxq4plyxamjwhi7s5k41q1k93";
      libraryHaskellDepends = [
        async
        base
        bytestring
        cassava
        containers
        criterion
        deepseq
        directory
        finite-typelits
        ghc-typelits-knownnat
        ghc-typelits-natnormalise
        hmatrix
        hmatrix-gsl
        math-functions
        optparse-applicative
        primitive
        process
        vector
        vector-sized
      ];
      benchmarkHaskellDepends = [
        base
        criterion
        hmatrix
        mwc-probability
        mwc-random
      ];
      description = "Common, non-geometric tools for use with Goal";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  goal-geometry = callPackage (
    {
      mkDerivation,
      ad,
      base,
      ghc-typelits-knownnat,
      ghc-typelits-natnormalise,
      goal-core,
      indexed-list-literals,
    }:
    mkDerivation {
      pname = "goal-geometry";
      version = "0.20";
      sha256 = "0bjyy0q7f4wmwna019wbaf7gfflpkng60f2rqxnffqcar9q127jk";
      libraryHaskellDepends = [
        ad
        base
        ghc-typelits-knownnat
        ghc-typelits-natnormalise
        goal-core
        indexed-list-literals
      ];
      description = "The basic geometric type system of Goal";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  goal-graphical = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cassava,
      containers,
      criterion,
      ghc-typelits-knownnat,
      ghc-typelits-natnormalise,
      goal-core,
      goal-geometry,
      goal-probability,
      hmatrix,
      hmatrix-special,
      mwc-probability,
      mwc-random,
      parallel,
      statistics,
      vector,
    }:
    mkDerivation {
      pname = "goal-graphical";
      version = "0.20";
      sha256 = "1ckp0238wkdvsxpi7mc7vp0ymfhmpz4hh2nzgpfr09c9dz02cv61";
      libraryHaskellDepends = [
        base
        containers
        ghc-typelits-knownnat
        ghc-typelits-natnormalise
        goal-core
        goal-geometry
        goal-probability
        hmatrix
        hmatrix-special
        mwc-probability
        mwc-random
        parallel
        statistics
        vector
      ];
      benchmarkHaskellDepends = [
        base
        bytestring
        cassava
        criterion
        goal-core
        goal-geometry
        goal-probability
      ];
      description = "Optimization of latent variable and dynamical models with Goal";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  goal-probability = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cassava,
      containers,
      criterion,
      ghc-typelits-knownnat,
      ghc-typelits-natnormalise,
      goal-core,
      goal-geometry,
      hmatrix,
      hmatrix-special,
      mwc-random,
      parallel,
      statistics,
      vector,
    }:
    mkDerivation {
      pname = "goal-probability";
      version = "0.20";
      sha256 = "14yfsazxrn8g3ygbwx8zs9xgjjzi5q1dw6sqbdkrixb8ffw7xszm";
      libraryHaskellDepends = [
        base
        containers
        ghc-typelits-knownnat
        ghc-typelits-natnormalise
        goal-core
        goal-geometry
        hmatrix
        hmatrix-special
        mwc-random
        parallel
        statistics
        vector
      ];
      benchmarkHaskellDepends = [
        base
        bytestring
        cassava
        criterion
        goal-core
        goal-geometry
      ];
      description = "Optimization on manifolds of probability distributions with Goal";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  goal-simulation = callPackage (
    {
      mkDerivation,
      base,
      cairo,
      clock,
      directory,
      goal-core,
      goal-geometry,
      goal-probability,
      gtk,
      hmatrix,
      machines,
      mtl,
      vector,
    }:
    mkDerivation {
      pname = "goal-simulation";
      version = "0.1";
      sha256 = "00c2cx4z63gphjhipwrm2r6872c59g03kb49ksm8yiq0xrwwr1sp";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        cairo
        clock
        goal-core
        goal-geometry
        goal-probability
        gtk
        hmatrix
        machines
        vector
      ];
      executableHaskellDepends = [
        base
        directory
        goal-core
        goal-geometry
        goal-probability
        hmatrix
        mtl
        vector
      ];
      description = "Mealy based simulation tools";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
