# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  gofer-prelude = callPackage (
    {
      mkDerivation,
      base,
      ghc-prim,
    }:
    mkDerivation {
      pname = "gofer-prelude";
      version = "2.30.3";
      sha256 = "1whl3fvwxh26nsb4l6brljsmwl891w5yxlsv69mdfvfb1rl7p64f";
      libraryHaskellDepends = [
        base
        ghc-prim
      ];
      description = "The Gofer 2.30 standard prelude";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
