# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  half = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      deepseq,
      QuickCheck,
      tasty,
      tasty-quickcheck,
      template-haskell,
    }:
    mkDerivation {
      pname = "half";
      version = "0.3.3";
      sha256 = "00mb2xfz0q8sq8zxqpw3ycp1p8gjhlgc0wxh5xr7kzyn52b08xpl";
      revision = "2";
      editedCabalFile = "1jy2q5nmf3mi97s44zyzrmq0dg3sgn1z0jcw5p19lhfdz2vlk5dk";
      libraryHaskellDepends = [
        base
        binary
        deepseq
        template-haskell
      ];
      testHaskellDepends = [
        base
        binary
        bytestring
        QuickCheck
        tasty
        tasty-quickcheck
      ];
      description = "Half-precision floating-point";
      license = lib.licenses.bsd3;
    }
  ) { };

  half-space = callPackage (
    {
      mkDerivation,
      base,
      call-stack,
      equational-reasoning,
      manifolds-core,
      vector-space,
    }:
    mkDerivation {
      pname = "half-space";
      version = "0.1.1.0";
      sha256 = "1wcnlbag6jr3fzb867izwsz1bdp94b3nv0xjg0kbs7kkpakk0l7d";
      libraryHaskellDepends = [
        base
        call-stack
        equational-reasoning
        manifolds-core
        vector-space
      ];
      description = "Additive monoids generalising vector spaces";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  halfs = callPackage (
    {
      mkDerivation,
      array,
      base,
      bytestring,
      cereal,
      containers,
      directory,
      filepath,
      fingertree,
      HFuse,
      mtl,
      QuickCheck,
      random,
      time,
      unix,
    }:
    mkDerivation {
      pname = "halfs";
      version = "2.0";
      sha256 = "1k47q0vp0cmvmxz28hmv8dgniz9ks7h0wjjmdkjgvb77p8jj2akd";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        array
        base
        bytestring
        cereal
        containers
        directory
        filepath
        fingertree
        mtl
        QuickCheck
        random
        time
        unix
      ];
      executableHaskellDepends = [
        array
        base
        bytestring
        cereal
        containers
        directory
        filepath
        fingertree
        HFuse
        mtl
        QuickCheck
        random
        time
        unix
      ];
      description = "The HAskelL File System (\"halfs\" -- intended for use on the HaLVM)";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  halfsplit = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "halfsplit";
      version = "0.4.3.0";
      sha256 = "1y09vl853nsc6fx19bwmmmh9k7di825j4y7rsm06wyk35m911yv7";
      libraryHaskellDepends = [ base ];
      description = "A library to provide special kind of two-column output for Phladiprelio";
      license = lib.meta.getLicenseFromSpdxId "MIT";
    }
  ) { };

}
