# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  HaXPath = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      HList,
      HUnit,
      text,
    }:
    mkDerivation {
      pname = "HaXPath";
      version = "0.3.0.1";
      sha256 = "048n17ab3dx3bmpa5dpdixqg07mjq800imibacjakahb1kklvcgv";
      libraryHaskellDepends = [
        base
        HList
      ];
      testHaskellDepends = [
        base
        bytestring
        HUnit
        text
      ];
      description = "An XPath-generating embedded domain specific language";
      license = lib.licenses.bsd3;
    }
  ) { };

  haxparse = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      containers,
      data-binary-ieee754,
      data-default,
      mtl,
      optparse-applicative,
      parsec,
      split,
      template-haskell,
      transformers,
      utf8-string,
      zlib,
    }:
    mkDerivation {
      pname = "haxparse";
      version = "0.3.1.0";
      sha256 = "12ksmhmk1yns8znh9srqm53q4by8dibdvkd9qhbihiwdyz137y6j";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
        data-binary-ieee754
        data-default
        mtl
        parsec
        split
        template-haskell
        transformers
        utf8-string
        zlib
      ];
      executableHaskellDepends = [
        base
        binary
        bytestring
        containers
        data-binary-ieee754
        data-default
        mtl
        optparse-applicative
        parsec
        split
        template-haskell
        transformers
        utf8-string
        zlib
      ];
      description = "Readable HaxBall replays";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "haxparse";
      broken = true;
    }
  ) { };

}
