# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  HCodecs = callPackage (
    {
      mkDerivation,
      array,
      base,
      bytestring,
      fail,
      QuickCheck,
      random,
      semigroups,
    }:
    mkDerivation {
      pname = "HCodecs";
      version = "0.5.2";
      sha256 = "0gbspig721viwncsfg9m4qc9jbl9rz93ra74d5b1zw9pw7rhy5ji";
      libraryHaskellDepends = [
        array
        base
        bytestring
        fail
        QuickCheck
        random
        semigroups
      ];
      testHaskellDepends = [
        array
        base
        bytestring
        fail
        QuickCheck
        random
        semigroups
      ];
      description = "A library to read, write and manipulate MIDI, WAVE, and SoundFont2 files";
      license = lib.licenses.bsd3;
    }
  ) { };

}
