# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hcom = callPackage (
    { mkDerivation }:
    mkDerivation {
      pname = "hcom";
      version = "0.0.0.6";
      sha256 = "1793wnjrny1nydqnbvvh1wsq9qnnknf80fmpxvz281mdpjz6n1h2";
      doHaddock = false;
      description = "Haskell COM support library";
      license = lib.licenses.bsd3;
    }
  ) { };

}
