# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hdf = callPackage (
    {
      mkDerivation,
      base,
      directory,
      fgl,
      fgl-visualize,
      filepath,
      hosc,
      hsc3,
      murmur-hash,
      process,
      split,
      transformers,
    }:
    mkDerivation {
      pname = "hdf";
      version = "0.15";
      sha256 = "11nf9wlymdhydf0bhh9gdl0cdn0i4mbvx3hfdcmnxfvag5jmfbkk";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        directory
        fgl
        fgl-visualize
        filepath
        hosc
        hsc3
        murmur-hash
        process
        split
        transformers
      ];
      description = "HDF: Uniform Rate Audio Signal Processing in Haskell";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
