# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hdph = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      containers,
      deepseq,
      hdph-closure,
      mtl,
      network,
      network-info,
      network-multicast,
      network-transport,
      network-transport-tcp,
      random,
      template-haskell,
      time,
    }:
    mkDerivation {
      pname = "hdph";
      version = "0.0.1";
      sha256 = "116499cr0pcc1gg7aniprlcp9vp8s61b4vk7rcm673nw3lay496a";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        cereal
        containers
        deepseq
        hdph-closure
        mtl
        network
        network-info
        network-multicast
        network-transport
        network-transport-tcp
        random
        template-haskell
        time
      ];
      executableHaskellDepends = [
        base
        bytestring
        cereal
        containers
        deepseq
        hdph-closure
        mtl
        network
        network-info
        network-multicast
        network-transport
        network-transport-tcp
        random
        template-haskell
        time
      ];
      description = "Haskell distributed parallel Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  hdph-closure = callPackage (
    {
      mkDerivation,
      array,
      base,
      bytestring,
      cereal,
      containers,
      deepseq,
      template-haskell,
    }:
    mkDerivation {
      pname = "hdph-closure";
      version = "0.0.1";
      sha256 = "0rcmp5i7jvpghg8nql5wlidbyjs79cxxmdb6bq3xxk806gdj66d8";
      libraryHaskellDepends = [
        array
        base
        bytestring
        cereal
        containers
        deepseq
        template-haskell
      ];
      description = "Explicit closures in Haskell distributed parallel Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
