# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  heap = callPackage (
    {
      mkDerivation,
      base,
      QuickCheck,
    }:
    mkDerivation {
      pname = "heap";
      version = "1.0.4";
      sha256 = "0ahpsfmb76728w71xn4021ad7z752n6aqqgzdpcyis9i22g4ihm4";
      revision = "1";
      editedCabalFile = "010mvg5syk0iprrin4kmqf21dmabyncmz1b65w5p05j9f4w22jfj";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        QuickCheck
      ];
      description = "Heaps in Haskell";
      license = lib.licenses.bsd3;
    }
  ) { };

  heap-console = callPackage (
    {
      mkDerivation,
      base,
      containers,
      exceptions,
      ghc-heap,
      ghc-prim,
      haskeline,
      hspec,
      hspec-discover,
      mtl,
      show-combinators,
    }:
    mkDerivation {
      pname = "heap-console";
      version = "0.1.0.1";
      sha256 = "1z2sdw64w50q2353ccsjpahncdp8czihpkizclgvx1gkqiv9mv02";
      libraryHaskellDepends = [
        base
        containers
        exceptions
        ghc-heap
        ghc-prim
        haskeline
        mtl
        show-combinators
      ];
      testHaskellDepends = [
        base
        hspec
      ];
      testToolDepends = [ hspec-discover ];
      description = "interactively inspect Haskell values at runtime";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  heaps = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "heaps";
      version = "0.4.1";
      sha256 = "10h3m98fjj114x3nffs0ajllc6z1dbb4g9804j8kq2rd79ka8qw7";
      libraryHaskellDepends = [ base ];
      description = "Asymptotically optimal Brodal/Okasaki heaps";
      license = lib.licenses.bsd3;
    }
  ) { };

  heapsize = callPackage (
    {
      mkDerivation,
      base,
      criterion,
      deepseq,
      exceptions,
      ghc-heap,
      hashable,
      hashtables,
      primitive,
      transformers,
      unordered-containers,
    }:
    mkDerivation {
      pname = "heapsize";
      version = "0.3.0.1";
      sha256 = "0v38czcdnrlpcszbz7janb2qw4bqldhmql0riqq6a9bylv3zfs0y";
      libraryHaskellDepends = [
        base
        deepseq
        exceptions
        ghc-heap
        hashable
        hashtables
        primitive
        transformers
        unordered-containers
      ];
      benchmarkHaskellDepends = [
        base
        criterion
        deepseq
        primitive
      ];
      description = "Determine the size of runtime data structures";
      license = lib.licenses.bsd3;
    }
  ) { };

  heapsort = callPackage (
    {
      mkDerivation,
      array,
      base,
    }:
    mkDerivation {
      pname = "heapsort";
      version = "0.1.0";
      sha256 = "0fzws9fjhqsygsbwj7nvj786j16264vqvqzc97dr73y72538k9qa";
      isLibrary = true;
      isExecutable = true;
      executableHaskellDepends = [
        array
        base
      ];
      description = "Heapsort of MArrays as a demo of imperative programming";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "heapsort-example";
      broken = true;
    }
  ) { };

}
