# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hecc = callPackage (
    {
      mkDerivation,
      base,
      cereal,
      crypto-api,
      hF2,
    }:
    mkDerivation {
      pname = "hecc";
      version = "0.4.1.1";
      sha256 = "1p7h9mlap8i0w2inhq944r0dgr27rzwk44igylil7gv0dgf4hsyx";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        cereal
        crypto-api
        hF2
      ];
      description = "Elliptic Curve Cryptography for Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
