# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  HGraphStorage = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      Cabal,
      containers,
      criterion,
      data-default,
      directory,
      filepath,
      HUnit,
      lifted-base,
      monad-control,
      monad-logger,
      QuickCheck,
      resourcet,
      tar,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      text,
      text-binary,
      transformers,
      transformers-base,
      zlib,
    }:
    mkDerivation {
      pname = "HGraphStorage";
      version = "0.0.3";
      sha256 = "1qbhzrw8sjxaz95b34w3w71dv79wlkmqjgvcsr79vxxfn4c83dfc";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
        data-default
        directory
        filepath
        lifted-base
        monad-control
        monad-logger
        resourcet
        text
        transformers
        transformers-base
      ];
      testHaskellDepends = [
        base
        bytestring
        containers
        data-default
        directory
        filepath
        HUnit
        lifted-base
        monad-control
        monad-logger
        QuickCheck
        resourcet
        tasty
        tasty-hunit
        tasty-quickcheck
        text
        transformers
        transformers-base
      ];
      benchmarkHaskellDepends = [
        base
        binary
        bytestring
        Cabal
        containers
        criterion
        data-default
        directory
        filepath
        monad-logger
        resourcet
        tar
        text
        text-binary
        transformers
        zlib
      ];
      description = "Graph database stored on disk";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  hgraph = callPackage (
    {
      mkDerivation,
      array,
      base,
      clock,
      containers,
      happy-dot,
      HUnit,
      linear,
      mtl,
      random,
      say,
      transformers,
    }:
    mkDerivation {
      pname = "hgraph";
      version = "1.10.0.0";
      sha256 = "0689z5dy5zifpqdvhfarc96l386zfin6xgpgxkgj92dc4ps6wb9h";
      libraryHaskellDepends = [
        array
        base
        containers
        happy-dot
        linear
        mtl
        random
        say
        transformers
      ];
      testHaskellDepends = [
        base
        containers
        HUnit
        transformers
      ];
      benchmarkHaskellDepends = [
        base
        clock
        containers
        random
        transformers
      ];
      description = "Tools for working on (di)graphs";
      license = lib.licenses.gpl3Only;
    }
  ) { };

}
