# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  himg = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      directory,
      gtk,
      HTTP,
      http-conduit,
      network,
      temporary,
    }:
    mkDerivation {
      pname = "himg";
      version = "0.1.0.0";
      sha256 = "09ya9966fn3ss7xxc1cd0izb5js35gwr2r1km881w4455sknl093";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        directory
        gtk
        HTTP
        http-conduit
        network
        temporary
      ];
      executableHaskellDepends = [
        base
        bytestring
        directory
        gtk
        HTTP
        http-conduit
        network
        temporary
      ];
      description = "Simple gtk2hs image viewer. Point it at an image and fire away.";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "himg";
      broken = true;
    }
  ) { };

}
