# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hinstaller = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      Cabal,
      directory,
      filepath,
      process,
      template-haskell,
    }:
    mkDerivation {
      pname = "hinstaller";
      version = "2008.2.16";
      sha256 = "1ldfqx98w7inpj76xyi0drh2lykfjfq9r34hlbcw7mv4bgxp4l8c";
      libraryHaskellDepends = [
        base
        bytestring
        Cabal
        directory
        filepath
        process
        template-haskell
      ];
      description = "Installer wrapper for Haskell applications";
      license = "LGPL";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
