# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hls = callPackage (
    {
      mkDerivation,
      base,
      containers,
      hcg-minus,
      hps,
    }:
    mkDerivation {
      pname = "hls";
      version = "0.15";
      sha256 = "0h32fyvnqkxx8c9vfpdjvnqaxkvr8b15myjavxmnm6kwh7v2796l";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        containers
        hcg-minus
        hps
      ];
      description = "Haskell Lindenmayer Systems";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
