# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hobbes = callPackage (
    {
      mkDerivation,
      base,
      filemanip,
      filepath,
      fsnotify,
      system-filepath,
      text,
    }:
    mkDerivation {
      pname = "hobbes";
      version = "0.2.2";
      sha256 = "1pri63d59q918jv1hdp2ib06m6lzw9a2b6bjyn86b2qrrx2512xd";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        filemanip
        filepath
        fsnotify
        system-filepath
        text
      ];
      description = "A small file watcher for OSX";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "hobbes";
      broken = true;
    }
  ) { };

  hobbits = callPackage (
    {
      mkDerivation,
      base,
      containers,
      deepseq,
      haskell-src-exts,
      haskell-src-meta,
      mtl,
      syb,
      tagged,
      template-haskell,
      th-expand-syns,
      transformers,
      vector,
    }:
    mkDerivation {
      pname = "hobbits";
      version = "1.3.1";
      sha256 = "0jpm65s2f0fz5ipppryy2k8qja2ijmfd56a65z5k0hsx4j93ipva";
      libraryHaskellDepends = [
        base
        containers
        deepseq
        haskell-src-exts
        haskell-src-meta
        mtl
        syb
        tagged
        template-haskell
        th-expand-syns
        transformers
        vector
      ];
      description = "A library for canonically representing terms with binding";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
