# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  holmes = callPackage (
    {
      mkDerivation,
      base,
      containers,
      hashable,
      hedgehog,
      hspec,
      logict,
      markdown-unlit,
      mtl,
      primitive,
      relude,
      split,
      tasty,
      tasty-discover,
      tasty-hedgehog,
      tasty-hspec,
      transformers,
      unordered-containers,
    }:
    mkDerivation {
      pname = "holmes";
      version = "0.3.2.0";
      sha256 = "1hrgdnlyqz8wjnqihp8gn3rhl1zfyd6p9yv4cjwsv876bgy17ql8";
      libraryHaskellDepends = [
        base
        containers
        hashable
        hedgehog
        logict
        mtl
        primitive
        transformers
        unordered-containers
      ];
      testHaskellDepends = [
        base
        containers
        hashable
        hedgehog
        hspec
        primitive
        relude
        split
        tasty
        tasty-discover
        tasty-hedgehog
        tasty-hspec
        transformers
        unordered-containers
      ];
      testToolDepends = [
        markdown-unlit
        tasty-discover
      ];
      description = "Tools and combinators for solving constraint problems";
      license = lib.meta.getLicenseFromSpdxId "MIT";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
