# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hoobuddy = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      Cabal,
      directory,
      filepath,
      hoogle,
      monad-loops,
      mtl,
      process,
      yaml,
    }:
    mkDerivation {
      pname = "hoobuddy";
      version = "0.1.0.1";
      sha256 = "0l1q6h0irfv3275jajvylajm2rhkfmvi1kpfan6n6z5adibh9and";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        aeson
        base
        bytestring
        Cabal
        directory
        filepath
        hoogle
        monad-loops
        mtl
        process
        yaml
      ];
      description = "Simple tool for fetching and merging hoogle data";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "hoobuddy";
      broken = true;
    }
  ) { };

}
