# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hoppy-docs = callPackage (
    {
      mkDerivation,
      base,
      haskell-src,
      hoppy-generator,
      hoppy-runtime,
    }:
    mkDerivation {
      pname = "hoppy-docs";
      version = "0.9.0";
      sha256 = "0fxj2w762zdl3lzknpglmlwm3dgxsaw8vrljm73fb3gcscj9flbc";
      libraryHaskellDepends = [
        base
        haskell-src
        hoppy-generator
        hoppy-runtime
      ];
      description = "C++ FFI generator - Documentation";
      license = lib.licenses.agpl3Only;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  hoppy-generator = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      directory,
      filepath,
      haskell-src,
      mtl,
      process,
      temporary,
      text,
    }:
    mkDerivation {
      pname = "hoppy-generator";
      version = "0.9.0";
      sha256 = "16pa8w05fa11xl7cv3gz36j5xk8rxsi341a1wgm513m0ghqxyaqw";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        directory
        filepath
        haskell-src
        mtl
        process
        temporary
        text
      ];
      description = "C++ FFI generator - Code generator";
      license = lib.licenses.agpl3Only;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  hoppy-runtime = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      containers,
      directory,
      filepath,
      hoppy-generator,
    }:
    mkDerivation {
      pname = "hoppy-runtime";
      version = "0.9.0";
      sha256 = "0ndabz5yb98d7xpjsgsvqvvaslvsg3pcmd1ms9n93lsx4xv4xkpx";
      libraryHaskellDepends = [
        base
        Cabal
        containers
        directory
        filepath
        hoppy-generator
      ];
      description = "C++ FFI generator - Runtime support";
      license = lib.licenses.asl20;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  hoppy-std = callPackage (
    {
      mkDerivation,
      base,
      filepath,
      haskell-src,
      hoppy-generator,
    }:
    mkDerivation {
      pname = "hoppy-std";
      version = "0.9.0";
      sha256 = "1vgpdkmy2pzfj2gl10pdc45i80d73vgi5mhcd82if1rgc4zvqjas";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        filepath
        haskell-src
        hoppy-generator
      ];
      description = "C++ FFI generator - Standard library bindings";
      license = lib.licenses.asl20;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
