# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hpage = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      Cabal,
      cabal-macosx,
      containers,
      directory,
      eprocess,
      filepath,
      FindBin,
      haskell-src-exts,
      hint,
      hint-server,
      monad-loops,
      mtl,
      process,
      time,
      wx,
      wxcore,
    }:
    mkDerivation {
      pname = "hpage";
      version = "0.12.2";
      sha256 = "0sl2qh3l5vbijln2al7vmvxm4zhn3qsz8axvprs6jxjfbndmk78j";
      isLibrary = false;
      isExecutable = true;
      enableSeparateDataOutput = true;
      executableHaskellDepends = [
        base
        bytestring
        Cabal
        cabal-macosx
        containers
        directory
        eprocess
        filepath
        FindBin
        haskell-src-exts
        hint
        hint-server
        monad-loops
        mtl
        process
        time
        wx
        wxcore
      ];
      description = "A scrapbook for Haskell developers";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "hpage";
    }
  ) { };

}
