# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hpg = callPackage (
    {
      mkDerivation,
      base,
      random,
    }:
    mkDerivation {
      pname = "hpg";
      version = "0.8";
      sha256 = "1in245bwnymzxp1bzvzkmfwxs2pxnhw94c9j8z9v3vxvz7g0fygs";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        random
      ];
      description = "a simple password generator";
      license = lib.licenses.isc;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "hpg";
      broken = true;
    }
  ) { };

}
