# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hpio = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      containers,
      directory,
      doctest,
      exceptions,
      filepath,
      hspec,
      monad-control,
      monad-logger,
      mtl,
      optparse-applicative,
      protolude,
      QuickCheck,
      text,
      transformers,
      transformers-base,
      unix,
      unix-bytestring,
    }:
    mkDerivation {
      pname = "hpio";
      version = "0.9.0.7";
      sha256 = "1l08b668bl9gwbrzkhljg73aizv640gcc7smiafhgrnk2bsl7q2p";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        containers
        directory
        exceptions
        filepath
        monad-control
        monad-logger
        mtl
        protolude
        QuickCheck
        text
        transformers
        transformers-base
        unix
        unix-bytestring
      ];
      executableHaskellDepends = [
        async
        base
        exceptions
        mtl
        optparse-applicative
        protolude
        text
        transformers
      ];
      testHaskellDepends = [
        base
        containers
        directory
        doctest
        exceptions
        filepath
        hspec
        protolude
        QuickCheck
      ];
      description = "Monads for GPIO in Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
