# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hranker = callPackage (
    {
      mkDerivation,
      base,
      HCL,
      NonEmpty,
    }:
    mkDerivation {
      pname = "hranker";
      version = "0.1.1";
      sha256 = "0hg2qjjr5pcnx62382r3d3rqvb3z7h1926lpym68869n4s19wz7d";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        HCL
        NonEmpty
      ];
      description = "Basic utility for ranking a list of items";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "hranker";
    }
  ) { };

}
