# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hrfsize = callPackage (
    {
      mkDerivation,
      base,
      process,
      tasty,
      tasty-hunit,
    }:
    mkDerivation {
      pname = "hrfsize";
      version = "0.0.2";
      sha256 = "1vffw7r3lx80ny2v19ykfj76xswqpsijp1mri4kmd4jnlv5z2nin";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        process
        tasty
        tasty-hunit
      ];
      description = "File size in human readable format";
      license = lib.licenses.bsd3;
    }
  ) { };

}
