# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  hsbencher = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      containers,
      data-default,
      directory,
      filepath,
      GenericPretty,
      HUnit,
      io-streams,
      mtl,
      process,
      random,
      test-framework,
      test-framework-hunit,
      text,
      time,
      unix,
    }:
    mkDerivation {
      pname = "hsbencher";
      version = "1.20.0.5";
      sha256 = "1fqp0n106dnqik3p6fa60xkamls8wgg8c5sp2klgp36n3xflvy9h";
      libraryHaskellDepends = [
        async
        base
        bytestring
        containers
        data-default
        directory
        filepath
        GenericPretty
        io-streams
        mtl
        process
        random
        time
        unix
      ];
      testHaskellDepends = [
        base
        bytestring
        containers
        directory
        HUnit
        test-framework
        test-framework-hunit
        text
        time
      ];
      description = "Launch and gather data from Haskell and non-Haskell benchmarks";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  hsbencher-codespeed = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      data-default,
      directory,
      filepath,
      hsbencher,
      HTTP,
      http-conduit,
      http-types,
      json,
      mtl,
      network,
      resourcet,
      time,
    }:
    mkDerivation {
      pname = "hsbencher-codespeed";
      version = "0.1.0.1";
      sha256 = "1a3hac73mzd0q25b1xbdh121k33m12phpxfn6hh7qcg5yys2i8l5";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        data-default
        directory
        filepath
        hsbencher
        HTTP
        http-conduit
        http-types
        json
        mtl
        network
        resourcet
        time
      ];
      description = "Backend for uploading benchmark data to CodeSpeed";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  hsbencher-fusion = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      criterion,
      csv,
      data-default,
      directory,
      filepath,
      handa-gdata,
      hsbencher,
      http-conduit,
      mtl,
      network,
      split,
      statistics,
      text,
      time,
    }:
    mkDerivation {
      pname = "hsbencher-fusion";
      version = "0.3.15.2";
      sha256 = "0xp2jm5zvrx5sz2mniachd7hjmhmf0sv9as3dzln8693n6l1ak4r";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        containers
        data-default
        directory
        filepath
        handa-gdata
        hsbencher
        http-conduit
        mtl
        network
        time
      ];
      executableHaskellDepends = [
        base
        bytestring
        containers
        criterion
        csv
        handa-gdata
        hsbencher
        mtl
        split
        statistics
        text
      ];
      description = "Backend for uploading benchmark data to Google Fusion Tables";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
