# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  HsHaruPDF = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "HsHaruPDF";
      version = "0.0.0";
      sha256 = "1yifhxk1m3z2i7gaxgwlmk6cv2spbpx8fny4sn59ybca8wd9z7ps";
      libraryHaskellDepends = [ base ];
      description = "Haskell binding to libharu (http://libharu.sourceforge.net/)";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  hsharc = callPackage (
    {
      mkDerivation,
      base,
      xml,
    }:
    mkDerivation {
      pname = "hsharc";
      version = "0.14";
      sha256 = "1mzi074iiz48pcy6rvgqz6ckm0zx115kmvax60bx9bfcanw686vf";
      libraryHaskellDepends = [
        base
        xml
      ];
      description = "Haskell SHARC bindings";
      license = "GPL";
    }
  ) { };

}
