# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Hungarian-Munkres = callPackage (
    {
      mkDerivation,
      array,
      base,
      criterion,
      Munkres,
      random,
      tasty,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "Hungarian-Munkres";
      version = "0.1.5";
      sha256 = "0g2hgcrsfwqp4w3mzg6vwi7lypgqd0b6axaff81wbi27h9n8q4qd";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        array
        base
        Munkres
        random
        tasty
        tasty-quickcheck
      ];
      benchmarkHaskellDepends = [
        array
        base
        criterion
        Munkres
        random
      ];
      description = "A Linear Sum Assignment Problem (LSAP) solver";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
