# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  idiii = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      data-accessor,
      directory,
      filepath,
      HUnit,
      MissingH,
      polyparse,
      process,
      text,
      utf8-string,
    }:
    mkDerivation {
      pname = "idiii";
      version = "0.1.3.3";
      sha256 = "11595aj56sjwk28grh6ldsbk5c6kgrirsc2xglfixw82vj7viw8h";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        bytestring
        containers
        data-accessor
        MissingH
        polyparse
        text
        utf8-string
      ];
      executableHaskellDepends = [
        base
        containers
      ];
      testHaskellDepends = [
        base
        bytestring
        containers
        data-accessor
        directory
        filepath
        HUnit
        MissingH
        polyparse
        process
        text
        utf8-string
      ];
      description = "ID3v2 (tagging standard for MP3 files) library";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "read-idiii";
      broken = true;
    }
  ) { };

}
