# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  ignore = callPackage (
    {
      mkDerivation,
      base,
      directory,
      Glob,
      HTF,
      mtl,
      path,
      pcre-heavy,
      text,
    }:
    mkDerivation {
      pname = "ignore";
      version = "0.1.1.0";
      sha256 = "0x9mqx198ssj742cv8w643w2cxv9avgyl9j7dr85mp4bmgyq3x5a";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        directory
        Glob
        mtl
        path
        pcre-heavy
        text
      ];
      executableHaskellDepends = [
        base
        directory
        path
      ];
      testHaskellDepends = [
        base
        HTF
        text
      ];
      description = "Handle ignore files of different VCSes";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "ignore";
      broken = true;
    }
  ) { };

}
