# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  INblobs = callPackage (
    {
      mkDerivation,
      base,
      containers,
      directory,
      haskell98,
      HaXml,
      polyparse,
      pretty,
      process,
      wx,
      wxcore,
    }:
    mkDerivation {
      pname = "INblobs";
      version = "0.1.1";
      sha256 = "04il63xafq20jn3m4hahn93xxfrp6whrjvsz974zczxqm41ygb10";
      isLibrary = false;
      isExecutable = true;
      enableSeparateDataOutput = true;
      executableHaskellDepends = [
        base
        containers
        directory
        haskell98
        HaXml
        polyparse
        pretty
        process
        wx
        wxcore
      ];
      description = "Editor and interpreter for Interaction Nets";
      license = "LGPL";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "INblobs";
    }
  ) { };

}
