# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  ini-qq = callPackage (
    {
      mkDerivation,
      base,
      HUnit,
      ini,
      raw-strings-qq,
      template-haskell,
      text,
    }:
    mkDerivation {
      pname = "ini-qq";
      version = "0.1.0.0";
      sha256 = "1szsx2jdq4qqjrj4z5xvwzx35j6apf7i1p4iqbiy0z9hyfh9splc";
      libraryHaskellDepends = [
        base
        ini
        template-haskell
        text
      ];
      testHaskellDepends = [
        base
        HUnit
        ini
        raw-strings-qq
        text
      ];
      description = "Quasiquoter for INI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
