# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  iwlib = callPackage (
    {
      mkDerivation,
      base,
      wirelesstools,
    }:
    mkDerivation {
      pname = "iwlib";
      version = "0.1.2";
      sha256 = "0iyibjiviqkh79bifnpnzs2cl8790hhbhh8wp10l8nl7wbwzppzx";
      libraryHaskellDepends = [ base ];
      librarySystemDepends = [ wirelesstools ];
      description = "Bindings for the iw C library";
      license = lib.licenses.bsd3;
      badPlatforms = lib.platforms.darwin;
    }
  ) { inherit (pkgs) wirelesstools; };

}
