# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Jdh = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "Jdh";
      version = "0.1.0.1";
      sha256 = "0zg7xh3apm7x3c9gz876k5cis5jpng1bzf6g9ywbmmndry6dn1c0";
      libraryHaskellDepends = [ base ];
      description = "A Json implementation for Haskell, with JavaScript Values and Encoding/Decoding";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
