# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  jsc = callPackage (
    {
      mkDerivation,
      base,
      jmacro,
      lens,
      template-haskell,
      text,
      transformers,
      webkitgtk3,
      webkitgtk3-javascriptcore,
    }:
    mkDerivation {
      pname = "jsc";
      version = "0.1.1.1";
      sha256 = "18mvpncvsfv4gv7lx00g8aixjmhzp0yklxaajx45v2hsx0azn8zc";
      libraryHaskellDepends = [
        base
        jmacro
        lens
        template-haskell
        text
        transformers
        webkitgtk3
        webkitgtk3-javascriptcore
      ];
      description = "High level interface for webkit-javascriptcore";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
