# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  kdl-hs = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      containers,
      data-default,
      directory,
      filepath,
      megaparsec,
      pretty-show,
      prettyprinter,
      process,
      scientific,
      skeletest,
      temporary,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "kdl-hs";
      version = "1.0.1";
      sha256 = "1z2y85avj0npgdin46pagyjdnh34sixf5vjasxphkcgshbw4pa8x";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
        data-default
        megaparsec
        prettyprinter
        scientific
        text
        transformers
      ];
      executableHaskellDepends = [
        aeson
        base
        bytestring
        containers
        scientific
        text
      ];
      testHaskellDepends = [
        base
        containers
        directory
        filepath
        pretty-show
        process
        scientific
        skeletest
        temporary
        text
      ];
      testToolDepends = [ skeletest ];
      description = "KDL language parser and API";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      mainProgram = "kdl-hs-test-decoder";
    }
  ) { };

}
