# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  keep-alive = callPackage (
    {
      mkDerivation,
      base,
      network,
    }:
    mkDerivation {
      pname = "keep-alive";
      version = "0.2.1.0";
      sha256 = "1sbkn9rkj8rv5gn2a4s46rfmxr46ya7l8bqbdp8p3xga79d42pyh";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        network
      ];
      description = "TCP keep alive implementation";
      license = lib.licenses.bsd3;
    }
  ) { };

}
