# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  KyotoCabinet = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      extensible-exceptions,
      kyotocabinet,
    }:
    mkDerivation {
      pname = "KyotoCabinet";
      version = "0.1";
      sha256 = "1l7cpppjfz5nd8k67ss959g8sg5kbsfl4zy80a3yrlwbivyrg58n";
      libraryHaskellDepends = [
        base
        bytestring
        extensible-exceptions
      ];
      librarySystemDepends = [ kyotocabinet ];
      description = "Kyoto Cabinet DB bindings";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { inherit (pkgs) kyotocabinet; };

  kyotocabinet = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      kyotocabinet,
    }:
    mkDerivation {
      pname = "kyotocabinet";
      version = "0.1.4";
      sha256 = "0wvrmykl1fi135hmsgclyzwhpq5bxy9wqb4s4lp0vd0bghyr9w83";
      libraryHaskellDepends = [
        base
        bytestring
        cereal
      ];
      librarySystemDepends = [ kyotocabinet ];
      description = "Mid level bindings to Kyoto Cabinet";
      license = lib.licenses.bsd3;
    }
  ) { inherit (pkgs) kyotocabinet; };

}
