# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  LargeCardinalHierarchy = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "LargeCardinalHierarchy";
      version = "0.0.1";
      sha256 = "0agq2593h5yb9r3jqnycis9fdizwij3and61ljc4prnhhyxv48g2";
      libraryHaskellDepends = [ base ];
      description = "A transfinite cardinal arithmetic library including all known large cardinals";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  large-anon = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-pretty,
      arrows,
      base,
      bytestring,
      containers,
      deepseq,
      ghc,
      ghc-tcplugin-api,
      hashable,
      large-generics,
      mtl,
      optics-core,
      parsec,
      primitive,
      QuickCheck,
      record-hasfield,
      sop-core,
      Stream,
      syb,
      tagged,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      text,
      typelet,
      validation-selective,
    }:
    mkDerivation {
      pname = "large-anon";
      version = "0.3.3";
      sha256 = "1xwl72d217i10va21cf61nfjvw85zdajhff57qhpbf15my187a3h";
      revision = "1";
      editedCabalFile = "0lqv9f4hq8f1cfgg763inqi05pc7kr08qdkmhrsmrqz24xan9wir";
      libraryHaskellDepends = [
        aeson
        base
        containers
        deepseq
        ghc
        ghc-tcplugin-api
        hashable
        large-generics
        mtl
        optics-core
        primitive
        record-hasfield
        sop-core
        syb
        tagged
        typelet
      ];
      testHaskellDepends = [
        aeson
        aeson-pretty
        arrows
        base
        bytestring
        containers
        large-generics
        mtl
        optics-core
        parsec
        QuickCheck
        record-hasfield
        sop-core
        Stream
        tasty
        tasty-hunit
        tasty-quickcheck
        text
        typelet
        validation-selective
      ];
      description = "Scalable anonymous records";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  large-generics = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      deepseq,
      generic-deriving,
      generics-sop,
      microlens,
      mtl,
      primitive,
      QuickCheck,
      sop-core,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "large-generics";
      version = "0.2.3";
      sha256 = "0sxgw2aajh79sm9pd66i7ml7z9k7vs38aarpf39yh98bppci6sgk";
      libraryHaskellDepends = [
        aeson
        base
        deepseq
        generics-sop
        primitive
        sop-core
      ];
      testHaskellDepends = [
        aeson
        base
        generic-deriving
        generics-sop
        microlens
        mtl
        QuickCheck
        sop-core
        tasty
        tasty-hunit
        tasty-quickcheck
      ];
      description = "Generic programming API for large-records and large-anon";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      maintainers = [ lib.maintainers.alexfmpe ];
    }
  ) { };

  large-hashable = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      base16-bytestring,
      byteable,
      bytes,
      bytestring,
      cereal,
      containers,
      cpphs,
      criterion,
      cryptohash,
      crypton,
      deepseq,
      hashable,
      HTF,
      inspection-testing,
      memory,
      QuickCheck,
      safecopy,
      scientific,
      strict,
      template-haskell,
      text,
      time,
      transformers,
      unordered-containers,
      vector,
      void,
    }:
    mkDerivation {
      pname = "large-hashable";
      version = "0.1.2.0";
      sha256 = "0nz3rgjch9qy662fgg3iyln3w8yz7i5vxzw6b00sddakmqnl5ypz";
      libraryHaskellDepends = [
        aeson
        base
        base16-bytestring
        bytes
        bytestring
        containers
        crypton
        memory
        scientific
        strict
        template-haskell
        text
        time
        transformers
        unordered-containers
        vector
        void
      ];
      libraryToolDepends = [ cpphs ];
      testHaskellDepends = [
        aeson
        base
        bytes
        bytestring
        containers
        hashable
        HTF
        inspection-testing
        QuickCheck
        scientific
        strict
        text
        time
        unordered-containers
        vector
      ];
      testToolDepends = [ cpphs ];
      benchmarkHaskellDepends = [
        base
        base16-bytestring
        byteable
        bytes
        bytestring
        cereal
        criterion
        cryptohash
        deepseq
        safecopy
        text
        transformers
      ];
      benchmarkToolDepends = [ cpphs ];
      description = "Efficiently hash (large) Haskell values";
      license = lib.licenses.bsd3;
      maintainers = [ lib.maintainers.sternenseemann ];
    }
  ) { };

  large-records = callPackage (
    {
      mkDerivation,
      base,
      containers,
      generic-deriving,
      ghc,
      ghc-internal,
      large-generics,
      mtl,
      newtype,
      optics-core,
      optics-th,
      primitive,
      record-hasfield,
      syb,
      tasty,
      tasty-hunit,
      template-haskell,
      transformers,
    }:
    mkDerivation {
      pname = "large-records";
      version = "0.4.4";
      sha256 = "15mk1n86y6lx7ycjraz4lzwqn7rb52qikmgwqd68sq9znfq802rj";
      libraryHaskellDepends = [
        base
        containers
        ghc
        large-generics
        mtl
        optics-core
        primitive
        record-hasfield
        syb
        template-haskell
        transformers
      ];
      testHaskellDepends = [
        base
        generic-deriving
        ghc-internal
        large-generics
        mtl
        newtype
        optics-core
        optics-th
        record-hasfield
        tasty
        tasty-hunit
        template-haskell
        transformers
      ];
      description = "Efficient compilation for large records, linear in the size of the record";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      maintainers = [ lib.maintainers.alexfmpe ];
    }
  ) { };

  largeword = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      HUnit,
      QuickCheck,
      test-framework,
      test-framework-hunit,
      test-framework-quickcheck2,
    }:
    mkDerivation {
      pname = "largeword";
      version = "1.2.5";
      sha256 = "0ikxklg4w30hyfcnrq8hr348p8s9hg42b9sj9x0byjb6hinv1cq0";
      libraryHaskellDepends = [
        base
        binary
      ];
      testHaskellDepends = [
        base
        binary
        bytestring
        HUnit
        QuickCheck
        test-framework
        test-framework-hunit
        test-framework-quickcheck2
      ];
      description = "Provides Word128, Word192 and Word256 and a way of producing other large words if required";
      license = lib.licenses.bsd3;
    }
  ) { };

}
