# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  LDAP = callPackage (
    {
      mkDerivation,
      base,
      HUnit,
      openldap,
    }:
    mkDerivation {
      pname = "LDAP";
      version = "0.6.11";
      sha256 = "1cwh3272zi5r0zznmixghf87vskz7s35bmz6ifyky0xk3s04ijq1";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [ base ];
      librarySystemDepends = [ openldap ];
      testHaskellDepends = [
        base
        HUnit
      ];
      testSystemDepends = [ openldap ];
      description = "Haskell binding for C LDAP API";
      license = lib.licenses.bsd3;
    }
  ) { inherit (pkgs) openldap; };

  LDAPv3 = callPackage (
    {
      mkDerivation,
      base,
      base-encoding,
      binary,
      bytestring,
      containers,
      deepseq,
      int-cast,
      newtype,
      parsec,
      quickcheck-instances,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      text,
      text-short,
    }:
    mkDerivation {
      pname = "LDAPv3";
      version = "0.1.2.0";
      sha256 = "09x8s9yh821lcc60sxifcy2pbzghnp9aw0vk6mcnrj0lb741f6f4";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
        deepseq
        int-cast
        newtype
        parsec
        text
        text-short
      ];
      testHaskellDepends = [
        base
        base-encoding
        binary
        bytestring
        containers
        deepseq
        int-cast
        newtype
        parsec
        quickcheck-instances
        tasty
        tasty-hunit
        tasty-quickcheck
        text
        text-short
      ];
      description = "Lightweight Directory Access Protocol (LDAP) version 3";
      license = lib.meta.getLicenseFromSpdxId "GPL-2.0-or-later";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  ldap-client = callPackage (
    {
      mkDerivation,
      asn1-encoding,
      asn1-types,
      async,
      base,
      bytestring,
      containers,
      crypton-connection,
      fail,
      hspec,
      network,
      process,
      semigroups,
      stm,
      text,
    }:
    mkDerivation {
      pname = "ldap-client";
      version = "0.4.3";
      sha256 = "15cid7mnfn6ykh4vhhqbs652sng12430ccdabf6kcc0236ghicrd";
      libraryHaskellDepends = [
        asn1-encoding
        asn1-types
        async
        base
        bytestring
        containers
        crypton-connection
        fail
        network
        semigroups
        stm
        text
      ];
      testHaskellDepends = [
        base
        bytestring
        hspec
        process
        semigroups
      ];
      description = "Pure Haskell LDAP Client Library";
      license = lib.licenses.bsd2;
    }
  ) { };

  ldap-client-og = callPackage (
    {
      mkDerivation,
      asn1-encoding,
      asn1-types,
      async,
      base,
      bytestring,
      containers,
      crypton-connection,
      data-default,
      hspec,
      hspec-discover,
      network,
      process,
      semigroups,
      stm,
      text,
      tls,
    }:
    mkDerivation {
      pname = "ldap-client-og";
      version = "0.5.0";
      sha256 = "023wsfcl8vy2viwr4447s5yd27rr42l0v54xxdxzl4bx09zkp87l";
      libraryHaskellDepends = [
        asn1-encoding
        asn1-types
        async
        base
        bytestring
        containers
        crypton-connection
        data-default
        network
        semigroups
        stm
        text
        tls
      ];
      testHaskellDepends = [
        base
        bytestring
        hspec
        process
        semigroups
      ];
      testToolDepends = [ hspec-discover ];
      description = "Pure Haskell LDAP Client Library";
      license = lib.licenses.bsd2;
    }
  ) { };

  ldap-scim-bridge = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-pretty,
      base,
      bytestring,
      containers,
      email-validate,
      hscim,
      hspec,
      http-client,
      http-client-tls,
      http-types,
      ldap-client,
      network,
      QuickCheck,
      relude,
      servant,
      servant-client,
      servant-client-core,
      string-conversions,
      text,
      tinylog,
      unordered-containers,
      yaml,
    }:
    mkDerivation {
      pname = "ldap-scim-bridge";
      version = "0.10";
      sha256 = "0pn3qp2p7w40wdagkwzq23i5dcimrsca1xwxh8jgffqr7zdym57v";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        aeson-pretty
        base
        bytestring
        containers
        email-validate
        hscim
        http-client
        http-client-tls
        http-types
        ldap-client
        network
        relude
        servant
        servant-client
        servant-client-core
        string-conversions
        text
        tinylog
        unordered-containers
        yaml
      ];
      executableHaskellDepends = [
        aeson
        aeson-pretty
        base
        bytestring
        containers
        email-validate
        hscim
        http-client
        http-client-tls
        http-types
        ldap-client
        network
        relude
        servant
        servant-client
        servant-client-core
        string-conversions
        text
        tinylog
        unordered-containers
        yaml
      ];
      testHaskellDepends = [
        base
        bytestring
        email-validate
        hscim
        hspec
        ldap-client
        QuickCheck
        string-conversions
        text
        yaml
      ];
      description = "See README for synopsis";
      license = lib.meta.getLicenseFromSpdxId "AGPL-3.0-or-later";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "ldap-scim-bridge";
    }
  ) { };

  ldapply = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      docopt,
      interpolatedstring-perl6,
      LDAP,
      ldif,
      unordered-containers,
    }:
    mkDerivation {
      pname = "ldapply";
      version = "0.2.0";
      sha256 = "0qgpb22k9krdhwjydzyfhjf85crxc49ss7x74mrqj8ivkzg5hl28";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        bytestring
        docopt
        interpolatedstring-perl6
        LDAP
        ldif
        unordered-containers
      ];
      description = "LDIF idempotent apply tool";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "ldapply";
    }
  ) { };

}
