# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  linode = callPackage (
    {
      mkDerivation,
      aeson,
      async,
      base,
      binary,
      bytestring,
      containers,
      errors,
      lens,
      process,
      retry,
      safe,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      text,
      transformers,
      wreq,
    }:
    mkDerivation {
      pname = "linode";
      version = "0.3.0.0";
      sha256 = "17hk0k9d91wi28h5k90dng0b64bhl9scbj20pmvqbk8rin9kap3w";
      libraryHaskellDepends = [
        aeson
        async
        base
        binary
        bytestring
        containers
        errors
        lens
        process
        retry
        safe
        text
        transformers
        wreq
      ];
      testHaskellDepends = [
        aeson
        base
        bytestring
        containers
        tasty
        tasty-hunit
        tasty-quickcheck
        text
      ];
      description = "Bindings to the Linode API";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  linode-v4 = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      hspec,
      http-conduit,
      unordered-containers,
    }:
    mkDerivation {
      pname = "linode-v4";
      version = "0.1.0.4";
      sha256 = "1qc6nm9845m9vgzdm0fbsrw4924cpcvcgzqxzbikml0lc1284g7r";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        http-conduit
        unordered-containers
      ];
      testHaskellDepends = [
        base
        hspec
      ];
      description = "Haskell wrapper for the Linode v4 API";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
