# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  loris = callPackage (
    {
      mkDerivation,
      base,
      c2hs,
      loris,
      vector,
    }:
    mkDerivation {
      pname = "loris";
      version = "0.3.1";
      sha256 = "19w1c3gsmy03y4a238yp844wgqcv9s53cwrcapv2yvn9xpchm2gq";
      libraryHaskellDepends = [
        base
        vector
      ];
      librarySystemDepends = [ loris ];
      libraryToolDepends = [ c2hs ];
      description = "interface to Loris API";
      license = lib.licenses.gpl2Only;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { loris = null; };

}
