# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  mac = callPackage (
    {
      mkDerivation,
      base,
      network,
      transformers,
    }:
    mkDerivation {
      pname = "mac";
      version = "0.1.3.0";
      sha256 = "0zhjpszj8qm1kqx2q7g9a41crbmqvqis7qlx65a1l36ywk78gnyd";
      revision = "1";
      editedCabalFile = "0p0yrv75zpn127vcn3inhsma1kf7zq7b1c33fsvywm4jba700cnx";
      libraryHaskellDepends = [
        base
        network
        transformers
      ];
      description = "Static Mandatory Access Control in Haskell";
      license = lib.licenses.bsd3;
    }
  ) { };

}
