# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  mprover = callPackage (
    {
      mkDerivation,
      base,
      containers,
      haskell98,
      mtl,
      parsec,
      pretty,
      transformers,
      unbound,
    }:
    mkDerivation {
      pname = "mprover";
      version = "0.0.0.0";
      sha256 = "1b5vzhbn5jnpxc0bzbhdak51qhzv5hif0300jsrbi5ffyvcjqkss";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        containers
        haskell98
        mtl
        parsec
        pretty
        transformers
        unbound
      ];
      description = "Simple equational reasoning for a Haskell-ish language";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "mp";
    }
  ) { };

}
