# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  mssql-simple = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      hostname,
      ms-tds,
      mtl,
      network,
      template-haskell,
      text,
      time,
      tls,
      transformers,
      uuid-types,
    }:
    mkDerivation {
      pname = "mssql-simple";
      version = "0.6.0.5";
      sha256 = "0d1cj0qfrnqqr12i976d3ynk4yg45fys38xcnixvz8wz20kv00mn";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        hostname
        ms-tds
        mtl
        network
        template-haskell
        text
        time
        tls
        transformers
        uuid-types
      ];
      testHaskellDepends = [
        base
        binary
        bytestring
        hostname
        ms-tds
        mtl
        network
        template-haskell
        text
        time
        tls
        transformers
        uuid-types
      ];
      description = "SQL Server client library implemented in Haskell";
      license = lib.licenses.bsd3;
    }
  ) { };

}
