# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  NoSlow = callPackage (
    {
      mkDerivation,
      array,
      base,
      containers,
      criterion,
      dph-base,
      dph-prim-seq,
      statistics,
      storablevector,
      template-haskell,
      uvector,
      vector,
    }:
    mkDerivation {
      pname = "NoSlow";
      version = "0.2";
      sha256 = "1pr1v8xxnhd7yxbhjqhlkwlsfzbk425bmxn99d80w8p4biag104x";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        array
        base
        containers
        criterion
        dph-base
        dph-prim-seq
        statistics
        storablevector
        template-haskell
        uvector
        vector
      ];
      description = "Microbenchmarks for various array libraries";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
