# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  nqe = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      conduit,
      conduit-extra,
      containers,
      exceptions,
      hashable,
      hspec,
      mtl,
      stm,
      stm-conduit,
      text,
      unique,
      unliftio,
    }:
    mkDerivation {
      pname = "nqe";
      version = "0.6.6";
      sha256 = "192w1l3i3cnmxxv2zq02ky31q4vsk6cy5bxih8767gfccn9kgkgi";
      libraryHaskellDepends = [
        base
        conduit
        containers
        hashable
        mtl
        stm
        unique
        unliftio
      ];
      testHaskellDepends = [
        async
        base
        bytestring
        conduit
        conduit-extra
        exceptions
        hspec
        stm
        stm-conduit
        text
        unliftio
      ];
      description = "Concurrency library in the style of Erlang/OTP";
      license = lib.licenses.mit;
    }
  ) { };

}
