# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  oanda-rest-api = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      conduit,
      containers,
      Decimal,
      hlint,
      hspec,
      http-client,
      http-conduit,
      HUnit,
      lens,
      old-locale,
      resourcet,
      scientific,
      text,
      thyme,
      transformers,
      vector,
    }:
    mkDerivation {
      pname = "oanda-rest-api";
      version = "0.4.1";
      sha256 = "1r20vn0hbx1xca5jaq9djfhgrxgdyhj1m4i9708wd972h2h7q2vr";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        conduit
        containers
        Decimal
        http-client
        http-conduit
        lens
        old-locale
        resourcet
        scientific
        text
        thyme
        transformers
        vector
      ];
      testHaskellDepends = [
        aeson
        base
        bytestring
        conduit
        containers
        Decimal
        hlint
        hspec
        http-client
        http-conduit
        HUnit
        lens
        old-locale
        resourcet
        scientific
        text
        thyme
        transformers
        vector
      ];
      description = "Client to the OANDA REST API";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
