# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  online = callPackage (
    {
      mkDerivation,
      adjunctions,
      backprop,
      base,
      containers,
      doctest,
      foldl,
      folds,
      generic-lens,
      hmatrix,
      lens,
      mwc-probability,
      mwc-random,
      numhask,
      numhask-array,
      primitive,
      profunctors,
      tdigest,
      text,
      vector,
      vector-algorithms,
    }:
    mkDerivation {
      pname = "online";
      version = "0.6.0";
      sha256 = "1yr3jq4gpjmgfd9q95n3b0g9ib2xjccc56m8mxlzsjxhnqc149jy";
      libraryHaskellDepends = [
        adjunctions
        backprop
        base
        containers
        foldl
        folds
        generic-lens
        hmatrix
        lens
        mwc-probability
        mwc-random
        numhask
        numhask-array
        primitive
        profunctors
        tdigest
        text
        vector
        vector-algorithms
      ];
      testHaskellDepends = [
        base
        doctest
        numhask
      ];
      description = "See readme.md";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  online-csv = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      box,
      doctest,
      foldl,
      generic-lens,
      lens,
      numhask-prelude,
      scientific,
      text,
      text-format,
    }:
    mkDerivation {
      pname = "online-csv";
      version = "0.0.1";
      sha256 = "0fibv9k9py6mszjnj501cak4jhdz6iyy6qp56cp1vvsbkv44m8ll";
      libraryHaskellDepends = [
        attoparsec
        base
        box
        foldl
        generic-lens
        lens
        numhask-prelude
        scientific
        text
        text-format
      ];
      testHaskellDepends = [
        base
        doctest
        numhask-prelude
      ];
      description = "See readme.md";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
