# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  overeasy = callPackage (
    {
      mkDerivation,
      algebraic-graphs,
      base,
      containers,
      deepseq,
      hashable,
      hedgehog,
      int-like,
      logict,
      mtl,
      prop-unit,
      recursion-schemes,
      text,
      transformers,
      unfree,
      unordered-containers,
    }:
    mkDerivation {
      pname = "overeasy";
      version = "0.2.0";
      sha256 = "1yyh79l9fjb1r769wm878ldi4g81i3iqmjwng02frs9c2fzbsp3w";
      libraryHaskellDepends = [
        algebraic-graphs
        base
        containers
        deepseq
        hashable
        int-like
        logict
        mtl
        recursion-schemes
        text
        transformers
        unfree
        unordered-containers
      ];
      testHaskellDepends = [
        algebraic-graphs
        base
        containers
        deepseq
        hashable
        hedgehog
        int-like
        logict
        mtl
        prop-unit
        recursion-schemes
        text
        transformers
        unfree
        unordered-containers
      ];
      description = "A purely functional E-Graph library";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  overhang = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "overhang";
      version = "1.0.0";
      sha256 = "07iafybg45130jhwin6jj2fnkgcwra367f5df91xn34kaj9zas0x";
      libraryHaskellDepends = [ base ];
      description = "Hang loose with your lambdas!";
      license = lib.licenses.mit;
    }
  ) { };

  overload = callPackage (
    {
      mkDerivation,
      base,
      simple-effects,
      template-haskell,
      th-expand-syns,
    }:
    mkDerivation {
      pname = "overload";
      version = "0.1.0.5";
      sha256 = "046lxmcrk072l08rxbbzb883gd7cffxx76l3x29h78d10aai6cac";
      libraryHaskellDepends = [
        base
        simple-effects
        template-haskell
        th-expand-syns
      ];
      description = "Finite overloading";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  overloaded = callPackage (
    {
      mkDerivation,
      assoc,
      base,
      bin,
      boring,
      bytestring,
      constraints,
      containers,
      fin,
      generic-lens-lite,
      ghc,
      HUnit,
      indexed-traversable,
      lens,
      optics-core,
      profunctors,
      QuickCheck,
      ral,
      record-hasfield,
      semigroupoids,
      singleton-bool,
      sop-core,
      split,
      syb,
      symbols,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      template-haskell,
      text,
      th-compat,
      time,
      vec,
    }:
    mkDerivation {
      pname = "overloaded";
      version = "0.3.1";
      sha256 = "0ra33rcbjm58978gc0pjzcspyvab7g2vxnjk6z5hag7qh6ay76bg";
      libraryHaskellDepends = [
        assoc
        base
        bin
        bytestring
        containers
        fin
        ghc
        indexed-traversable
        optics-core
        profunctors
        ral
        record-hasfield
        semigroupoids
        sop-core
        split
        syb
        symbols
        template-haskell
        text
        th-compat
        time
        vec
      ];
      testHaskellDepends = [
        assoc
        base
        bin
        boring
        bytestring
        constraints
        containers
        fin
        generic-lens-lite
        HUnit
        lens
        optics-core
        QuickCheck
        ral
        record-hasfield
        singleton-bool
        sop-core
        symbols
        tasty
        tasty-hunit
        tasty-quickcheck
        template-haskell
        text
        th-compat
        time
        vec
      ];
      doHaddock = false;
      description = "Overloaded pragmas as a plugin";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  overloaded-records = callPackage (
    {
      mkDerivation,
      base,
      data-default-class,
      HUnit,
      template-haskell,
      test-framework,
      test-framework-hunit,
    }:
    mkDerivation {
      pname = "overloaded-records";
      version = "0.4.2.0";
      sha256 = "15ijx0mbgxlwardr39dsya21hidfwwgsd374s6kasg2imhzv9cc6";
      revision = "1";
      editedCabalFile = "01bn5jqfkffcl4xdvw7hbarv0pvwgdrjcfvm4gqaz7ia7cwcpynr";
      libraryHaskellDepends = [
        base
        data-default-class
        template-haskell
      ];
      testHaskellDepends = [
        base
        data-default-class
        HUnit
        template-haskell
        test-framework
        test-framework-hunit
      ];
      description = "Overloaded Records based on current GHC proposal";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  overture = callPackage (
    {
      mkDerivation,
      base,
      criterion,
      doctest,
    }:
    mkDerivation {
      pname = "overture";
      version = "0.0.5";
      sha256 = "0mv9iakq1yjawf7f0zckmxbzlcv2rlqngsllfsrcydi6lxazznzw";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        doctest
      ];
      benchmarkHaskellDepends = [
        base
        criterion
      ];
      description = "An alternative to some of the Prelude";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
