# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  pcgen = callPackage (
    {
      mkDerivation,
      base,
      criterion,
      deepseq,
      hspec,
      QuickCheck,
      random,
    }:
    mkDerivation {
      pname = "pcgen";
      version = "2.0.1";
      sha256 = "15116krysjvp3if7rdqcfjgqappfybjzwmgrkd5v5x8w62izhnla";
      libraryHaskellDepends = [
        base
        random
      ];
      testHaskellDepends = [
        base
        hspec
        QuickCheck
        random
      ];
      benchmarkHaskellDepends = [
        base
        criterion
        deepseq
        random
      ];
      description = "A fast, pseudorandom number generator";
      license = lib.licenses.asl20;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
