# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  penn-treebank = callPackage (
    {
      mkDerivation,
      base,
      containers,
      parsec,
    }:
    mkDerivation {
      pname = "penn-treebank";
      version = "0.1.0.1";
      sha256 = "12c5bzn3ac8783lny56n7rd8a1ik4ayfm1pr5v7gm7z53f7iz0qy";
      libraryHaskellDepends = [
        base
        containers
        parsec
      ];
      description = "Tools for manipulating the Penn TreeBank";
      license = lib.licenses.bsd3;
    }
  ) { };

  penntreebank-megaparsec = callPackage (
    {
      mkDerivation,
      base,
      containers,
      hspec,
      hspec-discover,
      megaparsec,
      mtl,
      template-haskell,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "penntreebank-megaparsec";
      version = "0.2.0";
      sha256 = "1238y2wya0ryas58n0b0l4gjmsrzl0dwns0f4gx5m8q6aq4d33c9";
      libraryHaskellDepends = [
        base
        containers
        megaparsec
        mtl
        template-haskell
        transformers
      ];
      testHaskellDepends = [
        base
        containers
        hspec
        megaparsec
        mtl
        template-haskell
        text
        transformers
      ];
      testToolDepends = [ hspec-discover ];
      description = "Parser combinators for trees in the Penn Treebank format";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  penny = callPackage (
    {
      mkDerivation,
      action-permutations,
      anonymous-sums,
      base,
      bytestring,
      cereal,
      containers,
      contravariant,
      either,
      matchers,
      multiarg,
      ofx,
      old-locale,
      parsec,
      prednote,
      QuickCheck,
      rainbow,
      rainbox,
      random-shuffle,
      semigroups,
      split,
      tasty,
      tasty-quickcheck,
      text,
      time,
      transformers,
    }:
    mkDerivation {
      pname = "penny";
      version = "0.32.0.10";
      sha256 = "0bzxihhi7cs8cqbnz7mf6sj12dyr267265asc010pgyffpjc22qi";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        action-permutations
        anonymous-sums
        base
        bytestring
        cereal
        containers
        contravariant
        either
        matchers
        multiarg
        ofx
        old-locale
        parsec
        prednote
        rainbow
        rainbox
        semigroups
        split
        text
        time
        transformers
      ];
      executableHaskellDepends = [ base ];
      testHaskellDepends = [
        anonymous-sums
        base
        parsec
        QuickCheck
        random-shuffle
        semigroups
        tasty
        tasty-quickcheck
        text
        time
        transformers
      ];
      description = "Extensible double-entry accounting system";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  penny-bin = callPackage (
    {
      mkDerivation,
      base,
      containers,
      explicit-exception,
      multiarg,
      parsec,
      penny-lib,
      pretty-show,
      semigroups,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "penny-bin";
      version = "0.22.0.0";
      sha256 = "0mdl8wpcy2yzscpww6vv5vhgiwy5xi0js1yxd7y4h5dmvhxsrr9l";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        containers
        explicit-exception
        multiarg
        parsec
        penny-lib
        pretty-show
        semigroups
        text
        transformers
      ];
      description = "Deprecated - use penny package instead";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  penny-lib = callPackage (
    {
      mkDerivation,
      action-permutations,
      base,
      binary,
      bytestring,
      cereal,
      containers,
      explicit-exception,
      matchers,
      multiarg,
      ofx,
      old-locale,
      parsec,
      prednote,
      pretty-show,
      rainbow,
      semigroups,
      split,
      text,
      time,
      transformers,
    }:
    mkDerivation {
      pname = "penny-lib";
      version = "0.22.0.0";
      sha256 = "0fy671xvia7kjlcrwpsv93gsnyz5wvcajlva98ykbh7cdkf56b17";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        action-permutations
        base
        binary
        bytestring
        cereal
        containers
        explicit-exception
        matchers
        multiarg
        ofx
        old-locale
        parsec
        prednote
        pretty-show
        rainbow
        semigroups
        split
        text
        time
        transformers
      ];
      description = "Deprecated - use penny package instead";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
