# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  phoityne = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      Cabal,
      cmdargs,
      conduit,
      conduit-extra,
      ConfigFile,
      containers,
      directory,
      filepath,
      gtk3,
      hslogger,
      hspec,
      HStringTemplate,
      MissingH,
      mtl,
      parsec,
      process,
      resourcet,
      safe,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "phoityne";
      version = "0.0.5.0";
      sha256 = "0s2m9y7zb0219dz547z5d4plgrnaqvwzsbvm5cw7mv8dq043zdf3";
      isLibrary = false;
      isExecutable = true;
      enableSeparateDataOutput = true;
      executableHaskellDepends = [
        base
        bytestring
        Cabal
        cmdargs
        conduit
        conduit-extra
        ConfigFile
        containers
        directory
        filepath
        gtk3
        hslogger
        HStringTemplate
        MissingH
        mtl
        parsec
        process
        resourcet
        safe
        text
        transformers
      ];
      testHaskellDepends = [
        base
        hspec
      ];
      description = "Deprecated - ghci debug viewer with simple editor";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "phoityne";
      broken = true;
    }
  ) { };

  phoityne-vscode = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      Cabal,
      cmdargs,
      conduit,
      conduit-extra,
      containers,
      data-default,
      directory,
      filepath,
      fsnotify,
      hslogger,
      lens,
      MissingH,
      mtl,
      parsec,
      process,
      resourcet,
      safe,
      safe-exceptions,
      split,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "phoityne-vscode";
      version = "0.0.28.0";
      sha256 = "106y0j3a3xnz76pdv1vdag1wqn21ybypxzygs66jm1qv6vlragcn";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        aeson
        base
        bytestring
        Cabal
        cmdargs
        conduit
        conduit-extra
        containers
        data-default
        directory
        filepath
        fsnotify
        hslogger
        lens
        MissingH
        mtl
        parsec
        process
        resourcet
        safe
        safe-exceptions
        split
        text
        transformers
      ];
      description = "Haskell Debug Adapter for Visual Studio Code";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "phoityne-vscode";
      broken = true;
    }
  ) { };

}
