# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  pi-lcd = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      clock,
      deepseq,
      text,
      unix,
      unordered-containers,
    }:
    mkDerivation {
      pname = "pi-lcd";
      version = "0.1.1.0";
      sha256 = "0120zkza698ww8ng6svp54qywkrvn35pylvcgplfldw4ajln00vn";
      revision = "1";
      editedCabalFile = "0gkpx56dq7lqhlw9iq8zv1kqhpwpd7hkpvld2k86v0zyal526jms";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        bytestring
        clock
        deepseq
        text
        unix
        unordered-containers
      ];
      executableHaskellDepends = [
        base
        text
      ];
      description = "Control an Adafruit character LCD and keypad kit on a Raspberry Pi";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
