# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  plat = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      mtl,
      utf8-string,
    }:
    mkDerivation {
      pname = "plat";
      version = "0.1.0.1";
      sha256 = "06syff2yzrs7qvj8m1f7bgzd6qc834zl9qphv67q3ps5r2hy09qd";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        mtl
        utf8-string
      ];
      description = "Simple templating library";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  platinum-parsing = callPackage (
    {
      mkDerivation,
      base,
      binary,
      clock,
      containers,
      data-hash,
      directory,
      fgl,
      hspec,
      HStringTemplate,
      mtl,
      optparse-applicative,
      parsec,
      text,
      vector,
      yaml,
    }:
    mkDerivation {
      pname = "platinum-parsing";
      version = "0.1.0.0";
      sha256 = "1xngg7w238ngfwj2sz8rgkjnbhlqiz3lqnl6k3akfn9s6cdgk82y";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        binary
        containers
        fgl
        HStringTemplate
        mtl
        parsec
        text
        vector
      ];
      executableHaskellDepends = [
        base
        binary
        clock
        containers
        data-hash
        directory
        fgl
        mtl
        optparse-applicative
        text
        vector
        yaml
      ];
      testHaskellDepends = [
        base
        containers
        fgl
        hspec
        vector
      ];
      description = "General Framework for compiler development";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "pp";
      broken = true;
    }
  ) { };

}
