# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  prizm = callPackage (
    {
      mkDerivation,
      base,
      convertible,
      HUnit,
      QuickCheck,
      test-framework,
      test-framework-hunit,
      test-framework-quickcheck2,
      text,
    }:
    mkDerivation {
      pname = "prizm";
      version = "3.0.0";
      sha256 = "10sjs223i7yqhhdhd6lpaq4sz30faywiw0yp494dziybh63lrg4v";
      libraryHaskellDepends = [
        base
        convertible
        text
      ];
      testHaskellDepends = [
        base
        convertible
        HUnit
        QuickCheck
        test-framework
        test-framework-hunit
        test-framework-quickcheck2
      ];
      description = "Convert colors to different color spaces, interpolate colors, and transform colors";
      license = lib.licenses.bsd3;
    }
  ) { };

}
