# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  pro-abstract = callPackage (
    {
      mkDerivation,
      base,
      containers,
      deepseq,
      hashable,
      hedgehog,
      hedgehog-optics,
      neat-interpolation,
      optics-core,
      text,
    }:
    mkDerivation {
      pname = "pro-abstract";
      version = "0.3.0.0";
      sha256 = "1k7kimr067f0hc7g9m9lb7zihdnhv6508zi02w7zvj8w479ny73s";
      libraryHaskellDepends = [
        base
        containers
        deepseq
        hashable
        optics-core
        text
      ];
      testHaskellDepends = [
        base
        containers
        deepseq
        hashable
        hedgehog
        hedgehog-optics
        neat-interpolation
        optics-core
        text
      ];
      doHaddock = false;
      description = "Abstract syntax for writing documents";
      license = lib.meta.getLicenseFromSpdxId "MPL-2.0";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  pro-source = callPackage (
    {
      mkDerivation,
      base,
      deepseq,
      hashable,
      optics-core,
      prettyprinter,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      text,
      vector,
    }:
    mkDerivation {
      pname = "pro-source";
      version = "0.1.0.0";
      sha256 = "0c3xhdggw6cw8h8jxlkh4vi2xmcaibvj1c5klm9mf8cfyr4f6722";
      revision = "1";
      editedCabalFile = "1mxc6lbwdhk1d5in711ma1vvd60nckfb17ss8xbj68b8irw160ng";
      libraryHaskellDepends = [
        base
        deepseq
        hashable
        optics-core
        prettyprinter
        text
        vector
      ];
      testHaskellDepends = [
        base
        deepseq
        hashable
        optics-core
        prettyprinter
        tasty
        tasty-hunit
        tasty-quickcheck
        text
        vector
      ];
      description = "Utilities for tracking source locations";
      license = lib.meta.getLicenseFromSpdxId "MPL-2.0";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
