# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  psql = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cgroup-rts-threads,
      concurrency,
      containers,
      cryptonite,
      exceptions,
      hspec,
      massiv,
      megaparsec,
      mtl,
      postgresql-libpq,
      semigroupoids,
      simpoole,
      sop-core,
      template-haskell,
      text,
      unordered-containers,
      vector,
    }:
    mkDerivation {
      pname = "psql";
      version = "0.0.0";
      sha256 = "15f0404yvs6bixzb0wbcp9nnn07wf0vq0dgaxr1pkch4gy8n79ij";
      revision = "1";
      editedCabalFile = "0pfi16q3kv0kxwamggk3jsvy5mmgc7g6qawzxwmz14n8mg61885w";
      libraryHaskellDepends = [
        base
        bytestring
        concurrency
        containers
        cryptonite
        exceptions
        megaparsec
        mtl
        postgresql-libpq
        semigroupoids
        simpoole
        template-haskell
        text
        vector
      ];
      testHaskellDepends = [
        base
        bytestring
        cgroup-rts-threads
        exceptions
        hspec
        massiv
        mtl
        postgresql-libpq
        semigroupoids
        sop-core
        unordered-containers
        vector
      ];
      description = "PostgreSQL client";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  psql-helpers = callPackage (
    {
      mkDerivation,
      base,
      postgresql-simple,
    }:
    mkDerivation {
      pname = "psql-helpers";
      version = "0.1.0.0";
      sha256 = "1x0r68mfv56rp87j8ick875wbq3qzkii9ia60amx6xr40x1acg7i";
      libraryHaskellDepends = [
        base
        postgresql-simple
      ];
      description = "A small collection of helper functions to generate postgresql queries";
      license = lib.licenses.mit;
    }
  ) { };

  psql-utils = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      hashable,
      postgresql-simple,
      resource-pool,
      time,
    }:
    mkDerivation {
      pname = "psql-utils";
      version = "0.2.0.1";
      sha256 = "0vqi45v5ghv36gqmqc0ddhm4rwc0zg9qckl0bf7klwiiczs52smq";
      libraryHaskellDepends = [
        aeson
        base
        hashable
        postgresql-simple
        resource-pool
        time
      ];
      description = "PostgreSQL Simple util tools";
      license = lib.licenses.bsd3;
    }
  ) { };

}
