# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  PTQ = callPackage (
    {
      mkDerivation,
      base,
      containers,
      mtl,
      network,
      network-uri,
      xml,
    }:
    mkDerivation {
      pname = "PTQ";
      version = "0.0.8";
      sha256 = "0mbyf63s19rps7p74b4fazbfccpjzx40l1fjszv38kprrg7jff2s";
      isLibrary = false;
      isExecutable = true;
      enableSeparateDataOutput = true;
      executableHaskellDepends = [
        base
        containers
        mtl
        network
        network-uri
        xml
      ];
      description = "An implementation of Montague's PTQ";
      license = "LGPL";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
