# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  pure-cdb = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      containers,
      directory,
      mtl,
      test-simple,
      Unixutils,
      vector,
    }:
    mkDerivation {
      pname = "pure-cdb";
      version = "0.1.2";
      sha256 = "0h7qycpz86r29yshbqm5cmvamv65jj66cs9m03y6qzxda8q8l8i5";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
        directory
        mtl
        vector
      ];
      testHaskellDepends = [
        base
        bytestring
        containers
        mtl
        test-simple
        Unixutils
        vector
      ];
      description = "Another pure-haskell CDB (Constant Database) implementation";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  pure-fft = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "pure-fft";
      version = "0.2.0";
      sha256 = "1zzravfgxbx07c38pf0p73a9nzjk2pbq3hzfw8v9zkqj95b3l94i";
      libraryHaskellDepends = [ base ];
      description = "Fast Fourier Transform";
      license = lib.licenses.bsd3;
    }
  ) { };

  pure-io = callPackage (
    {
      mkDerivation,
      base,
      containers,
      mtl,
      safe,
    }:
    mkDerivation {
      pname = "pure-io";
      version = "0.2.1";
      sha256 = "0pzvkd8jxw859s187n972yaq5wmwi00cxwhivgffr7z29hr0zvx9";
      revision = "1";
      editedCabalFile = "04r055y62f46lxhm4wbfmdk115fslw7lapw06r16lzb1l48m0phj";
      libraryHaskellDepends = [
        base
        containers
        mtl
        safe
      ];
      description = "Pure IO monad";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  pure-noise = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-pretty,
      base,
      bytestring,
      deepseq,
      directory,
      filepath,
      JuicyPixels,
      massiv,
      primitive,
      random,
      tasty,
      tasty-bench,
      tasty-discover,
      tasty-golden,
      tasty-hunit,
      tasty-quickcheck,
      text,
      typed-process,
      vector,
    }:
    mkDerivation {
      pname = "pure-noise";
      version = "0.2.1.1";
      sha256 = "03vwa4yg1shlv7h092a53nxfnp4qa0yi0c17jrv3nz3jdzac1qpr";
      libraryHaskellDepends = [
        base
        primitive
      ];
      testHaskellDepends = [
        aeson
        aeson-pretty
        base
        bytestring
        directory
        filepath
        JuicyPixels
        massiv
        primitive
        tasty
        tasty-discover
        tasty-golden
        tasty-hunit
        tasty-quickcheck
        text
        typed-process
      ];
      testToolDepends = [ tasty-discover ];
      benchmarkHaskellDepends = [
        base
        deepseq
        massiv
        primitive
        random
        tasty
        tasty-bench
        vector
      ];
      description = "High-performance composable noise generation (Perlin, Simplex, Cellular)";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  pure-priority-queue = callPackage (
    {
      mkDerivation,
      base,
      containers,
    }:
    mkDerivation {
      pname = "pure-priority-queue";
      version = "0.14";
      sha256 = "125vnkjx6n7pgflk9iqg7b6daw55a1rdfi9pfgp39ikfcx9vhb3p";
      libraryHaskellDepends = [
        base
        containers
      ];
      description = "A pure priority queue";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  pure-priority-queue-tests = callPackage (
    {
      mkDerivation,
      base,
      containers,
      pure-priority-queue,
      QuickCheck,
      test-framework,
      test-framework-quickcheck2,
    }:
    mkDerivation {
      pname = "pure-priority-queue-tests";
      version = "0.12";
      sha256 = "17x2drpmdppzxp3nnxq0vajxrzdnhpapk9rz9qcqaxbg934c7h3d";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        containers
        pure-priority-queue
        QuickCheck
        test-framework
        test-framework-quickcheck2
      ];
      description = "Tests for the pure-priority-queue package";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "pure-priority-queue-tests";
    }
  ) { };

  pure-shuffle = callPackage (
    {
      mkDerivation,
      base,
      hspec,
      mono-traversable,
      QuickCheck,
      random-shuffle,
      transformers,
    }:
    mkDerivation {
      pname = "pure-shuffle";
      version = "0.1.1.1";
      sha256 = "0wgb32xjgknq6ncq54frpzzkzrf1firg9blpl79pi2y477slgr6m";
      libraryHaskellDepends = [
        base
        mono-traversable
        random-shuffle
      ];
      testHaskellDepends = [
        base
        hspec
        mono-traversable
        QuickCheck
        random-shuffle
        transformers
      ];
      license = lib.licenses.asl20;
    }
  ) { };

  pure-sum = callPackage (
    {
      mkDerivation,
      base,
      hspec,
      hspec-core,
      hspec-discover,
      text,
      text-manipulate,
    }:
    mkDerivation {
      pname = "pure-sum";
      version = "0.1.0.0";
      sha256 = "12yn8cj5vzwm4z2vnvclw6x6r17jzhzc29rv7m1mpvgmh174d9jx";
      libraryHaskellDepends = [
        base
        text
        text-manipulate
      ];
      testHaskellDepends = [
        base
        hspec
        hspec-core
        hspec-discover
        text
      ];
      testToolDepends = [ hspec-discover ];
      description = "Derive fromString/toString-like for pure sum types";
      license = lib.meta.getLicenseFromSpdxId "ISC";
    }
  ) { };

  pure-sum-aeson = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      containers,
      hspec,
      hspec-core,
      hspec-discover,
      pure-sum,
      text,
    }:
    mkDerivation {
      pname = "pure-sum-aeson";
      version = "0.1.0.0";
      sha256 = "08jcm06gm8a6x5b8m6j2l6xz8h8k1y6x3mclsl9lc86whmj3vvk2";
      libraryHaskellDepends = [
        aeson
        base
        pure-sum
        text
      ];
      testHaskellDepends = [
        aeson
        base
        containers
        hspec
        hspec-core
        hspec-discover
      ];
      testToolDepends = [ hspec-discover ];
      description = "Derive fromString/toString-like for pure sum types (aeson instances)";
      license = lib.meta.getLicenseFromSpdxId "ISC";
    }
  ) { };

  pure-zlib = callPackage (
    {
      mkDerivation,
      array,
      base,
      base-compat,
      bytestring,
      bytestring-builder,
      containers,
      criterion,
      filepath,
      ghc-prim,
      HUnit,
      primitive,
      QuickCheck,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      time,
      vector,
      zlib,
    }:
    mkDerivation {
      pname = "pure-zlib";
      version = "0.8.0";
      sha256 = "0hfi0jhn7gxzxvn94fbhfbih7qyak55qrdbbkllfx9vhji21pc6w";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        array
        base
        base-compat
        bytestring
        bytestring-builder
        containers
        primitive
        vector
      ];
      executableHaskellDepends = [
        base
        base-compat
        bytestring
        ghc-prim
      ];
      testHaskellDepends = [
        base
        base-compat
        bytestring
        filepath
        HUnit
        QuickCheck
        tasty
        tasty-hunit
        tasty-quickcheck
      ];
      benchmarkHaskellDepends = [
        base
        base-compat
        bytestring
        criterion
        time
        zlib
      ];
      description = "A Haskell-only implementation of zlib / DEFLATE";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "deflate";
      broken = true;
    }
  ) { };

  pureMD5 = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      cereal,
      crypto-api,
      crypto-api-tests,
      pretty-hex,
      QuickCheck,
      tagged,
      test-framework,
      test-framework-quickcheck2,
    }:
    mkDerivation {
      pname = "pureMD5";
      version = "2.1.4";
      sha256 = "0qwkvxwi9wh6knn69rg2hvc8ngmv1if77kmpcnp0xqr0l30fwavq";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        cereal
        crypto-api
        tagged
      ];
      testHaskellDepends = [
        base
        binary
        bytestring
        cereal
        crypto-api-tests
        pretty-hex
        QuickCheck
        test-framework
        test-framework-quickcheck2
      ];
      description = "A Haskell-only implementation of the MD5 digest (hash) algorithm";
      license = lib.licenses.bsd3;
    }
  ) { };

  purebred-email = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      base64-bytestring,
      bytestring,
      case-insensitive,
      concise,
      deepseq,
      hedgehog,
      lens,
      quickcheck-instances,
      random,
      semigroupoids,
      stringsearch,
      tasty,
      tasty-golden,
      tasty-hedgehog,
      tasty-hunit,
      tasty-quickcheck,
      text,
      time,
    }:
    mkDerivation {
      pname = "purebred-email";
      version = "0.7";
      sha256 = "1rw72rjji7bclql975gqpbisapjgzzywydql6p6b1v0ivzpsaq3s";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        attoparsec
        base
        base64-bytestring
        bytestring
        case-insensitive
        concise
        deepseq
        lens
        random
        semigroupoids
        stringsearch
        text
        time
      ];
      testHaskellDepends = [
        attoparsec
        base
        bytestring
        case-insensitive
        hedgehog
        lens
        quickcheck-instances
        random
        tasty
        tasty-golden
        tasty-hedgehog
        tasty-hunit
        tasty-quickcheck
        text
        time
      ];
      description = "types and parser for email messages (including MIME)";
      license = lib.meta.getLicenseFromSpdxId "AGPL-3.0-or-later";
      maintainers = [ lib.maintainers.maralorn ];
    }
  ) { };

  purekell = callPackage (
    {
      mkDerivation,
      base,
      hspec,
      hspec-discover,
      megaparsec,
      QuickCheck,
      text,
    }:
    mkDerivation {
      pname = "purekell";
      version = "0.1.0.0";
      sha256 = "1an4yh387wz7k9vqnh77y1wmcaanwb3imp61v74d1xdz1raish8z";
      libraryHaskellDepends = [
        base
        megaparsec
        text
      ];
      testHaskellDepends = [
        base
        hspec
        megaparsec
        QuickCheck
        text
      ];
      testToolDepends = [ hspec-discover ];
      description = "Bidirectional Haskell/PureScript expression translator";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
    }
  ) { };

  purenix = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      containers,
      directory,
      filepath,
      microlens-platform,
      mtl,
      pretty-simple,
      purescript,
      text,
    }:
    mkDerivation {
      pname = "purenix";
      version = "1.1";
      sha256 = "1z6kanz6i3a9nqpmymh6192g9qbpc759ixipnpqa9w1ph7aa8rv0";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        containers
        directory
        filepath
        microlens-platform
        mtl
        pretty-simple
        purescript
        text
      ];
      executableHaskellDepends = [ base ];
      description = "Nix backend for PureScript. Transpile PureScript code to Nix.";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      mainProgram = "purenix";
    }
  ) { };

  puresat = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      filepath,
      minisat,
      parsec,
      primitive,
      QuickCheck,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "puresat";
      version = "0.1";
      sha256 = "14jkk4wkmwh0pqai9zzsq214pc3g9fr3bv2lvq72k50cg49dc72a";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        containers
        parsec
        primitive
      ];
      testHaskellDepends = [
        base
        filepath
        minisat
        primitive
        QuickCheck
        tasty
        tasty-hunit
        tasty-quickcheck
      ];
      doHaddock = false;
      description = "Pure Haskell SAT-solver";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  purescheme-wai-routing-core = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      case-insensitive,
      http-media,
      http-types,
      interpolate,
      text,
      wai,
      warp,
    }:
    mkDerivation {
      pname = "purescheme-wai-routing-core";
      version = "0.1.3.0";
      sha256 = "0fwgxvn0vblyma3fpbyj9rvbwsrgsqzyd27mripa3yyvm6ygh4s6";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        case-insensitive
        http-media
        http-types
        interpolate
        text
        wai
      ];
      executableHaskellDepends = [
        aeson
        base
        bytestring
        http-types
        text
        wai
        warp
      ];
      testHaskellDepends = [ base ];
      description = "Simple Routing functions for Wai Applications";
      license = lib.licenses.asl20;
      mainProgram = "simple-routing-core-exe";
    }
  ) { };

  purescript = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-better-errors,
      ansi-terminal,
      ansi-wl-pprint,
      array,
      base,
      blaze-html,
      bower-json,
      boxes,
      bytestring,
      Cabal,
      cborg,
      cheapskate,
      clock,
      containers,
      cryptonite,
      data-ordlist,
      deepseq,
      directory,
      dlist,
      edit-distance,
      exceptions,
      file-embed,
      filepath,
      generic-random,
      gitrev,
      Glob,
      happy,
      haskeline,
      hspec,
      hspec-discover,
      HUnit,
      language-javascript,
      lens,
      lifted-async,
      lifted-base,
      memory,
      monad-control,
      monad-logger,
      monoidal-containers,
      mtl,
      network,
      newtype,
      optparse-applicative,
      parallel,
      parsec,
      pattern-arrows,
      process,
      protolude,
      QuickCheck,
      regex-base,
      regex-tdfa,
      safe,
      scientific,
      semialign,
      semigroups,
      serialise,
      sourcemap,
      split,
      stm,
      stringsearch,
      template-haskell,
      text,
      these,
      time,
      transformers,
      transformers-base,
      typed-process,
      utf8-string,
      vector,
      witherable,
    }:
    mkDerivation {
      pname = "purescript";
      version = "0.15.15";
      sha256 = "0rqf4bfn11hf2b7k90h82mffqh6rmfz101i69v1ss2gz8zm26jlw";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        aeson-better-errors
        ansi-terminal
        array
        base
        blaze-html
        bower-json
        boxes
        bytestring
        Cabal
        cborg
        cheapskate
        clock
        containers
        cryptonite
        data-ordlist
        deepseq
        directory
        dlist
        edit-distance
        file-embed
        filepath
        Glob
        haskeline
        language-javascript
        lens
        lifted-async
        lifted-base
        memory
        monad-control
        monad-logger
        monoidal-containers
        mtl
        parallel
        parsec
        pattern-arrows
        process
        protolude
        regex-tdfa
        safe
        scientific
        semialign
        semigroups
        serialise
        sourcemap
        stm
        stringsearch
        template-haskell
        text
        these
        time
        transformers
        transformers-base
        utf8-string
        vector
        witherable
      ];
      libraryToolDepends = [ happy ];
      executableHaskellDepends = [
        aeson
        aeson-better-errors
        ansi-terminal
        ansi-wl-pprint
        array
        base
        blaze-html
        bower-json
        boxes
        bytestring
        Cabal
        cborg
        cheapskate
        clock
        containers
        cryptonite
        data-ordlist
        deepseq
        directory
        dlist
        edit-distance
        exceptions
        file-embed
        filepath
        gitrev
        Glob
        haskeline
        language-javascript
        lens
        lifted-async
        lifted-base
        memory
        monad-control
        monad-logger
        monoidal-containers
        mtl
        network
        optparse-applicative
        parallel
        parsec
        pattern-arrows
        process
        protolude
        regex-tdfa
        safe
        scientific
        semialign
        semigroups
        serialise
        sourcemap
        stm
        stringsearch
        template-haskell
        text
        these
        time
        transformers
        transformers-base
        utf8-string
        vector
        witherable
      ];
      executableToolDepends = [ happy ];
      testHaskellDepends = [
        aeson
        aeson-better-errors
        ansi-terminal
        array
        base
        blaze-html
        bower-json
        boxes
        bytestring
        Cabal
        cborg
        cheapskate
        clock
        containers
        cryptonite
        data-ordlist
        deepseq
        directory
        dlist
        edit-distance
        file-embed
        filepath
        generic-random
        Glob
        haskeline
        hspec
        HUnit
        language-javascript
        lens
        lifted-async
        lifted-base
        memory
        monad-control
        monad-logger
        monoidal-containers
        mtl
        newtype
        parallel
        parsec
        pattern-arrows
        process
        protolude
        QuickCheck
        regex-base
        regex-tdfa
        safe
        scientific
        semialign
        semigroups
        serialise
        sourcemap
        split
        stm
        stringsearch
        template-haskell
        text
        these
        time
        transformers
        transformers-base
        typed-process
        utf8-string
        vector
        witherable
      ];
      testToolDepends = [
        happy
        hspec-discover
      ];
      doCheck = false;
      description = "PureScript Programming Language Compiler";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      mainProgram = "purs";
    }
  ) { };

  purescript-ast = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      base-compat,
      bytestring,
      containers,
      deepseq,
      filepath,
      microlens,
      mtl,
      protolude,
      scientific,
      serialise,
      text,
      vector,
    }:
    mkDerivation {
      pname = "purescript-ast";
      version = "0.1.1.0";
      sha256 = "12zkkbpv1xxvx4d3rybng1kxvw6z5gjr45mfy9bpkmb3jqzl1xd2";
      libraryHaskellDepends = [
        aeson
        base
        base-compat
        bytestring
        containers
        deepseq
        filepath
        microlens
        mtl
        protolude
        scientific
        serialise
        text
        vector
      ];
      description = "PureScript Programming Language Abstract Syntax Tree";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  purescript-bridge = callPackage (
    {
      mkDerivation,
      base,
      containers,
      directory,
      filepath,
      generic-deriving,
      hspec,
      hspec-expectations-pretty-diff,
      lens,
      mtl,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "purescript-bridge";
      version = "0.15.0.0";
      sha256 = "09bjlmwq3vsprngsrvx3g1ah9n60bng91kfswv61lh1bhca0q9z0";
      libraryHaskellDepends = [
        base
        containers
        directory
        filepath
        generic-deriving
        lens
        mtl
        text
        transformers
      ];
      testHaskellDepends = [
        base
        containers
        hspec
        hspec-expectations-pretty-diff
        text
      ];
      description = "Generate PureScript data types from Haskell data types";
      license = lib.licenses.bsd3;
    }
  ) { };

  purescript-bundle-fast = callPackage (
    {
      mkDerivation,
      base,
      containers,
      directory,
      filepath,
      optparse-applicative,
      text,
      vector,
    }:
    mkDerivation {
      pname = "purescript-bundle-fast";
      version = "0.1.0.1";
      sha256 = "0s9db4nb5ppr3yznay7jlgydq68hcdn525cwnxkj41h8fv9sflfw";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        containers
        directory
        filepath
        optparse-applicative
        text
        vector
      ];
      description = "A fast alternative to Purescript's `psc-bundle` to be used during development";
      license = lib.licenses.mit;
      mainProgram = "psc-bundle-fast";
    }
  ) { };

  purescript-cst = callPackage (
    {
      mkDerivation,
      aeson,
      array,
      base,
      base-compat,
      bytestring,
      containers,
      deepseq,
      dlist,
      filepath,
      happy,
      microlens,
      mtl,
      protolude,
      scientific,
      semigroups,
      serialise,
      text,
      vector,
    }:
    mkDerivation {
      pname = "purescript-cst";
      version = "0.5.0.0";
      sha256 = "13gds3hbsz3bhajhs17r9gsdzfmhci6q5plzg0fx6mb89nb4ps7d";
      libraryHaskellDepends = [
        aeson
        array
        base
        base-compat
        bytestring
        containers
        deepseq
        dlist
        filepath
        microlens
        mtl
        protolude
        scientific
        semigroups
        serialise
        text
        vector
      ];
      libraryToolDepends = [ happy ];
      description = "PureScript Programming Language Concrete Syntax Tree";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  purescript-iso = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-attoparsec,
      aeson-diff,
      async,
      attoparsec,
      attoparsec-uri,
      base,
      bytestring,
      containers,
      deepseq,
      emailaddress,
      monad-control,
      mtl,
      QuickCheck,
      quickcheck-instances,
      scientific,
      stm,
      strict,
      tasty,
      tasty-quickcheck,
      text,
      time,
      utf8-string,
      uuid,
      vector,
      zeromq4-haskell,
      zeromq4-simple,
    }:
    mkDerivation {
      pname = "purescript-iso";
      version = "0.0.6";
      sha256 = "0zz71c8mv86ihqwcqsp0cjw9dlyd0xw394dz14mwg16frajn986k";
      libraryHaskellDepends = [
        aeson
        aeson-attoparsec
        aeson-diff
        async
        attoparsec
        attoparsec-uri
        base
        bytestring
        containers
        deepseq
        emailaddress
        monad-control
        mtl
        QuickCheck
        quickcheck-instances
        scientific
        stm
        strict
        text
        time
        utf8-string
        uuid
        vector
        zeromq4-haskell
        zeromq4-simple
      ];
      testHaskellDepends = [
        aeson
        aeson-attoparsec
        aeson-diff
        async
        attoparsec
        attoparsec-uri
        base
        bytestring
        containers
        deepseq
        emailaddress
        monad-control
        mtl
        QuickCheck
        quickcheck-instances
        scientific
        stm
        strict
        tasty
        tasty-quickcheck
        text
        time
        utf8-string
        uuid
        vector
        zeromq4-haskell
        zeromq4-simple
      ];
      description = "Isomorphic trivial data type definitions over JSON";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  purescript-tsd-gen = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      containers,
      directory,
      filepath,
      mtl,
      optparse-applicative,
      purescript,
      text,
    }:
    mkDerivation {
      pname = "purescript-tsd-gen";
      version = "0.3.0.0";
      sha256 = "0246pxgwrqbrhsgixx6mp9w1h355qz29gx1b7bmdxxxafyn2il6n";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        containers
        directory
        filepath
        mtl
        purescript
        text
      ];
      executableHaskellDepends = [
        aeson
        base
        bytestring
        containers
        directory
        filepath
        mtl
        optparse-applicative
        purescript
        text
      ];
      description = "TypeScript Declaration File (.d.ts) generator for PureScript";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "purs-tsd-gen";
      broken = true;
    }
  ) { };

}
