# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  purl = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      case-insensitive,
      containers,
      http-types,
      parsec,
      tasty,
      tasty-hunit,
      text,
    }:
    mkDerivation {
      pname = "purl";
      version = "0.1.0.0";
      sha256 = "07p3jn5ljj0b98hcmacz2yv735c2ywnqywpw2bnyzqxg9ld0c7bx";
      libraryHaskellDepends = [
        aeson
        base
        case-insensitive
        containers
        http-types
        parsec
        text
      ];
      testHaskellDepends = [
        base
        containers
        tasty
        tasty-hunit
        text
      ];
      description = "Support for purl (mostly universal package url)";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

}
