# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  q4c12-twofinger = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      cabal-doctest,
      containers,
      deepseq,
      doctest,
      lens,
      lens-properties,
      semigroupoids,
      tasty,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "q4c12-twofinger";
      version = "0.2";
      sha256 = "0c4fm6pdl1mlh4xnp8syjifknyvbdqwdyiika9pkww4xmf12lv7z";
      setupHaskellDepends = [
        base
        Cabal
        cabal-doctest
      ];
      libraryHaskellDepends = [
        base
        containers
        deepseq
        semigroupoids
      ];
      testHaskellDepends = [
        base
        doctest
        lens
        lens-properties
        tasty
        tasty-quickcheck
      ];
      description = "Efficient alternating finger trees";
      license = lib.licenses.bsd2;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
