# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  qhull = callPackage (
    {
      mkDerivation,
      base,
      combinat,
      containers,
      data-default-class,
      extra,
      hashable,
      ilist,
      insert-ordered-containers,
      optparse-applicative,
      pretty-show,
      random,
      regex-base,
      regex-compat,
      regex-posix,
      split,
      toysolver,
      Unique,
      vector-algorithms,
      vector-space,
    }:
    mkDerivation {
      pname = "qhull";
      version = "0.1.0.4";
      sha256 = "01a9dngcq0f87zyp6p20cw6p9rz22ln1hixnzc6gp1wpcjgas7r1";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        combinat
        containers
        data-default-class
        extra
        hashable
        ilist
        insert-ordered-containers
        pretty-show
        random
        regex-base
        regex-compat
        regex-posix
        split
        toysolver
        Unique
        vector-algorithms
        vector-space
      ];
      executableHaskellDepends = [
        base
        combinat
        containers
        extra
        ilist
        insert-ordered-containers
        optparse-applicative
        pretty-show
        regex-base
        regex-compat
        regex-posix
      ];
      description = "Delaunay triangulation, Voronoi diagrams and convex hulls";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  qhull-simple = callPackage (
    {
      mkDerivation,
      base,
      qhull,
      vector,
    }:
    mkDerivation {
      pname = "qhull-simple";
      version = "0.1";
      sha256 = "0g0abqc5z9nysm21c77kylkka1bvyn16ycinws1lcrjy53cb82sw";
      libraryHaskellDepends = [
        base
        vector
      ];
      librarySystemDepends = [ qhull ];
      description = "Simple bindings to Qhull, a library for computing convex hulls";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { inherit (pkgs) qhull; };

}
