# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  quaalude = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "quaalude";
      version = "0.0.0.1";
      sha256 = "0wwsrpm2s7gs2c4fwh4qvhnjywxfyf94dw715bz34q7bzyyk3lc6";
      revision = "3";
      editedCabalFile = "0pqi04fvyclnx4lfq8ifax6l4kayay6xbmwp0k0h7yjz14k252gn";
      libraryHaskellDepends = [ base ];
      description = "Extremely minimal prelude";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
    }
  ) { };

}
