# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Range = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "Range";
      version = "0.1.0.0";
      sha256 = "0759508s75zba89jjr56sqpm7idgwsxynmf9zl9hwrz9q11fxrqh";
      libraryHaskellDepends = [ base ];
      description = "Data structure for managing ranges";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  Ranged-sets = callPackage (
    {
      mkDerivation,
      base,
      HUnit,
      QuickCheck,
    }:
    mkDerivation {
      pname = "Ranged-sets";
      version = "0.5.0";
      sha256 = "03254dl4nl7x4dhlkj6285gc6djgwklfbg1yypl1vfl72l5bsh40";
      libraryHaskellDepends = [
        base
        QuickCheck
      ];
      testHaskellDepends = [
        base
        HUnit
        QuickCheck
      ];
      description = "Ranged sets for Haskell";
      license = lib.licenses.bsd3;
    }
  ) { };

  range = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      free,
      parsec,
      QuickCheck,
      random,
      test-framework,
      test-framework-quickcheck2,
    }:
    mkDerivation {
      pname = "range";
      version = "0.3.0.2";
      sha256 = "0kvb5bl4k2gwm0hd71plwh7hmwbgk17g77iq39d7lqw4nmlg3j0k";
      libraryHaskellDepends = [
        base
        free
        parsec
      ];
      testHaskellDepends = [
        base
        Cabal
        free
        QuickCheck
        random
        test-framework
        test-framework-quickcheck2
      ];
      description = "An efficient and versatile range library";
      license = lib.licenses.mit;
    }
  ) { };

  range-set-list = callPackage (
    {
      mkDerivation,
      base,
      containers,
      deepseq,
      hashable,
      tasty,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "range-set-list";
      version = "0.1.4";
      sha256 = "1w5kvqi66wg13m6ibzkjkn1gf725msr6ks4nfm5chhk30ad4lvj1";
      revision = "1";
      editedCabalFile = "0819grvps1rb88s1a93mh1mwhxqk67rpijjk13lpfib9948scnfy";
      libraryHaskellDepends = [
        base
        containers
        deepseq
        hashable
      ];
      testHaskellDepends = [
        base
        containers
        deepseq
        hashable
        tasty
        tasty-quickcheck
      ];
      description = "Memory efficient sets with ranges of elements";
      license = lib.meta.getLicenseFromSpdxId "MIT";
    }
  ) { };

  range-space = callPackage (
    {
      mkDerivation,
      base,
      QuickCheck,
      semigroups,
      test-framework,
      test-framework-quickcheck2,
      time,
      vector-space,
      vector-space-points,
    }:
    mkDerivation {
      pname = "range-space";
      version = "0.1.2.0";
      sha256 = "1hrqdf2rjvf69vwaaw92fw2xa0j2x4i9g6231dz9s08i0pm6r39q";
      libraryHaskellDepends = [
        base
        semigroups
        vector-space
        vector-space-points
      ];
      testHaskellDepends = [
        base
        QuickCheck
        semigroups
        test-framework
        test-framework-quickcheck2
        time
        vector-space
        vector-space-points
      ];
      description = "A Range type with vector-space instances";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  ranged-list = callPackage (
    {
      mkDerivation,
      base,
      doctest,
      ghc-internal,
      typecheck-plugin-nat-simple,
    }:
    mkDerivation {
      pname = "ranged-list";
      version = "0.1.2.3";
      sha256 = "079h4xvjr4amrr48gljfc438savyvm5qfmnwwz29k8ifavxzxzw1";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        ghc-internal
        typecheck-plugin-nat-simple
      ];
      testHaskellDepends = [
        base
        doctest
        ghc-internal
        typecheck-plugin-nat-simple
      ];
      description = "The list like structure whose length or range of length can be specified";
      license = lib.licenses.bsd3;
    }
  ) { };

  rangemin = callPackage (
    {
      mkDerivation,
      base,
      containers,
      primitive,
      vector,
    }:
    mkDerivation {
      pname = "rangemin";
      version = "2.2.2";
      sha256 = "01n1m3ibi44pjg04mg16j751fjzkspmnq8bzxz55qbyi22wshnwc";
      libraryHaskellDepends = [
        base
        containers
        primitive
        vector
      ];
      description = "Linear range-min algorithms";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  ranges = callPackage (
    {
      mkDerivation,
      base,
      containers,
    }:
    mkDerivation {
      pname = "ranges";
      version = "0.2.4";
      sha256 = "1ymvmvfvzkdxblg691g9n5y94gpiz782jgyvaisg5mydzj1s1fyv";
      libraryHaskellDepends = [
        base
        containers
      ];
      description = "Ranges and various functions on them";
      license = lib.licenses.bsd3;
    }
  ) { };

  rangeset = callPackage (
    {
      mkDerivation,
      array,
      base,
      containers,
      deepseq,
      gauge,
      QuickCheck,
      random,
      random-shuffle,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
    }:
    mkDerivation {
      pname = "rangeset";
      version = "0.1.0.0";
      sha256 = "13z83p1y5afnncqakih73jgn47kk4s71cz1h424s0fx8b9frddyh";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        tasty
        tasty-hunit
        tasty-quickcheck
      ];
      benchmarkHaskellDepends = [
        array
        base
        containers
        deepseq
        gauge
        QuickCheck
        random
        random-shuffle
      ];
      description = "Efficient sets for semi-contiguous data";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

}
