# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  rawfilepath = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      unix,
    }:
    mkDerivation {
      pname = "rawfilepath";
      version = "1.1.1";
      sha256 = "0sdzwg69yaxrfa46khimwaw6nyrb6vak2g3awwq7rc5phgd7ky23";
      libraryHaskellDepends = [
        base
        bytestring
        unix
      ];
      testHaskellDepends = [
        base
        bytestring
      ];
      description = "Use RawFilePath instead of FilePath";
      license = lib.licenses.asl20;
    }
  ) { };

}
