# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  RBTree = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "RBTree";
      version = "0.0.5";
      sha256 = "0p46b105lixbxqjz8pwxf4asl4s7zdh2ss3nvgmp1rclqfg6cwrq";
      libraryHaskellDepends = [ base ];
      description = "Pure haskell Red-Black-Tree implemetation";
      license = lib.licenses.bsd3;
    }
  ) { };

}
