# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  red-black-record = callPackage (
    {
      mkDerivation,
      base,
      sop-core,
      tasty,
      tasty-hunit,
    }:
    mkDerivation {
      pname = "red-black-record";
      version = "2.1.6.0";
      sha256 = "089fbazh6q0x4q07cda5msn143l2zz5a70vgc63xm0r3f0n1qybp";
      libraryHaskellDepends = [
        base
        sop-core
      ];
      testHaskellDepends = [
        base
        sop-core
        tasty
        tasty-hunit
      ];
      doHaddock = false;
      description = "Extensible records and variants indexed by a type-level Red-Black tree";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  red-black-tree = callPackage (
    {
      mkDerivation,
      base,
      hspec,
      QuickCheck,
    }:
    mkDerivation {
      pname = "red-black-tree";
      version = "0.1.0.0";
      sha256 = "0wz3afh2d2rzhp76whbn607pzmpkd28imycrdrdbk1pxrk1psbxf";
      libraryHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        hspec
        QuickCheck
      ];
      description = "Red Black Trees implemented in Haskell";
      license = lib.licenses.bsd3;
    }
  ) { };

}
