# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  route-generator = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      network,
      text,
      yesod-routes,
    }:
    mkDerivation {
      pname = "route-generator";
      version = "0.6.1";
      sha256 = "0bfrb3mz9nxrl4l5pikrp3x4igq4w9jlmvwikyc71ph8ks6rghc6";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        attoparsec
        base
        network
        text
        yesod-routes
      ];
      description = "Utility to generate routes for use with yesod-routes";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "routeGenerator";
    }
  ) { };

  route-planning = callPackage (
    {
      mkDerivation,
      base,
      containers,
      coordinate,
      directory,
      doctest,
      filepath,
      lens,
      QuickCheck,
      semigroupoids,
      semigroups,
      text,
      xsd,
    }:
    mkDerivation {
      pname = "route-planning";
      version = "0.0.3";
      sha256 = "0l3z9hjd8xqnahffg930qi13pf8cpiq44diqmpmh1narcllcbgj7";
      libraryHaskellDepends = [
        base
        containers
        coordinate
        lens
        semigroupoids
        semigroups
        text
        xsd
      ];
      testHaskellDepends = [
        base
        directory
        doctest
        filepath
        QuickCheck
      ];
      description = "A library and utilities for creating a route";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
