# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  rtnetlink = callPackage (
    {
      mkDerivation,
      base,
      bits-bytestring,
      bytestring,
      cereal,
      exceptions,
      hspec,
      linux-namespaces,
      pretty-hex,
      random,
      socket,
      transformers,
      unix,
    }:
    mkDerivation {
      pname = "rtnetlink";
      version = "0.2.0.1";
      sha256 = "1ly3cgkbnz24p33vlgbllmxx25f0b3d1rzr05gzcnhjlg7nxwwga";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bits-bytestring
        bytestring
        cereal
        exceptions
        pretty-hex
        random
        socket
        transformers
        unix
      ];
      testHaskellDepends = [
        base
        bytestring
        exceptions
        hspec
        linux-namespaces
        socket
        unix
      ];
      description = "Manipulate network devices, addresses, and routes on Linux";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
