# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  ruby-marshal = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      containers,
      fail,
      hspec,
      hspec-discover,
      mtl,
      string-conv,
      vector,
    }:
    mkDerivation {
      pname = "ruby-marshal";
      version = "0.2.1";
      sha256 = "18kdagf0lyghpaffzgw42ql1wrqkh13rfqjpj23i09i67pqrv3lk";
      revision = "3";
      editedCabalFile = "01zvrzwd6knw3lkbnc50m8ql4bk7wsnglsf2s2cbvjmd3fzacdka";
      libraryHaskellDepends = [
        base
        bytestring
        cereal
        containers
        fail
        mtl
        string-conv
        vector
      ];
      testHaskellDepends = [
        base
        bytestring
        cereal
        containers
        fail
        hspec
        mtl
        string-conv
        vector
      ];
      testToolDepends = [ hspec-discover ];
      description = "Parse a subset of Ruby objects serialised with Marshal.dump.";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  ruby-qq = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      haskell-src-exts,
      haskell-src-meta,
      pcre-light,
      process,
      template-haskell,
      trifecta,
    }:
    mkDerivation {
      pname = "ruby-qq";
      version = "0.1.0.0";
      sha256 = "1d2a31kiiv0p8d2yygpg8mgrz0xy6zh5qnf49hz70yk2vavkcac1";
      libraryHaskellDepends = [
        base
        bytestring
        haskell-src-exts
        haskell-src-meta
        pcre-light
        process
        template-haskell
        trifecta
      ];
      description = "rubyish quasiquoters";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
