# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  run-haskell-module = callPackage (
    {
      mkDerivation,
      base,
      data-default,
      filepath,
      process,
    }:
    mkDerivation {
      pname = "run-haskell-module";
      version = "0.0.2";
      sha256 = "1ra8rv7cbsj1x8vfd3sbynd7a73v9arfimzcfhg9j6blqcii2i2d";
      libraryHaskellDepends = [
        base
        data-default
        filepath
        process
      ];
      description = "Running newly generated Haskell source module";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  run-st = callPackage (
    {
      mkDerivation,
      base,
      primitive,
      primitive-unlifted,
    }:
    mkDerivation {
      pname = "run-st";
      version = "0.1.3.3";
      sha256 = "0m56v348mp78g1g60bgxgwnvb3iczg8rccnq55mhmhzzvh9msn4p";
      libraryHaskellDepends = [
        base
        primitive
        primitive-unlifted
      ];
      description = "runST without boxing penalty";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

}
