# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  rwlock = callPackage (
    {
      mkDerivation,
      base,
      monad-loops-stm,
      stm,
      syb,
    }:
    mkDerivation {
      pname = "rwlock";
      version = "0.0.0.3";
      sha256 = "0isx32ayaqh7vhcyl11ykdy8f1chs1fdw73h3c2r53k989yfkmba";
      libraryHaskellDepends = [
        base
        monad-loops-stm
        stm
        syb
      ];
      description = "Multiple-read / single-write locks";
      license = lib.licenses.publicDomain;
    }
  ) { };

}
