# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Salsa =
    callPackage
      (
        {
          mkDerivation,
          base,
          bytestring,
          file-embed,
          glib,
          mono,
        }:
        mkDerivation {
          pname = "Salsa";
          version = "0.2.0.2";
          sha256 = "0915mwi1ksa85in03vzm5hqbvk6ih7l0zslg5cmy7j9fc0jhgwgd";
          libraryHaskellDepends = [
            base
            bytestring
            file-embed
          ];
          librarySystemDepends = [
            glib
            mono
          ];
          description = "A .NET Bridge for Haskell";
          license = lib.licenses.bsd3;
          hydraPlatforms = lib.platforms.none;
          broken = true;
        }
      )
      {
        inherit (pkgs) glib;
        inherit (pkgs) mono;
      };

}
