# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  sat = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "sat";
      version = "1.1.1";
      sha256 = "1ia2asqnxzpyr9s4n488yy00388x0bfy8kwqjx17fap33jkjfi6p";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [ base ];
      description = "CNF SATisfier";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
