# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  say = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      gauge,
      hspec,
      text,
      transformers,
      unliftio,
    }:
    mkDerivation {
      pname = "say";
      version = "0.1.0.1";
      sha256 = "1r5kffjfwpas45g74sip8glrj1m9nygrnxjm7xgw898rq9pnafgn";
      libraryHaskellDepends = [
        base
        bytestring
        text
        transformers
      ];
      testHaskellDepends = [
        base
        bytestring
        hspec
        text
        transformers
        unliftio
      ];
      benchmarkHaskellDepends = [
        base
        bytestring
        gauge
        text
        transformers
        unliftio
      ];
      description = "Send textual messages to a Handle in a thread-friendly way";
      license = lib.licenses.mit;
      maintainers = [ lib.maintainers.maralorn ];
    }
  ) { };

}
