# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  sbv-program = callPackage (
    {
      mkDerivation,
      base,
      bifunctors,
      containers,
      pretty-simple,
      sbv,
    }:
    mkDerivation {
      pname = "sbv-program";
      version = "1.1.0.0";
      sha256 = "0bdddln73f27zy4a8j51n82wqpcsziagzviv3vfsq7s990dmkb2g";
      libraryHaskellDepends = [
        base
        bifunctors
        containers
        pretty-simple
        sbv
      ];
      testHaskellDepends = [
        base
        sbv
      ];
      description = "Component-based program synthesis using SBV";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
