# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  SDL = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      SDL,
    }:
    mkDerivation {
      pname = "SDL";
      version = "0.6.7.0";
      sha256 = "00y67v80a8l09i3k76z09lg25kw72ivl09nag8ckdlk4a0cfnzfq";
      enableSeparateDataOutput = true;
      setupHaskellDepends = [
        base
        Cabal
      ];
      libraryHaskellDepends = [ base ];
      librarySystemDepends = [ SDL ];
      description = "Binding to libSDL";
      license = lib.licenses.bsd3;
    }
  ) { inherit (pkgs) SDL; };

}
