# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  search = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      cabal-doctest,
      directory,
      doctest,
      filepath,
      ghc-prim,
      profunctors,
      semigroupoids,
      tagged,
      transformers,
    }:
    mkDerivation {
      pname = "search";
      version = "0.2";
      sha256 = "0xdacs6adcwi3ls8w8dk08yvb9s90ymcdvcm9232wfh263mq13w7";
      setupHaskellDepends = [
        base
        Cabal
        cabal-doctest
      ];
      libraryHaskellDepends = [
        base
        ghc-prim
        profunctors
        semigroupoids
        tagged
        transformers
      ];
      testHaskellDepends = [
        base
        directory
        doctest
        filepath
      ];
      description = "Infinite search in finite time with Hilbert's epsilon";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  search-algorithms = callPackage (
    {
      mkDerivation,
      base,
      containers,
      criterion,
      doctest,
      hspec,
    }:
    mkDerivation {
      pname = "search-algorithms";
      version = "0.3.4";
      sha256 = "1r6nnwb0ry95xqg8psdwgfx6h264kd437a3mr5z7gv7vdarb3r2h";
      libraryHaskellDepends = [
        base
        containers
      ];
      testHaskellDepends = [
        base
        containers
        doctest
        hspec
      ];
      benchmarkHaskellDepends = [
        base
        criterion
      ];
      description = "Common graph search algorithms";
      license = lib.licenses.bsd3;
    }
  ) { };

}
