# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  sec = callPackage (
    {
      mkDerivation,
      base,
      template-haskell,
    }:
    mkDerivation {
      pname = "sec";
      version = "0.0.1";
      sha256 = "1ryl0nm1a37r606xhxy6ykf3c8c1gml6gdqna428w8y3a2vg5q2v";
      libraryHaskellDepends = [
        base
        template-haskell
      ];
      description = "Semantic Editor Combinators";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
