# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  sharc-timbre = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "sharc-timbre";
      version = "0.2";
      sha256 = "1cwzks95jlpa4cd99mz5cz509h7j8k08w53xpvwny1bdb3p1cpsa";
      libraryHaskellDepends = [ base ];
      description = "Sandell Harmonic Archive. A collection of stable phases for all instruments in the orchestra.";
      license = lib.licenses.bsd3;
    }
  ) { };

  shared-buffer = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      QuickCheck,
      test-framework,
      test-framework-quickcheck2,
      unix,
    }:
    mkDerivation {
      pname = "shared-buffer";
      version = "0.2.2";
      sha256 = "031aabqynp5d4k47rjjwyx3xjzh4f1k4csfgdnnhsf45xv5nc3kc";
      libraryHaskellDepends = [
        base
        bytestring
        unix
      ];
      testHaskellDepends = [
        base
        bytestring
        QuickCheck
        test-framework
        test-framework-quickcheck2
        unix
      ];
      description = "A circular buffer built on shared memory";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  shared-fields = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      hspec,
      lens,
      template-haskell,
      text,
    }:
    mkDerivation {
      pname = "shared-fields";
      version = "0.2.0.0";
      sha256 = "107n6w4dn0n4iv7qmfm1d9y04rgj3ab3qc8kyqqddnbnfa44y157";
      libraryHaskellDepends = [
        base
        template-haskell
      ];
      testHaskellDepends = [
        base
        Cabal
        hspec
        lens
        text
      ];
      description = "a tiny library for using shared lens fields";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  shared-memory = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      unix,
    }:
    mkDerivation {
      pname = "shared-memory";
      version = "0.2.0.1";
      sha256 = "04s8m05w5k065lxpjsvd29l1bnig1bqrxvnqdg028vd4w9y5kac1";
      libraryHaskellDepends = [
        base
        unix
      ];
      testHaskellDepends = [
        base
        bytestring
        unix
      ];
      description = "POSIX shared memory";
      license = lib.licenses.mit;
    }
  ) { };

  sharedio = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "sharedio";
      version = "0.1.0";
      sha256 = "08hmmb2nn2lpirdnpp928m6xadzkv8k90x1nycw2b58vp1rpk7zv";
      libraryHaskellDepends = [ base ];
      description = "Bundles shared calls to IO functions to perform them only once";
      license = lib.licenses.mit;
    }
  ) { };

}
