# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  ShellCheck_0_9_0 = callPackage (
    {
      mkDerivation,
      aeson,
      array,
      base,
      bytestring,
      containers,
      deepseq,
      Diff,
      directory,
      fgl,
      filepath,
      mtl,
      parsec,
      process,
      QuickCheck,
      regex-tdfa,
      transformers,
    }:
    mkDerivation {
      pname = "ShellCheck";
      version = "0.9.0";
      sha256 = "071k2gc8rzpg9lwq9g10c9xx0zm1wcgsf8v4n1csj9fm56vy7gmb";
      revision = "2";
      editedCabalFile = "1bc552vfv76jq1zmqywv7a2z322v9ncz3sc69xpj0w6qwb3sd224";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        array
        base
        bytestring
        containers
        deepseq
        Diff
        directory
        fgl
        filepath
        mtl
        parsec
        process
        QuickCheck
        regex-tdfa
        transformers
      ];
      executableHaskellDepends = [
        aeson
        array
        base
        bytestring
        containers
        deepseq
        Diff
        directory
        fgl
        filepath
        mtl
        parsec
        QuickCheck
        regex-tdfa
        transformers
      ];
      testHaskellDepends = [
        aeson
        array
        base
        bytestring
        containers
        deepseq
        Diff
        directory
        fgl
        filepath
        mtl
        parsec
        QuickCheck
        regex-tdfa
        transformers
      ];
      description = "Shell script analysis tool";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "shellcheck";
      maintainers = [ lib.maintainers.zowoq ];
    }
  ) { };

  ShellCheck = callPackage (
    {
      mkDerivation,
      aeson,
      array,
      base,
      bytestring,
      containers,
      deepseq,
      Diff,
      directory,
      fgl,
      filepath,
      mtl,
      parsec,
      process,
      QuickCheck,
      regex-tdfa,
      transformers,
    }:
    mkDerivation {
      pname = "ShellCheck";
      version = "0.11.0";
      sha256 = "003lhhmaqbzvddw2im4ki5vz6v4imd8f5cp470gk122p36f2x9w1";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        array
        base
        bytestring
        containers
        deepseq
        Diff
        directory
        fgl
        filepath
        mtl
        parsec
        process
        QuickCheck
        regex-tdfa
        transformers
      ];
      executableHaskellDepends = [
        aeson
        array
        base
        bytestring
        containers
        deepseq
        Diff
        directory
        fgl
        filepath
        mtl
        parsec
        QuickCheck
        regex-tdfa
        transformers
      ];
      testHaskellDepends = [
        aeson
        array
        base
        bytestring
        containers
        deepseq
        Diff
        directory
        fgl
        filepath
        mtl
        parsec
        QuickCheck
        regex-tdfa
        transformers
      ];
      description = "Shell script analysis tool";
      license = lib.licenses.gpl3Only;
      mainProgram = "shellcheck";
      maintainers = [ lib.maintainers.zowoq ];
    }
  ) { };

  Shellac = callPackage (
    {
      mkDerivation,
      base,
      directory,
      mtl,
      unix,
    }:
    mkDerivation {
      pname = "Shellac";
      version = "0.9.9";
      sha256 = "005793m4njccn28ngbhmi4zp7grf71rmhscy2i5bsy8an4b4wkg6";
      revision = "1";
      editedCabalFile = "1nq7j00vfrhfzkbsgr6j28zr339gx5bcvq6x9mvh9qvs2jmcdz1z";
      libraryHaskellDepends = [
        base
        directory
        mtl
        unix
      ];
      description = "A framework for creating shell envinronments";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  Shellac-compatline = callPackage (
    {
      mkDerivation,
      base,
      Shellac,
      Shellac-readline,
    }:
    mkDerivation {
      pname = "Shellac-compatline";
      version = "0.9.9";
      sha256 = "0qmiadsi8yihvlgdx88y9smw18jzcgpacv5mdipwrv2lrix9hnr5";
      revision = "1";
      editedCabalFile = "0ws8prjzj4j9yf1mqdnvlpv367cx4wfqa5jq5n6x7g9npwmd5ya0";
      libraryHaskellDepends = [
        base
        Shellac
        Shellac-readline
      ];
      description = "\"compatline\" backend module for Shellac";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shellac-editline = callPackage (
    {
      mkDerivation,
      base,
      editline,
      Shellac,
    }:
    mkDerivation {
      pname = "Shellac-editline";
      version = "0.9.9";
      sha256 = "172fd5khxdi1wa3244mziypd7sp0d2wc2wh19w0gzmiqp1d2vqc7";
      revision = "1";
      editedCabalFile = "1wyal7nqnl5sj74d9mid2dw35d37b40v132cg3zhw9ys24k0jl6v";
      libraryHaskellDepends = [
        base
        editline
        Shellac
      ];
      description = "Editline backend module for Shellac";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shellac-haskeline = callPackage (
    {
      mkDerivation,
      base,
      haskeline,
      mtl,
      Shellac,
    }:
    mkDerivation {
      pname = "Shellac-haskeline";
      version = "0.2.1";
      sha256 = "0lhm2j8gl2vk4qasb2d6ips6qnvb4bg0mpb7mczqhahzq3i38sh4";
      libraryHaskellDepends = [
        base
        haskeline
        mtl
        Shellac
      ];
      description = "Haskeline backend module for Shellac";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shellac-readline = callPackage (
    {
      mkDerivation,
      base,
      readline,
      Shellac,
    }:
    mkDerivation {
      pname = "Shellac-readline";
      version = "0.9.9";
      sha256 = "0lc8xf81cz6slyl7djr5kibp96f7fqmqlhlmvv9x5as4k9gbq7rm";
      revision = "1";
      editedCabalFile = "019p7q1nmi2v7rb1rjnch4zaz506c4ry28mkivhkqiq3ay1m86hs";
      libraryHaskellDepends = [
        base
        readline
        Shellac
      ];
      description = "Readline backend module for Shellac";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  shelduck = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-pretty,
      async,
      base,
      bytestring,
      directory,
      exceptions,
      hastache,
      hspec,
      http-client,
      lens,
      lens-aeson,
      mtl,
      random,
      regex-compat,
      shelly,
      Spock,
      stm,
      text,
      time,
      transformers,
      unix,
      unordered-containers,
      uuid,
      wreq,
      yesod,
    }:
    mkDerivation {
      pname = "shelduck";
      version = "0.2.0.0";
      sha256 = "1hgzj9qr90mbhxk0mx8y93jcad7srgxplvkmswxynidfaphvfqry";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        aeson-pretty
        async
        base
        bytestring
        directory
        exceptions
        hastache
        http-client
        lens
        lens-aeson
        mtl
        random
        shelly
        Spock
        stm
        text
        time
        transformers
        unordered-containers
        uuid
        wreq
        yesod
      ];
      executableHaskellDepends = [
        aeson
        aeson-pretty
        async
        base
        bytestring
        directory
        exceptions
        hastache
        http-client
        lens
        lens-aeson
        mtl
        random
        shelly
        Spock
        stm
        text
        time
        transformers
        unix
        unordered-containers
        uuid
        wreq
        yesod
      ];
      testHaskellDepends = [
        aeson
        base
        hspec
        http-client
        lens
        mtl
        regex-compat
        stm
        text
        transformers
        wreq
      ];
      description = "Test webhooks locally";
      license = lib.licenses.asl20;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "shelduck";
    }
  ) { };

  shell-conduit = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      conduit,
      conduit-extra,
      directory,
      filepath,
      hspec,
      hspec-expectations,
      monads-tf,
      process,
      resourcet,
      semigroups,
      split,
      template-haskell,
      text,
      transformers,
      unix,
      unliftio,
    }:
    mkDerivation {
      pname = "shell-conduit";
      version = "5.0.0";
      sha256 = "02zilgrb64x0rk4b4bihprwq9fr5gydzj003y3fq8ryf7r60g41w";
      libraryHaskellDepends = [
        async
        base
        bytestring
        conduit
        conduit-extra
        directory
        filepath
        monads-tf
        process
        resourcet
        semigroups
        split
        template-haskell
        text
        transformers
        unix
        unliftio
      ];
      testHaskellDepends = [
        base
        bytestring
        conduit
        conduit-extra
        hspec
        hspec-expectations
        template-haskell
      ];
      description = "Write shell scripts with Conduit";
      license = lib.licenses.bsd3;
    }
  ) { };

  shell-escape = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      containers,
      vector,
    }:
    mkDerivation {
      pname = "shell-escape";
      version = "0.2.0";
      sha256 = "0jms5hdl8zrpxwypq9998798krspclivprirrcq59r179alrng72";
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
        vector
      ];
      description = "Shell escaping library";
      license = lib.licenses.bsd3;
    }
  ) { };

  shell-monad = callPackage (
    {
      mkDerivation,
      base,
      containers,
      text,
      unix,
    }:
    mkDerivation {
      pname = "shell-monad";
      version = "0.6.10";
      sha256 = "11jl90ajzypgwchmsxw9l3ap3f1xb65zmvsrc3g9wf27bl8m8435";
      libraryHaskellDepends = [
        base
        containers
        text
        unix
      ];
      description = "shell monad";
      license = lib.licenses.bsd3;
    }
  ) { };

  shell-pipe = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "shell-pipe";
      version = "0.1";
      sha256 = "0xyarxm2hs8yypmz8w4zbnjvv5xl9dd657j7j3a82gbghsb93vyy";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [ base ];
      executableHaskellDepends = [ base ];
      description = "Pipe streams through external shell commands";
      license = "GPL";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  shell-utility = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "shell-utility";
      version = "0.1";
      sha256 = "1n15v0avvkxvczmyjc6g4z9axr5c61n8jlpa1cm4xr3qk7spm1mi";
      libraryHaskellDepends = [ base ];
      description = "Utility functions for writing command-line programs";
      license = lib.licenses.bsd3;
      maintainers = [ lib.maintainers.thielema ];
    }
  ) { };

  shellify = callPackage (
    {
      mkDerivation,
      base,
      containers,
      data-default,
      directory,
      extra,
      hspec,
      hspec-core,
      HStringTemplate,
      lens,
      mtl,
      optparse-applicative,
      parsec,
      raw-strings-qq,
      shake,
      text,
      unordered-containers,
    }:
    mkDerivation {
      pname = "shellify";
      version = "0.14.0.2";
      sha256 = "0hv3ggkx00qn62pdgk3paiqmhm6l3ckgw3ajwg43b9xwji5iiz3r";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
        data-default
        directory
        HStringTemplate
        lens
        mtl
        optparse-applicative
        parsec
        raw-strings-qq
        shake
        text
        unordered-containers
      ];
      executableHaskellDepends = [
        base
        optparse-applicative
        raw-strings-qq
        text
      ];
      testHaskellDepends = [
        base
        data-default
        extra
        hspec
        hspec-core
        optparse-applicative
        raw-strings-qq
        text
      ];
      description = "A tool for generating shell.nix files";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
      mainProgram = "nix-shellify";
      maintainers = [ lib.maintainers.danielrolls ];
    }
  ) { };

  shellish = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      directory,
      filepath,
      mtl,
      process,
      strict,
      time,
      unix-compat,
    }:
    mkDerivation {
      pname = "shellish";
      version = "0.1.4";
      sha256 = "1ldwid270mwyky6zmggbvn72hvs4s39hhf2zj8r0jahxnwlpbfan";
      libraryHaskellDepends = [
        base
        bytestring
        directory
        filepath
        mtl
        process
        strict
        time
        unix-compat
      ];
      description = "shell-/perl- like (systems) programming in Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  shellmate = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      directory,
      filepath,
      process,
      temporary,
      transformers,
      unix,
    }:
    mkDerivation {
      pname = "shellmate";
      version = "0.3.4.3";
      sha256 = "1cn3kh5rszyis2pqvh3s35zlchxwyf7vssd8md9z8vgqs6apd49r";
      libraryHaskellDepends = [
        base
        bytestring
        directory
        filepath
        process
        temporary
        transformers
        unix
      ];
      description = "Simple interface for shell scripting in Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  shellmate-extras = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      feed,
      http-conduit,
      http-types,
      mime-types,
      shellmate,
      tagsoup,
      text,
      utf8-string,
      xml,
    }:
    mkDerivation {
      pname = "shellmate-extras";
      version = "0.3.4.3";
      sha256 = "1aqc0bslqwrfr8b9nkk52n3fjw2b91gnn7pzzp24smm1cbm2x50d";
      libraryHaskellDepends = [
        base
        bytestring
        feed
        http-conduit
        http-types
        mime-types
        shellmate
        tagsoup
        text
        utf8-string
        xml
      ];
      description = "Extra functionality for shellmate";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  shellmet = callPackage (
    {
      mkDerivation,
      base,
      doctest,
      Glob,
      markdown-unlit,
      process,
      text,
    }:
    mkDerivation {
      pname = "shellmet";
      version = "0.0.6.0";
      sha256 = "0vxbqpsmd7g3dfkgildzb34vzbz4j1p1ry55910f0jl79dx1w6xj";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        process
        text
      ];
      executableHaskellDepends = [
        base
        text
      ];
      executableToolDepends = [ markdown-unlit ];
      testHaskellDepends = [
        base
        doctest
        Glob
      ];
      description = "Out of the shell solution for scripting in Haskell";
      license = lib.meta.getLicenseFromSpdxId "MPL-2.0";
      mainProgram = "readme";
    }
  ) { };

  shellout = callPackage (
    {
      mkDerivation,
      async,
      base,
      stm,
      text,
      typed-process,
    }:
    mkDerivation {
      pname = "shellout";
      version = "0.1.0.0";
      sha256 = "0cinrxwr4jclx37c3h9r1swkj6l78z7fmja6242z53ai1kjqj9kp";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        async
        base
        stm
        text
        typed-process
      ];
      executableHaskellDepends = [
        async
        base
        stm
        text
        typed-process
      ];
      description = "A threaded manager for Haskell that can run and stream external process output/err/exits";
      license = lib.licenses.bsd3;
      mainProgram = "example";
    }
  ) { };

  shelltestrunner = callPackage (
    {
      mkDerivation,
      base,
      cmdargs,
      Diff,
      directory,
      filemanip,
      filepath,
      hspec,
      hspec-contrib,
      hspec-core,
      HUnit,
      parsec,
      pretty-show,
      process,
      regex-tdfa,
      safe,
      test-framework,
      test-framework-hunit,
      utf8-string,
    }:
    mkDerivation {
      pname = "shelltestrunner";
      version = "1.10";
      sha256 = "1c6bjyxqa4mgnh3w4pqp6sbr5cf160n7jf9i1b4b9sdxzdjk7g87";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        cmdargs
        Diff
        directory
        filemanip
        filepath
        hspec
        hspec-contrib
        hspec-core
        HUnit
        parsec
        pretty-show
        process
        regex-tdfa
        safe
        test-framework
        test-framework-hunit
        utf8-string
      ];
      description = "Easy, repeatable testing of CLI programs/commands";
      license = "GPL";
      mainProgram = "shelltest";
    }
  ) { };

  shelltestrunner_1_11 = callPackage (
    {
      mkDerivation,
      base,
      cmdargs,
      Diff,
      directory,
      filemanip,
      filepath,
      hspec,
      hspec-contrib,
      hspec-core,
      HUnit,
      parsec,
      pretty-show,
      process,
      regex-tdfa,
      safe,
      test-framework,
      test-framework-hunit,
      utf8-string,
    }:
    mkDerivation {
      pname = "shelltestrunner";
      version = "1.11";
      sha256 = "0ka1scq321dxdxqap2laph2c98s8323z2yd8zabl20v20a62yx5i";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        cmdargs
        Diff
        directory
        filemanip
        filepath
        hspec
        hspec-contrib
        hspec-core
        HUnit
        parsec
        pretty-show
        process
        regex-tdfa
        safe
        test-framework
        test-framework-hunit
        utf8-string
      ];
      description = "Easy, repeatable testing of CLI programs/commands";
      license = lib.meta.getLicenseFromSpdxId "GPL-3.0-or-later";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "shelltest";
    }
  ) { };

  shellwords = callPackage (
    {
      mkDerivation,
      base,
      hspec,
      hspec-discover,
      megaparsec,
      text,
    }:
    mkDerivation {
      pname = "shellwords";
      version = "0.1.4.6";
      sha256 = "00jadd023d3c03d9l69i2dif8zw7x9pdjfxwr2923sv7pc03pqd8";
      libraryHaskellDepends = [
        base
        megaparsec
        text
      ];
      testHaskellDepends = [
        base
        hspec
        megaparsec
      ];
      testToolDepends = [ hspec-discover ];
      description = "Parse strings into words, like a shell would";
      license = lib.licenses.mit;
    }
  ) { };

  shelly = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      containers,
      directory,
      enclosed-exceptions,
      exceptions,
      filepath,
      hspec,
      hspec-contrib,
      HUnit,
      lifted-async,
      lifted-base,
      monad-control,
      mtl,
      process,
      text,
      time,
      transformers,
      transformers-base,
      unix-compat,
    }:
    mkDerivation {
      pname = "shelly";
      version = "1.12.1.1";
      sha256 = "16fy3mgky92w85g4vhnl3xf9bxjil3kc2vh85qy85jg2kz5mw208";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        async
        base
        bytestring
        containers
        directory
        enclosed-exceptions
        exceptions
        filepath
        lifted-base
        monad-control
        mtl
        process
        text
        time
        transformers
        transformers-base
        unix-compat
      ];
      testHaskellDepends = [
        base
        bytestring
        directory
        filepath
        hspec
        hspec-contrib
        HUnit
        lifted-async
        mtl
        text
        transformers
        unix-compat
      ];
      description = "shell-like (systems) programming in Haskell";
      license = lib.licenses.bsd3;
    }
  ) { };

  shelly-extra = callPackage (
    {
      mkDerivation,
      async,
      base,
      hspec,
      HUnit,
      mtl,
      SafeSemaphore,
      shelly,
      text,
    }:
    mkDerivation {
      pname = "shelly-extra";
      version = "0.3.0.2";
      sha256 = "0ijlmqcxlxrxmiyvz2kqscmyr9fhfcpxfj56g6grvc8gm4w9rlqr";
      libraryHaskellDepends = [
        async
        base
        mtl
        SafeSemaphore
        shelly
      ];
      testHaskellDepends = [
        async
        base
        hspec
        HUnit
        mtl
        SafeSemaphore
        shelly
        text
      ];
      description = "shelly features that require extra dependencies";
      license = lib.licenses.bsd3;
    }
  ) { };

}
