# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Shpadoinkle = callPackage (
    {
      mkDerivation,
      base,
      containers,
      deepseq,
      ghcjs-dom,
      jsaddle,
      jsaddle-warp,
      mtl,
      text,
      transformers,
      unliftio,
      wai,
      wai-app-static,
      warp,
    }:
    mkDerivation {
      pname = "Shpadoinkle";
      version = "0.3.2.0";
      sha256 = "1an13ybgayp532vx040bhjccg3kb429zrcrhc38bkvbs6475y3bz";
      libraryHaskellDepends = [
        base
        containers
        deepseq
        ghcjs-dom
        jsaddle
        jsaddle-warp
        mtl
        text
        transformers
        unliftio
        wai
        wai-app-static
        warp
      ];
      description = "A programming model for declarative, high performance user interface";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  Shpadoinkle-backend-pardiff = callPackage (
    {
      mkDerivation,
      base,
      compactable,
      containers,
      exceptions,
      file-embed,
      ghcjs-dom,
      jsaddle,
      monad-control,
      mtl,
      random,
      Shpadoinkle,
      text,
      transformers-base,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-backend-pardiff";
      version = "0.3.0.1";
      sha256 = "1ghj2464pq36paf3z56hc7q0p2nkfgwqjvfa3yymwfr2xdachqwd";
      libraryHaskellDepends = [
        base
        compactable
        containers
        exceptions
        file-embed
        ghcjs-dom
        jsaddle
        monad-control
        mtl
        random
        Shpadoinkle
        text
        transformers-base
        unliftio
      ];
      description = "A Virtual Dom in pure Haskell, based on Html as an Alignable Functor";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-backend-snabbdom = callPackage (
    {
      mkDerivation,
      base,
      containers,
      exceptions,
      file-embed,
      ghcjs-dom,
      jsaddle,
      monad-control,
      mtl,
      Shpadoinkle,
      text,
      transformers-base,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-backend-snabbdom";
      version = "0.3.0.2";
      sha256 = "1hqbfsjlvrkfjf16r5f1jr7fxbki559mbxksqviba80b94wn34ld";
      libraryHaskellDepends = [
        base
        containers
        exceptions
        file-embed
        ghcjs-dom
        jsaddle
        monad-control
        mtl
        Shpadoinkle
        text
        transformers-base
        unliftio
      ];
      description = "Use the high-performance Snabbdom virtual dom library written in JavaScript";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-backend-static = callPackage (
    {
      mkDerivation,
      base,
      compactable,
      Shpadoinkle,
      text,
    }:
    mkDerivation {
      pname = "Shpadoinkle-backend-static";
      version = "0.2.0.1";
      sha256 = "1lcly4kb6im7m1y25209s7wxdvisc0nyfa33a3fjf078ambqpai1";
      libraryHaskellDepends = [
        base
        compactable
        Shpadoinkle
        text
      ];
      description = "A backend for rendering Shpadoinkle as Text";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-console = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      jsaddle,
      lens,
      text,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-console";
      version = "0.0.1.4";
      sha256 = "1agvyr8785y9dmhdcm36mhvg3lq2ksqly38asb7pb8xynhlvllbk";
      libraryHaskellDepends = [
        aeson
        base
        jsaddle
        lens
        text
        unliftio
      ];
      description = "Support for the native browser console";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  Shpadoinkle-debug = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      jsaddle,
      lens,
      text,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-debug";
      version = "0.0.0.1";
      sha256 = "1yvr3d40aa6sl3gpyr24a5hij63jm2p0jrx0kac7asjihvd6fk2g";
      libraryHaskellDepends = [
        aeson
        base
        jsaddle
        lens
        text
        unliftio
      ];
      description = "Debugging tools for Shpadoinkle applications";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  Shpadoinkle-developer-tools = callPackage (
    {
      mkDerivation,
      base,
      containers,
      jsaddle,
      lens,
      pretty-show,
      Shpadoinkle,
      Shpadoinkle-backend-pardiff,
      Shpadoinkle-html,
      stm,
      text,
      time,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-developer-tools";
      version = "0.0.0.2";
      sha256 = "1lcz9xlqxzzv8gq31jcd1lw5l8dw14ixkcg14kq73p0418lwm06z";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
        jsaddle
        lens
        pretty-show
        Shpadoinkle
        Shpadoinkle-backend-pardiff
        Shpadoinkle-html
        stm
        text
        time
        unliftio
      ];
      executableHaskellDepends = [
        base
        containers
        jsaddle
        lens
        pretty-show
        Shpadoinkle
        Shpadoinkle-backend-pardiff
        Shpadoinkle-html
        stm
        text
        time
        unliftio
      ];
      description = "Chrome extension to aide in development";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "devtools";
    }
  ) { };

  Shpadoinkle-disembodied = callPackage (
    {
      mkDerivation,
      base,
      directory,
      filepath,
      servant,
      Shpadoinkle,
      Shpadoinkle-backend-static,
      Shpadoinkle-html,
      Shpadoinkle-router,
      text,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-disembodied";
      version = "0.0.0.2";
      sha256 = "1r96j6lx5k28m0wc4x0pdf81zzml6ppdaw5ywdlv85yxcmv1wxsd";
      libraryHaskellDepends = [
        base
        directory
        filepath
        servant
        Shpadoinkle
        Shpadoinkle-backend-static
        Shpadoinkle-html
        Shpadoinkle-router
        text
        unliftio
      ];
      description = "Shpadoinkle as a static site";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-examples = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      beam-core,
      beam-sqlite,
      bytestring,
      containers,
      ease,
      exceptions,
      file-embed,
      generic-lens,
      generic-monoid,
      ghcjs-dom,
      jsaddle,
      lens,
      mtl,
      optparse-applicative,
      pretty-show,
      safe,
      servant,
      servant-client,
      servant-server,
      Shpadoinkle,
      Shpadoinkle-backend-pardiff,
      Shpadoinkle-backend-snabbdom,
      Shpadoinkle-backend-static,
      Shpadoinkle-console,
      Shpadoinkle-html,
      Shpadoinkle-lens,
      Shpadoinkle-router,
      Shpadoinkle-widgets,
      split,
      sqlite-simple,
      stm,
      text,
      unliftio,
      wai,
      wai-app-static,
      warp,
    }:
    mkDerivation {
      pname = "Shpadoinkle-examples";
      version = "0.0.0.3";
      sha256 = "1ym3wnqqj07v0w07af6z9yiccx95bbljna36z37pz8gp35dxamlh";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        aeson
        base
        beam-core
        beam-sqlite
        bytestring
        containers
        ease
        exceptions
        file-embed
        generic-lens
        generic-monoid
        ghcjs-dom
        jsaddle
        lens
        mtl
        optparse-applicative
        pretty-show
        safe
        servant
        servant-client
        servant-server
        Shpadoinkle
        Shpadoinkle-backend-pardiff
        Shpadoinkle-backend-snabbdom
        Shpadoinkle-backend-static
        Shpadoinkle-console
        Shpadoinkle-html
        Shpadoinkle-lens
        Shpadoinkle-router
        Shpadoinkle-widgets
        split
        sqlite-simple
        stm
        text
        unliftio
        wai
        wai-app-static
        warp
      ];
      description = "Example usages of Shpadoinkle";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-html = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      compactable,
      containers,
      directory,
      ghcjs-dom,
      jsaddle,
      lens,
      process,
      raw-strings-qq,
      regex-pcre,
      Shpadoinkle,
      stm,
      template-haskell,
      text,
      time,
      transformers,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-html";
      version = "0.3.0.2";
      sha256 = "1wi1b4vnag530iz8xzqih1phwgpr96yv3brizmn6yj9j8d0bf5qz";
      libraryHaskellDepends = [
        base
        bytestring
        compactable
        containers
        directory
        ghcjs-dom
        jsaddle
        lens
        process
        raw-strings-qq
        regex-pcre
        Shpadoinkle
        stm
        template-haskell
        text
        time
        transformers
        unliftio
      ];
      description = "A typed, template generated Html DSL, and helpers";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-isreal = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      containers,
      deepseq,
      directory,
      filepath,
      process,
      random,
      servant,
      servant-server,
      text,
      time,
      warp,
    }:
    mkDerivation {
      pname = "Shpadoinkle-isreal";
      version = "0.0.0.2";
      sha256 = "1mvc5q5rvsgvgind9pv7389908ikb80qa704vwrzqb2wg2ir5g78";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        containers
        deepseq
        random
        servant
        servant-server
        text
        time
      ];
      executableHaskellDepends = [
        aeson
        base
        bytestring
        containers
        deepseq
        directory
        filepath
        process
        random
        servant
        servant-server
        text
        time
        warp
      ];
      description = "Isreal Swan will make a snowman for you!";
      license = lib.meta.getLicenseFromSpdxId "GPL-3.0-or-later";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "isreal";
      broken = true;
    }
  ) { };

  Shpadoinkle-lens = callPackage (
    {
      mkDerivation,
      base,
      lens,
      Shpadoinkle,
      text,
    }:
    mkDerivation {
      pname = "Shpadoinkle-lens";
      version = "0.0.0.4";
      sha256 = "16lkkyjlxczdcdb8wwj4jvkhi9wsr9d9h5ih6kjdxd9r2qn4zi84";
      libraryHaskellDepends = [
        base
        lens
        Shpadoinkle
        text
      ];
      description = "Lens combinators for Shpadoinkle applications";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-router = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      compactable,
      exceptions,
      ghcjs-dom,
      http-api-data,
      http-media,
      http-types,
      jsaddle,
      jsaddle-warp,
      lens,
      network-uri,
      servant,
      servant-client,
      servant-client-js,
      servant-rawm,
      servant-rawm-server,
      servant-server,
      Shpadoinkle,
      Shpadoinkle-backend-static,
      text,
      unliftio,
      wai,
      wai-app-static,
      warp,
    }:
    mkDerivation {
      pname = "Shpadoinkle-router";
      version = "0.3.0.1";
      sha256 = "0xy09nklsjypaw2dmzl4dzdkrhdlzip2jw41mj1vm7xdvas7i7f1";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        compactable
        exceptions
        ghcjs-dom
        http-api-data
        http-media
        http-types
        jsaddle
        jsaddle-warp
        lens
        network-uri
        servant
        servant-client
        servant-client-js
        servant-rawm
        servant-rawm-server
        servant-server
        Shpadoinkle
        Shpadoinkle-backend-static
        text
        unliftio
        wai
        wai-app-static
        warp
      ];
      description = "A single page application rounter for Shpadoinkle based on Servant";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-streaming = callPackage (
    {
      mkDerivation,
      base,
      lens,
      Shpadoinkle,
      streaming,
      text,
    }:
    mkDerivation {
      pname = "Shpadoinkle-streaming";
      version = "0.0.0.2";
      sha256 = "1i86299ss25xd1swxd4rz9k5mvxqzhnafiylaawan2fbp2xwqkq2";
      libraryHaskellDepends = [
        base
        lens
        Shpadoinkle
        streaming
        text
      ];
      description = "Integration of the streaming library with Shpadoinkle continuations";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-template = callPackage (
    {
      mkDerivation,
      base,
      directory,
      file-embed,
      html-entities,
      html-parse,
      process,
      Shpadoinkle,
      Shpadoinkle-backend-static,
      template-haskell,
      text,
    }:
    mkDerivation {
      pname = "Shpadoinkle-template";
      version = "0.0.0.2";
      sha256 = "1alhlc4w9xcyzan0sbsanip3q0yw9pjg094linwwavb211wbcdkj";
      libraryHaskellDepends = [
        base
        directory
        html-entities
        html-parse
        process
        Shpadoinkle
        Shpadoinkle-backend-static
        template-haskell
        text
      ];
      testHaskellDepends = [
        base
        directory
        file-embed
        html-entities
        html-parse
        process
        Shpadoinkle
        Shpadoinkle-backend-static
        template-haskell
        text
      ];
      description = "Read standard file formats into Shpadoinkle with Template Haskell";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  Shpadoinkle-widgets = callPackage (
    {
      mkDerivation,
      aeson,
      attoparsec,
      base,
      bytestring,
      compactable,
      containers,
      edit-distance,
      either,
      email-validate,
      hspec,
      jsaddle,
      mtl,
      QuickCheck,
      quickcheck-classes,
      quickcheck-classes-base,
      servant,
      Shpadoinkle,
      Shpadoinkle-html,
      stm,
      template-haskell,
      text,
      transformers,
      unliftio,
    }:
    mkDerivation {
      pname = "Shpadoinkle-widgets";
      version = "0.2.0.1";
      sha256 = "11ncdip5f01d8ng1rgpprl0adrgca19mww86hybckg8v9lxvyfgc";
      libraryHaskellDepends = [
        aeson
        attoparsec
        base
        bytestring
        compactable
        containers
        edit-distance
        either
        email-validate
        jsaddle
        mtl
        servant
        Shpadoinkle
        Shpadoinkle-html
        stm
        template-haskell
        text
        transformers
        unliftio
      ];
      testHaskellDepends = [
        base
        containers
        hspec
        QuickCheck
        quickcheck-classes
        quickcheck-classes-base
      ];
      description = "A collection of common reusable types and components";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
