# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  smt-lib = callPackage (
    {
      mkDerivation,
      array,
      base,
      directory,
      polyparse,
    }:
    mkDerivation {
      pname = "smt-lib";
      version = "0.0.2";
      sha256 = "1phm50pabahrpxrzp25mfhpafzhp4hz8cxp6fp93rwh4cl7cckky";
      libraryHaskellDepends = [
        array
        base
        directory
        polyparse
      ];
      description = "Parsing and printing SMT-LIB";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
