# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  sshd-lint = callPackage (
    {
      mkDerivation,
      base,
      containers,
      hspec,
      keyword-args,
      nagios-check,
      parsec,
    }:
    mkDerivation {
      pname = "sshd-lint";
      version = "0.1.0.1";
      sha256 = "0q34zx8cn0gs91c4x4bicmygfaary5kk42ib62jk0hlrh3rzdi7c";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        base
        containers
        keyword-args
        nagios-check
        parsec
      ];
      testHaskellDepends = [
        base
        containers
        hspec
        keyword-args
        nagios-check
        parsec
      ];
      description = "Check sshd configuration for adherence to best practices";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "sshd-lint";
    }
  ) { };

}
