# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  stp = callPackage (
    {
      mkDerivation,
      base,
      containers,
      regex-compat,
    }:
    mkDerivation {
      pname = "stp";
      version = "0.1.0.1";
      sha256 = "1vg2w6iawqydg2n4k6m6pzfxr7sr10cx33aabyx6b9wp1i8xa5kl";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
      ];
      executableHaskellDepends = [
        base
        regex-compat
      ];
      description = "Simple Theorem Prover";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "mu-test";
      broken = true;
    }
  ) { };

}
