# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  svgsym = callPackage (
    {
      mkDerivation,
      array,
      base,
      bytestring,
      containers,
      directory,
      filepath,
      filepattern,
      optparse-applicative,
      regex-base,
      regex-tdfa,
      xml,
    }:
    mkDerivation {
      pname = "svgsym";
      version = "0.1.2.0";
      sha256 = "0b3m0acvypn58h566dhbpyjywka2saccfs0l7rp2nyvd9b51skk6";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        array
        base
        bytestring
        containers
        directory
        filepath
        filepattern
        optparse-applicative
        regex-base
        regex-tdfa
        xml
      ];
      description = "A tool to prune unused symbols from icon SVG files";
      license = lib.meta.getLicenseFromSpdxId "GPL-3.0-or-later";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "svgsym";
      broken = true;
    }
  ) { };

}
