# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  taglib = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      taglib,
      utf8-string,
    }:
    mkDerivation {
      pname = "taglib";
      version = "0.1.1";
      sha256 = "16qyfy8rxaab0q9j2v00h4j5d3la95acfhmp32x1hdxz1rwr6zfp";
      libraryHaskellDepends = [
        base
        bytestring
        utf8-string
      ];
      librarySystemDepends = [ taglib ];
      libraryPkgconfigDepends = [ taglib ];
      description = "Binding to TagLib (ID3 tag library)";
      license = "LGPL";
    }
  ) { inherit (pkgs) taglib; };

  taglib-api = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      mtl,
      taglib,
      text,
      transformers,
    }:
    mkDerivation {
      pname = "taglib-api";
      version = "0.1.1.3";
      sha256 = "1ahbwi28yjigbkgfv52iaaqalmmlc4d09fa65l0yczxrs7rzchmj";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        mtl
        text
        transformers
      ];
      libraryPkgconfigDepends = [ taglib ];
      description = "An FFI layer over TagLib's C bindings";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { inherit (pkgs) taglib; };

}
