# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  TBit = callPackage (
    {
      mkDerivation,
      base,
      containers,
      deepseq,
      fgl,
      free,
      hmatrix,
      integration,
      list-extras,
      mtl,
      numeric-tools,
      parallel,
    }:
    mkDerivation {
      pname = "TBit";
      version = "0.4.2.3";
      sha256 = "1by1wy2w3ankg1php7m911kc53q2dv5jfl8v1iwp3mb68s8b6wrs";
      libraryHaskellDepends = [
        base
        containers
        deepseq
        fgl
        free
        hmatrix
        integration
        list-extras
        mtl
        numeric-tools
        parallel
      ];
      description = "Utilities for condensed matter physics tight binding calculations";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
