# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  tpdb = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      data-default,
      exceptions,
      filepath,
      hashable,
      mtl,
      parsec,
      pretty,
      prettyprinter,
      text,
      time,
      xml-conduit,
      xml-hamlet,
    }:
    mkDerivation {
      pname = "tpdb";
      version = "2.8.6";
      sha256 = "0gxjxlwbdbwlygw0n8rd00564vp96jgasf49s6rkm4pgi3hzh1m8";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        containers
        data-default
        exceptions
        filepath
        hashable
        mtl
        parsec
        prettyprinter
        text
        time
        xml-conduit
        xml-hamlet
      ];
      executableHaskellDepends = [
        base
        bytestring
      ];
      testHaskellDepends = [
        base
        pretty
        text
      ];
      description = "Data Type for Rewriting Systems";
      license = lib.meta.getLicenseFromSpdxId "GPL-3.0-only";
    }
  ) { };

}
