# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  turtle = callPackage (
    {
      mkDerivation,
      ansi-wl-pprint,
      async,
      base,
      bytestring,
      clock,
      containers,
      directory,
      doctest,
      exceptions,
      filepath,
      foldl,
      hostname,
      managed,
      optional-args,
      optparse-applicative,
      process,
      stm,
      streaming-commons,
      tasty,
      tasty-bench,
      tasty-hunit,
      temporary,
      text,
      time,
      transformers,
      unix,
      unix-compat,
    }:
    mkDerivation {
      pname = "turtle";
      version = "1.6.2";
      sha256 = "0bav7b2ghbwdhpa4b5a7812psr6hqk7wydvgxjy5dsb62nqnc08s";
      revision = "3";
      editedCabalFile = "19i3n3hd2a0rkdz1ikwdgwhg4ds5pcfah25vgk0jnmwf71h0qwbm";
      libraryHaskellDepends = [
        ansi-wl-pprint
        async
        base
        bytestring
        clock
        containers
        directory
        exceptions
        filepath
        foldl
        hostname
        managed
        optional-args
        optparse-applicative
        process
        stm
        streaming-commons
        temporary
        text
        time
        transformers
        unix
        unix-compat
      ];
      testHaskellDepends = [
        base
        doctest
        filepath
        tasty
        tasty-hunit
        temporary
      ];
      benchmarkHaskellDepends = [
        base
        tasty-bench
        text
      ];
      description = "Shell programming, Haskell-style";
      license = lib.licenses.bsd3;
      maintainers = [ lib.maintainers.Gabriella439 ];
    }
  ) { };

  turtle-options = callPackage (
    {
      mkDerivation,
      base,
      HUnit,
      optional-args,
      parsec,
      text,
      turtle,
    }:
    mkDerivation {
      pname = "turtle-options";
      version = "0.1.0.4";
      sha256 = "1khsslhy5s0q10djlrlz5xqgwak8kq26yay14xw3k4xwq05npiy2";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        optional-args
        parsec
        text
        turtle
      ];
      executableHaskellDepends = [
        base
        turtle
      ];
      testHaskellDepends = [
        base
        HUnit
        parsec
      ];
      description = "Collection of command line options and parsers for these options";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "example";
      broken = true;
    }
  ) { };

}
