# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  twirl = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      file-embed,
      linear,
      mtl,
      pretty-simple,
      sdl2,
      sdl2-image,
      sdl2-mixer,
      sdl2-ttf,
      text,
      time,
      transformers,
      vector,
    }:
    mkDerivation {
      pname = "twirl";
      version = "0.4.0.4";
      sha256 = "034sx3j2zqbf10w18c013any17pbn07sydn4r5s5s3lj5wg7g6ik";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        containers
        file-embed
        linear
        mtl
        pretty-simple
        sdl2
        sdl2-image
        sdl2-mixer
        sdl2-ttf
        text
        time
        transformers
        vector
      ];
      executableHaskellDepends = [
        base
        bytestring
        containers
        file-embed
        linear
        mtl
        pretty-simple
        sdl2
        sdl2-image
        sdl2-mixer
        sdl2-ttf
        text
        time
        transformers
        vector
      ];
      description = "Simple 2D Game Engine";
      license = lib.meta.getLicenseFromSpdxId "Zlib";
      badPlatforms = lib.platforms.darwin;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "example";
    }
  ) { };

  twirp = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      http-media,
      http-types,
      proto-lens,
      proto-lens-jsonpb,
      proto-lens-runtime,
      servant,
      text,
      wai,
    }:
    mkDerivation {
      pname = "twirp";
      version = "0.2.2.0";
      sha256 = "1n69f1pwcw0ig7j92yi94hh50c5jyn03bc7y5gybw2ajz412iz2h";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        http-media
        http-types
        proto-lens
        proto-lens-jsonpb
        proto-lens-runtime
        servant
        text
        wai
      ];
      testHaskellDepends = [
        aeson
        base
        bytestring
        http-media
        http-types
        proto-lens
        proto-lens-jsonpb
        proto-lens-runtime
        servant
        text
        wai
      ];
      description = "Haskell twirp foundations";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
