# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Twofish = callPackage (
    {
      mkDerivation,
      array,
      base,
      binary,
      bytestring,
      cereal,
      crypto-api,
      HUnit,
      largeword,
      mtl,
      tagged,
    }:
    mkDerivation {
      pname = "Twofish";
      version = "0.3.2";
      sha256 = "1bv79582fxwgk255fhss6k8irb7mlbdvlvvx8jyzs16g3fyw1y5a";
      libraryHaskellDepends = [
        array
        base
        binary
        bytestring
        cereal
        crypto-api
        largeword
        mtl
        tagged
      ];
      testHaskellDepends = [
        array
        base
        binary
        bytestring
        cereal
        crypto-api
        HUnit
        largeword
        tagged
      ];
      description = "An implementation of the Twofish Symmetric-key cipher";
      license = lib.licenses.bsd3;
    }
  ) { };

}
