# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  txt-sushi = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      containers,
      directory,
      parsec,
      regex-posix,
    }:
    mkDerivation {
      pname = "txt-sushi";
      version = "0.6.0";
      sha256 = "0375q8qcirkalz6n48rkylkx1j8z5gvjhh8n2fdvvjqvn064q1s6";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        binary
        bytestring
        containers
        directory
        parsec
        regex-posix
      ];
      description = "The SQL link in your *NIX chain";
      license = lib.licenses.bsd3;
    }
  ) { };

}
