# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  udev = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      posix-paths,
      systemd,
      unix,
    }:
    mkDerivation {
      pname = "udev";
      version = "0.1.1.0";
      sha256 = "1sb0bdi221gr58cv2b24izs02wd28fr4jijsbpw8r5gzia2j4wf0";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        posix-paths
        unix
      ];
      libraryPkgconfigDepends = [ systemd ];
      description = "libudev bindings";
      license = lib.licenses.bsd3;
      platforms = lib.platforms.linux;
    }
  ) { inherit (pkgs) systemd; };

}
