# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  unfoldable = callPackage (
    {
      mkDerivation,
      base,
      containers,
      one-liner,
      QuickCheck,
      random,
      transformers,
    }:
    mkDerivation {
      pname = "unfoldable";
      version = "1.1";
      sha256 = "0dabyhn3cl1pix2g554jql33n2lpq18lf09r56dqnar01pygmfdv";
      revision = "3";
      editedCabalFile = "1g38gq83gzhbgaxiv4f1j1yil6ascqx8bx37fk9d6g2mcl91qrmc";
      libraryHaskellDepends = [
        base
        containers
        one-liner
        QuickCheck
        random
        transformers
      ];
      description = "Class of data structures that can be unfolded";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  unfoldable-restricted = callPackage (
    {
      mkDerivation,
      base,
      constraints,
      containers,
      hashable,
      transformers,
      unfoldable,
      unit-constraint,
      unordered-containers,
    }:
    mkDerivation {
      pname = "unfoldable-restricted";
      version = "0.0.3";
      sha256 = "0vl3qw6sjprsxadbf70md2njm9jvwwmz6qrqi3rifdj535vjh68b";
      libraryHaskellDepends = [
        base
        constraints
        containers
        hashable
        transformers
        unfoldable
        unit-constraint
        unordered-containers
      ];
      description = "An alternative to the Unfoldable typeclass";
      license = lib.licenses.bsd3;
    }
  ) { };

  unfork = callPackage (
    {
      mkDerivation,
      async,
      base,
      safe-exceptions,
      stm,
    }:
    mkDerivation {
      pname = "unfork";
      version = "1.0.0.2";
      sha256 = "1amshm2cybg4wqbydxnpgvgmd7hi5kss061q9d1l4767kmiwzi7z";
      libraryHaskellDepends = [
        async
        base
        safe-exceptions
        stm
      ];
      description = "Make any action thread safe";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
