# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  Verba = callPackage (
    {
      mkDerivation,
      base,
      containers,
      matrix,
    }:
    mkDerivation {
      pname = "Verba";
      version = "0.1.2.0";
      sha256 = "1fig9zxxisd51v5vzcsapsp4qygikhwhpjzyagw7a3x6kv5qpipm";
      isLibrary = false;
      isExecutable = true;
      enableSeparateDataOutput = true;
      executableHaskellDepends = [
        base
        containers
        matrix
      ];
      description = "A solver for the WordBrain game";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "Verba";
      broken = true;
    }
  ) { };

  verbalexpressions = callPackage (
    {
      mkDerivation,
      base,
      regex-pcre,
    }:
    mkDerivation {
      pname = "verbalexpressions";
      version = "1.0.0.0";
      sha256 = "0wai72bqb1vp4p7ml1yj2jdmkjglihai9vhmgj7ri6y2qgzkpwly";
      libraryHaskellDepends = [
        base
        regex-pcre
      ];
      description = "Regular expressions made easy";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  verbosity = callPackage (
    {
      mkDerivation,
      base,
      binary,
      deepseq,
      dhall,
      generic-lens,
      serialise,
    }:
    mkDerivation {
      pname = "verbosity";
      version = "0.4.0.0";
      sha256 = "1h2vgy3ai3rxh76zi68yi5n5qmj0kyjm0sjg2m1gf9nr4z47afjx";
      libraryHaskellDepends = [
        base
        binary
        deepseq
        dhall
        generic-lens
        serialise
      ];
      description = "Simple enum that encodes application verbosity";
      license = lib.licenses.bsd3;
    }
  ) { };

}
