# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  wai-accept-language = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      file-embed,
      http-types,
      text,
      wai,
      wai-app-static,
      wai-extra,
      warp,
      word8,
    }:
    mkDerivation {
      pname = "wai-accept-language";
      version = "0.1.0.1";
      sha256 = "0caa1944dhcd8k5p079608g5m0h6304mhzayy33a1psyqklz7lyh";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        text
        wai
        wai-extra
        word8
      ];
      executableHaskellDepends = [
        base
        file-embed
        wai
        wai-app-static
        warp
      ];
      description = "Rewrite based on Accept-Language header";
      license = lib.licenses.bsd3;
      mainProgram = "wai-accept-language-exe";
    }
  ) { };

  wai-app-file-cgi = callPackage (
    {
      mkDerivation,
      array,
      attoparsec,
      base,
      bytestring,
      case-insensitive,
      conduit,
      conduit-extra,
      containers,
      directory,
      filepath,
      hspec,
      HTTP,
      http-client,
      http-conduit,
      http-date,
      http-types,
      mime-types,
      network,
      process,
      sockaddr,
      static-hash,
      text,
      transformers,
      unix,
      wai,
      wai-conduit,
      warp,
      word8,
    }:
    mkDerivation {
      pname = "wai-app-file-cgi";
      version = "3.1.12";
      sha256 = "0h1j6zz3l098jhrb42s6hdzxmr2qcksl27w5ghzxrvzwnl12j7fa";
      libraryHaskellDepends = [
        array
        attoparsec
        base
        bytestring
        case-insensitive
        conduit
        conduit-extra
        containers
        directory
        filepath
        http-client
        http-conduit
        http-date
        http-types
        mime-types
        network
        process
        sockaddr
        static-hash
        text
        transformers
        unix
        wai
        wai-conduit
        warp
        word8
      ];
      testHaskellDepends = [
        base
        bytestring
        conduit
        conduit-extra
        directory
        filepath
        hspec
        HTTP
        http-types
        unix
        wai
        warp
      ];
      description = "File/CGI/Rev Proxy App of WAI";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-app-static = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      blaze-html,
      blaze-markup,
      bytestring,
      containers,
      cryptohash-md5,
      directory,
      file-embed,
      filepath,
      hspec,
      http-date,
      http-types,
      mime-types,
      mockery,
      old-locale,
      optparse-applicative,
      template-haskell,
      temporary,
      text,
      time,
      transformers,
      unix-compat,
      unordered-containers,
      wai,
      wai-extra,
      warp,
      zlib,
    }:
    mkDerivation {
      pname = "wai-app-static";
      version = "3.1.9.1";
      sha256 = "0b5wlgl424rwlr68xdrj30jrw0x1gj3101xcf38b1flwl2ki7f0b";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        base64-bytestring
        blaze-html
        blaze-markup
        bytestring
        containers
        cryptohash-md5
        directory
        file-embed
        filepath
        http-date
        http-types
        mime-types
        old-locale
        optparse-applicative
        template-haskell
        text
        time
        transformers
        unix-compat
        unordered-containers
        wai
        wai-extra
        warp
        zlib
      ];
      executableHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        bytestring
        filepath
        hspec
        http-date
        http-types
        mime-types
        mockery
        temporary
        text
        transformers
        unix-compat
        wai
        wai-extra
        zlib
      ];
      description = "WAI application for static serving";
      license = lib.licenses.mit;
      mainProgram = "warp";
    }
  ) { };

  wai-app-static_3_2_1 = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      blaze-html,
      blaze-markup,
      bytestring,
      containers,
      cryptohash-md5,
      directory,
      file-embed,
      filepath,
      hspec,
      http-date,
      http-types,
      mime-types,
      mockery,
      old-locale,
      optparse-applicative,
      template-haskell,
      temporary,
      text,
      time,
      transformers,
      unix-compat,
      unordered-containers,
      wai,
      wai-extra,
      warp,
      zlib,
    }:
    mkDerivation {
      pname = "wai-app-static";
      version = "3.2.1";
      sha256 = "0x040ikyrwjiik1lds5q2bpaya3a8kfvyij0kjjljf0bdfl2dyr7";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        base64-bytestring
        blaze-html
        blaze-markup
        bytestring
        containers
        cryptohash-md5
        directory
        file-embed
        filepath
        http-date
        http-types
        mime-types
        old-locale
        optparse-applicative
        template-haskell
        text
        time
        transformers
        unix-compat
        unordered-containers
        wai
        wai-extra
        warp
        zlib
      ];
      executableHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        bytestring
        filepath
        hspec
        http-date
        http-types
        mime-types
        mockery
        temporary
        text
        transformers
        unix-compat
        wai
        wai-extra
        zlib
      ];
      description = "WAI application for static serving";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "warp";
    }
  ) { };

  wai-cli = callPackage (
    {
      mkDerivation,
      ansi-terminal,
      base,
      http-types,
      iproute,
      monads-tf,
      network,
      options,
      stm,
      streaming-commons,
      transformers,
      unix,
      wai,
      wai-extra,
      warp,
      warp-tls,
    }:
    mkDerivation {
      pname = "wai-cli";
      version = "0.2.3";
      sha256 = "0fflvxfc9ibkrrgqdsr89gl77b0b706a8g7ylydaqqz6z089qbi3";
      revision = "2";
      editedCabalFile = "1dv6lvfrsjpg733ssxgxghlfddqmnm8h2lp99wxyc8iiliy62vl9";
      libraryHaskellDepends = [
        ansi-terminal
        base
        http-types
        iproute
        monads-tf
        network
        options
        stm
        streaming-commons
        transformers
        unix
        wai
        wai-extra
        warp
        warp-tls
      ];
      description = "Command line runner for Wai apps (using Warp) with TLS, CGI, socket activation & graceful shutdown";
      license = lib.licenses.publicDomain;
    }
  ) { };

  wai-conduit = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      conduit,
      http-types,
      transformers,
      wai,
    }:
    mkDerivation {
      pname = "wai-conduit";
      version = "3.0.0.4";
      sha256 = "07yn41rn2skd5p3wqqa09wa761vj7ibl8l19gh4bi4i8slxhk417";
      libraryHaskellDepends = [
        base
        bytestring
        conduit
        http-types
        transformers
        wai
      ];
      description = "conduit wrappers for WAI";
      license = lib.licenses.mit;
    }
  ) { };

  wai-control = callPackage (
    {
      mkDerivation,
      base,
      unliftio-core,
      wai,
      wai-websockets,
      websockets,
    }:
    mkDerivation {
      pname = "wai-control";
      version = "0.2.0.0";
      sha256 = "091plz38ixm4h54hycgyz5g24h2w1wg25bqsbsfyjyhjjzh4a150";
      libraryHaskellDepends = [
        base
        unliftio-core
        wai
        wai-websockets
        websockets
      ];
      description = "Run wai Applications in IO based monads";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-cors = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      base-unicode-symbols,
      bytestring,
      case-insensitive,
      directory,
      filepath,
      http-types,
      mtl,
      network,
      process,
      tasty,
      tasty-hunit,
      text,
      transformers,
      wai,
      wai-extra,
      wai-websockets,
      warp,
      websockets,
    }:
    mkDerivation {
      pname = "wai-cors";
      version = "0.2.7";
      sha256 = "10gv3jjlkcb13031frr818p56v2s0qf6dqjsfpwlhwdxdssvx5r5";
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        attoparsec
        base
        base-unicode-symbols
        bytestring
        case-insensitive
        http-types
        mtl
        transformers
        wai
      ];
      testHaskellDepends = [
        base
        base-unicode-symbols
        directory
        filepath
        http-types
        network
        process
        tasty
        tasty-hunit
        text
        wai
        wai-extra
        wai-websockets
        warp
        websockets
      ];
      description = "CORS for WAI";
      license = lib.licenses.mit;
    }
  ) { };

  wai-cryptocookie = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      case-insensitive,
      cookie,
      crypton,
      directory,
      filepath,
      http-types,
      memory,
      text,
      time,
      wai,
      wai-csrf,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-cryptocookie";
      version = "0.3";
      sha256 = "1g2i1fjdpca0zq7pib6szh8zadrqb93sw1bqi12il5fhd805swh9";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        case-insensitive
        cookie
        crypton
        http-types
        memory
        text
        time
        wai
        wai-csrf
      ];
      testHaskellDepends = [
        base
        bytestring
        cookie
        directory
        filepath
        http-types
        wai
        wai-extra
      ];
      description = "Encrypted cookies for WAI";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
    }
  ) { };

  wai-csrf = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      case-insensitive,
      cookie,
      crypton,
      http-types,
      memory,
      time,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-csrf";
      version = "0.1";
      sha256 = "0i6bwp6libbbv1q0gcrn5cgk66v4ll84gsycxcw18r3nmh3qdawa";
      libraryHaskellDepends = [
        base
        bytestring
        case-insensitive
        cookie
        crypton
        http-types
        memory
        time
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        cookie
        http-types
        wai
        wai-extra
      ];
      description = "Cross-site request forgery protection for WAI";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
    }
  ) { };

  wai-devel = callPackage (
    {
      mkDerivation,
      array,
      base,
      blaze-html,
      bytestring,
      Cabal-ide-backend,
      directory,
      file-embed,
      filepath,
      fsnotify,
      ghc,
      Glob,
      hspec,
      http-client,
      http-conduit,
      http-reverse-proxy,
      http-types,
      ide-backend,
      MissingH,
      network,
      optparse-applicative,
      process,
      shakespeare,
      split,
      stm,
      streaming-commons,
      system-filepath,
      text,
      time,
      transformers,
      wai,
      warp,
      websockets,
    }:
    mkDerivation {
      pname = "wai-devel";
      version = "0.0.0.4";
      sha256 = "0zn2w1fgb0fz9c93vqpgyghjks6npzvxpwdwdxxjl4hzwhgnwsy3";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        array
        base
        blaze-html
        bytestring
        Cabal-ide-backend
        directory
        file-embed
        filepath
        fsnotify
        ghc
        Glob
        http-client
        http-conduit
        http-reverse-proxy
        http-types
        ide-backend
        MissingH
        network
        optparse-applicative
        process
        shakespeare
        split
        stm
        streaming-commons
        system-filepath
        text
        time
        transformers
        wai
        warp
        websockets
      ];
      executableHaskellDepends = [ base ];
      testHaskellDepends = [
        base
        hspec
        stm
      ];
      description = "A web server for the development of WAI compliant web applications";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "wai-devel";
    }
  ) { };

  wai-digestive-functors = callPackage (
    {
      mkDerivation,
      base,
      digestive-functors,
      http-types,
      resourcet,
      text,
      transformers,
      wai,
      wai-extra,
      wai-util,
    }:
    mkDerivation {
      pname = "wai-digestive-functors";
      version = "0.3";
      sha256 = "04l9m43gm1zcgq32c70870kygy87p44zb4kvqcvi86zcspqdgpld";
      libraryHaskellDepends = [
        base
        digestive-functors
        http-types
        resourcet
        text
        transformers
        wai
        wai-extra
        wai-util
      ];
      description = "Helpers to bind digestive-functors onto wai requests";
      license = "unknown";
    }
  ) { };

  wai-dispatch = callPackage (
    {
      mkDerivation,
      base,
      text,
      wai,
      yesod-routes,
    }:
    mkDerivation {
      pname = "wai-dispatch";
      version = "0.1";
      sha256 = "1qyarjbpnngb2x272gkmvrhy3f8kqygxj4nvi6giz09rdx9pfrza";
      libraryHaskellDepends = [
        base
        text
        wai
        yesod-routes
      ];
      description = "Nice wrapper around yesod-routes for use with WAI";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-enforce-https = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      case-insensitive,
      hspec,
      http-types,
      network,
      text,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-enforce-https";
      version = "1.0.0.0";
      sha256 = "08hygyl930bwjxfvzds7wwl9yv94q7612bfg68qzmq2dfivypkfq";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        base
        bytestring
        case-insensitive
        http-types
        network
        text
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        case-insensitive
        hspec
        http-types
        wai
        wai-extra
      ];
      description = "Enforce HTTPS in Wai server app safely";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-env = callPackage (
    {
      mkDerivation,
      base,
      data-default,
      vault,
      wai,
    }:
    mkDerivation {
      pname = "wai-env";
      version = "1.0.0.0";
      sha256 = "03hnp38qgi2qqkzpds7ac2arvsjvpbfdkwwfcl5c6f6zjdwzq97y";
      libraryHaskellDepends = [
        base
        data-default
        vault
        wai
      ];
      description = "WAI middleware to parameterize requests with environment";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-eventsource = callPackage (
    { mkDerivation, wai }:
    mkDerivation {
      pname = "wai-eventsource";
      version = "3.0.0";
      sha256 = "1h5zlqky7ldqbmiaixizhk1s8ghf5i3ha1xfz8flxgzr7gr0al3q";
      libraryHaskellDepends = [ wai ];
      doHaddock = false;
      description = "WAI support for server-sent events (deprecated)";
      license = lib.licenses.mit;
    }
  ) { };

  wai-extra = callPackage (
    {
      mkDerivation,
      aeson,
      ansi-terminal,
      base,
      base64-bytestring,
      bytestring,
      call-stack,
      case-insensitive,
      containers,
      cookie,
      data-default,
      directory,
      fast-logger,
      hspec,
      hspec-discover,
      http-types,
      HUnit,
      iproute,
      network,
      resourcet,
      streaming-commons,
      temporary,
      text,
      time,
      transformers,
      unix,
      vault,
      wai,
      wai-logger,
      warp,
      word8,
      zlib,
    }:
    mkDerivation {
      pname = "wai-extra";
      version = "3.1.18";
      sha256 = "1xshy78bz6jpmvnifbahll5f03mwn41qd5pqjq8v0y6lil5p8qzf";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        ansi-terminal
        base
        base64-bytestring
        bytestring
        call-stack
        case-insensitive
        containers
        cookie
        data-default
        directory
        fast-logger
        http-types
        HUnit
        iproute
        network
        resourcet
        streaming-commons
        text
        time
        transformers
        unix
        vault
        wai
        wai-logger
        warp
        word8
      ];
      testHaskellDepends = [
        aeson
        base
        bytestring
        case-insensitive
        cookie
        directory
        fast-logger
        hspec
        http-types
        HUnit
        iproute
        resourcet
        temporary
        text
        time
        wai
        warp
        word8
        zlib
      ];
      testToolDepends = [ hspec-discover ];
      description = "Provides some basic WAI handlers and middleware";
      license = lib.licenses.mit;
    }
  ) { };

  wai-feature-flags = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      splitmix,
      text,
      unordered-containers,
      wai,
      warp,
    }:
    mkDerivation {
      pname = "wai-feature-flags";
      version = "0.1.0.8";
      sha256 = "0mwad6x95yma2gdpi0i93hl29xhw1qrb4hxgpm2np7cwy8gcprv3";
      isLibrary = true;
      isExecutable = true;
      enableSeparateDataOutput = true;
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        splitmix
        text
        unordered-containers
        wai
      ];
      executableHaskellDepends = [
        base
        wai
        warp
      ];
      description = "Feature flag support for WAI applications";
      license = lib.licenses.bsd3;
      mainProgram = "example-app";
    }
  ) { };

  wai-frontend-monadcgi = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      case-insensitive,
      cgi,
      containers,
      http-types,
      transformers,
      wai,
    }:
    mkDerivation {
      pname = "wai-frontend-monadcgi";
      version = "3.0.0.3";
      sha256 = "0a97yj6bs59a600lhif6gnvb28a1x25d9n58lzgkirjj48vssh5i";
      libraryHaskellDepends = [
        base
        bytestring
        case-insensitive
        cgi
        containers
        http-types
        transformers
        wai
      ];
      description = "Run CGI apps on WAI";
      license = lib.licenses.mit;
    }
  ) { };

  wai-git-http = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      blaze-builder,
      bytestring,
      case-insensitive,
      conduit,
      conduit-extra,
      containers,
      directory,
      filepath,
      hspec,
      http-types,
      network,
      process,
      sockaddr,
      text,
      wai,
      wai-conduit,
      warp,
    }:
    mkDerivation {
      pname = "wai-git-http";
      version = "0.0.0";
      sha256 = "15j0zkrd0m0qs0yg6b6zwhgfq283a2j8dxf1aqs9l9cbagzsg75g";
      libraryHaskellDepends = [
        attoparsec
        base
        blaze-builder
        bytestring
        case-insensitive
        conduit
        conduit-extra
        containers
        directory
        filepath
        http-types
        network
        process
        sockaddr
        text
        wai
        wai-conduit
      ];
      testHaskellDepends = [
        base
        bytestring
        conduit
        conduit-extra
        directory
        hspec
        process
        wai
        warp
      ];
      description = "Git http-backend CGI App of WAI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-graceful = callPackage (
    {
      mkDerivation,
      base,
      http-types,
      mtl,
      resourcet,
      unix,
      wai,
    }:
    mkDerivation {
      pname = "wai-graceful";
      version = "0.1.0.1";
      sha256 = "0a06yrakg9gwjjj4f9nr474j8i8xz642aj56m8vaq621i1kn7jaq";
      libraryHaskellDepends = [
        base
        http-types
        mtl
        resourcet
        unix
        wai
      ];
      description = "Graceful shutdown for WAI applications";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-handler-devel = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      bytestring,
      cmdargs,
      directory,
      hint,
      http-types,
      network,
      old-time,
      text,
      time,
      transformers,
      wai,
      wai-extra,
      warp,
    }:
    mkDerivation {
      pname = "wai-handler-devel";
      version = "2.0.0.2";
      sha256 = "13f3w31kr3zinll76i6y3walpyqz3i1rlbsh3d7c5p8hp2d88bzy";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        attoparsec
        base
        bytestring
        directory
        hint
        http-types
        network
        old-time
        text
        time
        transformers
        wai
        wai-extra
        warp
      ];
      executableHaskellDepends = [ cmdargs ];
      description = "WAI server that automatically reloads code after modification. (deprecated)";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-handler-fastcgi = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      fcgi,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-handler-fastcgi";
      version = "3.0.0.3";
      sha256 = "15z9zmlm8svak0gqcw4p0yx1q4dr7wqsn24a2zfzacihfi47pkva";
      libraryHaskellDepends = [
        base
        bytestring
        wai
        wai-extra
      ];
      librarySystemDepends = [ fcgi ];
      description = "Wai handler to fastcgi";
      license = lib.licenses.mit;
    }
  ) { inherit (pkgs) fcgi; };

  wai-handler-hal = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      base64-bytestring,
      bytestring,
      case-insensitive,
      hal,
      http-media,
      http-types,
      network,
      pretty-simple,
      tasty,
      tasty-discover,
      tasty-golden,
      tasty-hunit,
      text,
      unordered-containers,
      vault,
      wai,
    }:
    mkDerivation {
      pname = "wai-handler-hal";
      version = "0.5.0.0";
      sha256 = "1v4x1ma31lvhmrwpqlig3xicdyk6q2rpasgc0ynfsl57n9wp5yvd";
      libraryHaskellDepends = [
        base
        base64-bytestring
        bytestring
        case-insensitive
        hal
        http-media
        http-types
        network
        text
        unordered-containers
        vault
        wai
      ];
      testHaskellDepends = [
        aeson
        base
        base64-bytestring
        bytestring
        case-insensitive
        hal
        http-media
        http-types
        network
        pretty-simple
        tasty
        tasty-golden
        tasty-hunit
        text
        unordered-containers
        vault
        wai
      ];
      testToolDepends = [ tasty-discover ];
      description = "Wrap WAI applications to run on AWS Lambda";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-handler-launch = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      http-types,
      process,
      streaming-commons,
      transformers,
      wai,
      warp,
    }:
    mkDerivation {
      pname = "wai-handler-launch";
      version = "3.0.3.1";
      sha256 = "1ifqgyc1ccig5angh5l1iq7vyms4lvi8wzvysg5dw82nml49n02m";
      revision = "1";
      editedCabalFile = "1jp1lngryrg4v84q4q6c5g7h93kasdk3bgp4x0miivvx8s8iibs6";
      libraryHaskellDepends = [
        async
        base
        bytestring
        http-types
        process
        streaming-commons
        transformers
        wai
        warp
      ];
      description = "Launch a web app in the default browser";
      license = lib.licenses.mit;
    }
  ) { };

  wai-handler-scgi = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-handler-scgi";
      version = "2.0.0.2";
      sha256 = "0h7d78d641bjsnmxsnz4b7s9pw4x0y0xi8bld51y4nqnbjl8gvac";
      libraryHaskellDepends = [
        base
        bytestring
        wai
        wai-extra
      ];
      description = "Wai handler to SCGI (deprecated)";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-handler-snap = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      enumerator,
      snap-core,
      snap-server,
      transformers,
      wai,
    }:
    mkDerivation {
      pname = "wai-handler-snap";
      version = "0.1.1";
      sha256 = "0akk9h7m1hhdggbhj0grss94jzm13fmcmgj51nvh7mfj6f5kj31l";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        enumerator
        snap-core
        snap-server
        transformers
        wai
      ];
      description = "Web Application Interface handler using snap-server. (deprecated)";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-handler-webkit = callPackage (
    {
      mkDerivation,
      base,
      QtWebKit,
      wai,
      warp,
    }:
    mkDerivation {
      pname = "wai-handler-webkit";
      version = "3.0.0.3";
      sha256 = "10sr9xgd95ncwczbmchaf2qjyadqchm566r3zhqc3bwgsydrsq08";
      revision = "1";
      editedCabalFile = "073p8nar10pv1p1k7ryjv38404wdmhzpv3llql034r6bhdplc5gr";
      libraryHaskellDepends = [
        base
        wai
        warp
      ];
      libraryPkgconfigDepends = [ QtWebKit ];
      description = "Turn WAI applications into standalone GUIs using QtWebkit";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { QtWebKit = null; };

  wai-hastache = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      hastache,
      http-types,
      transformers,
      wai,
    }:
    mkDerivation {
      pname = "wai-hastache";
      version = "0.1";
      sha256 = "1kkn8n33cm5r7hw0xxf815nx1ixg09r7ckspq228j1syq5j1lzq8";
      libraryHaskellDepends = [
        base
        bytestring
        hastache
        http-types
        transformers
        wai
      ];
      description = "Nice wrapper around hastache for use with WAI";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-hmac-auth = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      bifunctors,
      byteable,
      bytestring,
      containers,
      cryptohash,
      hspec,
      http-types,
      monad-loops,
      mtl,
      transformers,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-hmac-auth";
      version = "1.0.0";
      sha256 = "1hjzwh9hzy29y617faa94428s7ja2ri0bggqxwmf27a0r4qpf1r4";
      libraryHaskellDepends = [
        base
        base64-bytestring
        bifunctors
        byteable
        bytestring
        containers
        cryptohash
        http-types
        monad-loops
        mtl
        transformers
        wai
      ];
      testHaskellDepends = [
        base
        base64-bytestring
        bifunctors
        byteable
        bytestring
        containers
        cryptohash
        hspec
        http-types
        monad-loops
        mtl
        transformers
        wai
        wai-extra
      ];
      description = "hmac authentication tools for WAI apps";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-http2-extra = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      doctest,
      http-types,
      psqueues,
      wai,
      warp,
      word8,
    }:
    mkDerivation {
      pname = "wai-http2-extra";
      version = "0.1.3";
      sha256 = "0nchb2jxaa687lksryhgpyr8s9p7g6z34rcwddan5lzr5khp0g2c";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        http-types
        psqueues
        wai
        warp
        word8
      ];
      testHaskellDepends = [
        base
        doctest
      ];
      description = "WAI utilities for HTTP/2";
      license = lib.licenses.mit;
    }
  ) { };

  wai-lambda = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      binary,
      bytestring,
      case-insensitive,
      deepseq,
      directory,
      http-types,
      iproute,
      network,
      temporary,
      text,
      unliftio,
      unordered-containers,
      vault,
      wai,
    }:
    mkDerivation {
      pname = "wai-lambda";
      version = "0.1.1.0";
      sha256 = "1qx69gp2mrlc1gy45vcyicj9f9wyzdnidkqw15lm4hdmz20qwjzc";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        binary
        bytestring
        case-insensitive
        deepseq
        directory
        http-types
        iproute
        network
        temporary
        text
        unliftio
        unordered-containers
        vault
        wai
      ];
      executableHaskellDepends = [
        aeson
        base
        binary
        bytestring
        case-insensitive
        deepseq
        directory
        http-types
        iproute
        network
        temporary
        text
        unliftio
        unordered-containers
        vault
        wai
      ];
      description = "Haskell Webapps on AWS Lambda";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "wai-lambda";
      broken = true;
    }
  ) { };

  wai-lens = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-types,
      lens,
      network,
      text,
      vault,
      wai,
    }:
    mkDerivation {
      pname = "wai-lens";
      version = "0.1";
      sha256 = "05vd7pjw6jgbb11yln4h2lbyr5pr471040p51pj7iy2m65s42v4x";
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        lens
        network
        text
        vault
        wai
      ];
      description = "Lenses for WAI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-lite = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      conduit,
      http-types,
      text,
      transformers,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-lite";
      version = "0.2.0.0";
      sha256 = "1ghxna51m304x5yvgfdgpml0yf6jqhfkixlxxnflg7z34h6wjzz4";
      libraryHaskellDepends = [
        base
        bytestring
        conduit
        http-types
        text
        transformers
        wai
        wai-extra
      ];
      description = "DEPCRECATED (use package \"simple\" instead) A minimalist web framework for WAI web applications";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-log = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      http-types,
      log-base,
      string-conversions,
      text,
      time,
      uuid,
      wai,
    }:
    mkDerivation {
      pname = "wai-log";
      version = "0.4.0.1";
      sha256 = "02lrbvl1rj3jmm9z2mjrkss0lz7jz8xx6cknznd2i4rhirl1vlhr";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        http-types
        log-base
        string-conversions
        text
        time
        uuid
        wai
      ];
      description = "A logging middleware for WAI applications";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-logger = callPackage (
    {
      mkDerivation,
      base,
      byteorder,
      bytestring,
      fast-logger,
      http-types,
      network,
      wai,
    }:
    mkDerivation {
      pname = "wai-logger";
      version = "2.5.0";
      sha256 = "1171qfz6wlmq69virwvlg79j4smk6sqhdvrdpnisr50zdc3x7ysw";
      libraryHaskellDepends = [
        base
        byteorder
        bytestring
        fast-logger
        http-types
        network
        wai
      ];
      description = "A logging system for WAI";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-logger-buffered = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      data-default,
      http-types,
      time,
      wai,
      warp,
    }:
    mkDerivation {
      pname = "wai-logger-buffered";
      version = "0.1.0.1";
      sha256 = "0ksyh5g3wsldg739gzjvvmw9r1wrm5vq84n3shjqsl2y29r4kbls";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        containers
        data-default
        time
        wai
      ];
      executableHaskellDepends = [
        base
        bytestring
        containers
        data-default
        http-types
        time
        wai
        warp
      ];
      testHaskellDepends = [
        base
        bytestring
        containers
        data-default
        time
        wai
      ];
      description = "Buffer requets before logging them";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "example";
      broken = true;
    }
  ) { };

  wai-logger-prefork = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      date-cache,
      fast-logger,
      http-types,
      unix,
      wai,
      wai-logger,
    }:
    mkDerivation {
      pname = "wai-logger-prefork";
      version = "0.3.0";
      sha256 = "0cfslqr2zdj0x83dbscafhdljrn2xswym7hpf23zlrsrnpz71qy4";
      libraryHaskellDepends = [
        base
        bytestring
        date-cache
        fast-logger
        http-types
        unix
        wai
        wai-logger
      ];
      description = "A logging system for preforked WAI apps";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-make-assets = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      data-default,
      directory,
      filepath,
      getopt-generics,
      hspec,
      http-types,
      lens,
      mockery,
      shake,
      silently,
      string-conversions,
      wai,
      wai-app-static,
      warp,
      wreq,
    }:
    mkDerivation {
      pname = "wai-make-assets";
      version = "0.3";
      sha256 = "07h56bjyap8x2aaay23k3l6n6gk1h5a3qqijd33b4pnc0nygfzci";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        data-default
        directory
        filepath
        http-types
        shake
        string-conversions
        wai
        wai-app-static
        warp
      ];
      executableHaskellDepends = [
        base
        bytestring
        data-default
        directory
        filepath
        getopt-generics
        http-types
        shake
        string-conversions
        wai
        wai-app-static
        warp
      ];
      testHaskellDepends = [
        base
        bytestring
        data-default
        directory
        filepath
        hspec
        http-types
        lens
        mockery
        shake
        silently
        string-conversions
        wai
        wai-app-static
        warp
        wreq
      ];
      description = "Compiling and serving assets";
      license = lib.licenses.bsd3;
      mainProgram = "wai-make-assets";
    }
  ) { };

  wai-middleware-auth = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      base64-bytestring,
      binary,
      blaze-builder,
      blaze-html,
      bytestring,
      case-insensitive,
      cereal,
      clientsession,
      cookie,
      exceptions,
      hedgehog,
      hoauth2,
      http-client,
      http-client-tls,
      http-conduit,
      http-reverse-proxy,
      http-types,
      jose,
      microlens,
      mtl,
      optparse-applicative,
      optparse-simple,
      regex-posix,
      safe-exceptions,
      shakespeare,
      tasty,
      tasty-hedgehog,
      tasty-hunit,
      text,
      time,
      unix-compat,
      unordered-containers,
      uri-bytestring,
      vault,
      wai,
      wai-app-static,
      wai-extra,
      warp,
      yaml,
    }:
    mkDerivation {
      pname = "wai-middleware-auth";
      version = "0.2.6.0";
      sha256 = "0ji0jywippk9vqdcbv79fy79xl20p91h8wdadmxa684m5mj95b6x";
      revision = "1";
      editedCabalFile = "0jivjypzh6331hk2y5rb1cyf27qmxdmwc2a3p1cjmc7636h1il4k";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        base64-bytestring
        binary
        blaze-builder
        blaze-html
        bytestring
        case-insensitive
        cereal
        clientsession
        cookie
        exceptions
        hoauth2
        http-client
        http-client-tls
        http-conduit
        http-reverse-proxy
        http-types
        jose
        microlens
        mtl
        regex-posix
        safe-exceptions
        shakespeare
        text
        time
        unix-compat
        unordered-containers
        uri-bytestring
        vault
        wai
        wai-app-static
        wai-extra
        yaml
      ];
      executableHaskellDepends = [
        base
        bytestring
        cereal
        clientsession
        optparse-applicative
        optparse-simple
        wai-extra
        warp
      ];
      testHaskellDepends = [
        aeson
        base
        binary
        bytestring
        clientsession
        cookie
        hedgehog
        hoauth2
        http-types
        jose
        microlens
        mtl
        tasty
        tasty-hedgehog
        tasty-hunit
        text
        time
        uri-bytestring
        wai
        wai-extra
        warp
      ];
      description = "Authentication middleware that secures WAI application";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "wai-auth";
      broken = true;
    }
  ) { };

  wai-middleware-bearer = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      hspec,
      hspec-wai,
      http-types,
      wai,
      word8,
    }:
    mkDerivation {
      pname = "wai-middleware-bearer";
      version = "1.0.3";
      sha256 = "17vqvr9f8n4zgxhhanndkpywjmzffm06f2nbsq1wxq79qpghc44j";
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        wai
        word8
      ];
      testHaskellDepends = [
        base
        bytestring
        hspec
        hspec-wai
        http-types
        wai
        word8
      ];
      description = "WAI Middleware for Bearer Token Authentication";
      license = lib.licenses.mit;
    }
  ) { };

  wai-middleware-brotli = callPackage (
    {
      mkDerivation,
      base,
      binary,
      bytestring,
      directory,
      filepath,
      hs-brotli,
      http-types,
      mtl,
      tasty,
      tasty-hspec,
      tasty-hunit,
      unix,
      wai,
      wai-app-static,
      wai-extra,
      warp,
    }:
    mkDerivation {
      pname = "wai-middleware-brotli";
      version = "0.1.0.0";
      sha256 = "1gv3s2y49179kzkjqzs905g2rq1a9al9n716y86ivan8nnkhxjnq";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        binary
        bytestring
        directory
        filepath
        hs-brotli
        http-types
        unix
        wai
      ];
      executableHaskellDepends = [
        base
        http-types
        wai
        wai-app-static
        wai-extra
        warp
      ];
      testHaskellDepends = [
        base
        bytestring
        hs-brotli
        http-types
        mtl
        tasty
        tasty-hspec
        tasty-hunit
        wai
        wai-extra
      ];
      description = "WAI middleware for brotli compression";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "wai-middleware-brotli-server";
    }
  ) { };

  wai-middleware-cache = callPackage (
    {
      mkDerivation,
      base,
      binary,
      blaze-builder-conduit,
      bytestring,
      conduit,
      crypto-conduit,
      http-types,
      HUnit,
      pureMD5,
      test-framework,
      test-framework-hunit,
      wai,
      wai-test,
    }:
    mkDerivation {
      pname = "wai-middleware-cache";
      version = "0.3.6";
      sha256 = "1kqrqjsmnwwavcyhwx6m2x3qk7qbd0h60817ai61dz3aprwc8hdw";
      libraryHaskellDepends = [
        base
        binary
        blaze-builder-conduit
        bytestring
        conduit
        crypto-conduit
        http-types
        pureMD5
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        http-types
        HUnit
        test-framework
        test-framework-hunit
        wai
        wai-test
      ];
      description = "Caching middleware for WAI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-middleware-cache-redis = callPackage (
    {
      mkDerivation,
      base,
      binary,
      blaze-builder-conduit,
      bytestring,
      case-insensitive,
      conduit,
      hedis,
      hedis-pile,
      http-types,
      transformers,
      wai,
      wai-middleware-cache,
    }:
    mkDerivation {
      pname = "wai-middleware-cache-redis";
      version = "0.4.3";
      sha256 = "1vd81jcisav6jyqzwa0qn35xarm21bjrw0qps9qbbq56svkh1lw9";
      libraryHaskellDepends = [
        base
        binary
        blaze-builder-conduit
        bytestring
        case-insensitive
        conduit
        hedis
        hedis-pile
        http-types
        transformers
        wai
        wai-middleware-cache
      ];
      description = "Redis backend for wai-middleware-cache";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-middleware-caching = callPackage (
    {
      mkDerivation,
      base,
      blaze-builder,
      bytestring,
      http-types,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-caching";
      version = "0.1.0.2";
      sha256 = "13fp08ba46wn7gianfbirag8yj14s2x41fkhdb5mx7arjafgpd8m";
      libraryHaskellDepends = [
        base
        blaze-builder
        bytestring
        http-types
        wai
      ];
      testHaskellDepends = [ base ];
      description = "WAI Middleware to cache things";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-caching-lru = callPackage (
    {
      mkDerivation,
      base,
      blaze-builder,
      bytestring,
      http-types,
      lrucache,
      text,
      wai,
      wai-middleware-caching,
    }:
    mkDerivation {
      pname = "wai-middleware-caching-lru";
      version = "0.1.0.0";
      sha256 = "1lr8vaail00g72dgdfcgjzdd1kqwi4n0jzl1ia7bjxxdym1chz9p";
      libraryHaskellDepends = [
        base
        blaze-builder
        bytestring
        http-types
        lrucache
        text
        wai
        wai-middleware-caching
      ];
      testHaskellDepends = [ base ];
      description = "Initial project template from stack";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-caching-redis = callPackage (
    {
      mkDerivation,
      base,
      blaze-builder,
      bytestring,
      hedis,
      http-types,
      text,
      wai,
      wai-middleware-caching,
    }:
    mkDerivation {
      pname = "wai-middleware-caching-redis";
      version = "0.2.0.0";
      sha256 = "0k3wpw9prhcac8iavzr0xdcwl8khkxks4kji03zz1n10vf1kgxbg";
      libraryHaskellDepends = [
        base
        blaze-builder
        bytestring
        hedis
        http-types
        text
        wai
        wai-middleware-caching
      ];
      testHaskellDepends = [ base ];
      description = "Cache Wai Middleware using Redis backend";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-catch = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-types,
      lifted-base,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-catch";
      version = "0.3.6";
      sha256 = "1vh5sad3zhdwxqbmivmy9hkbnq9vrv4k6k17rjk4f79lv2xcq56h";
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        lifted-base
        wai
      ];
      description = "Wai error catching middleware";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-clacks = callPackage (
    {
      mkDerivation,
      base,
      base-compat-batteries,
      bytestring,
      case-insensitive,
      http-types,
      tasty,
      tasty-wai,
      text,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-clacks";
      version = "0.1.0.1";
      sha256 = "1mx3qmyiywib8wcrccxd7wjlx4jv9wlc5w8lykivgh8q66pbcihf";
      revision = "1";
      editedCabalFile = "1q26ni3mzy102ib5428axj149h6j8pxgsccfzxccqbdvwf5nmn7r";
      libraryHaskellDepends = [
        base
        base-compat-batteries
        bytestring
        case-insensitive
        http-types
        text
        wai
      ];
      testHaskellDepends = [
        base
        base-compat-batteries
        http-types
        tasty
        tasty-wai
        wai
      ];
      description = "GNU Terry Pratchett - Add the X-Clacks-Overhead Header to Wai Responses";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-consul = callPackage (
    {
      mkDerivation,
      async,
      base,
      base-prelude,
      bytestring,
      conduit,
      conduit-extra,
      consul-haskell,
      enclosed-exceptions,
      http-client,
      http-types,
      monad-control,
      monad-logger,
      network,
      process,
      resourcet,
      text,
      transformers,
      void,
      wai,
      wai-conduit,
    }:
    mkDerivation {
      pname = "wai-middleware-consul";
      version = "0.1.0.2";
      sha256 = "0qq7kilp9a4qjja337saqccn250s6mnf3n80sgyg935hy1dmm7fq";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        async
        base
        base-prelude
        bytestring
        conduit
        conduit-extra
        consul-haskell
        enclosed-exceptions
        http-client
        http-types
        monad-control
        monad-logger
        network
        process
        resourcet
        text
        transformers
        void
        wai
        wai-conduit
      ];
      description = "Wai Middleware for Consul";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-middleware-content-type = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      blaze-builder,
      blaze-html,
      bytestring,
      clay,
      exceptions,
      extractable-singleton,
      hashable,
      hspec,
      hspec-wai,
      http-media,
      http-types,
      lucid,
      mmorph,
      monad-control,
      monad-control-aligned,
      monad-logger,
      mtl,
      resourcet,
      shakespeare,
      tasty,
      tasty-hspec,
      text,
      transformers,
      transformers-base,
      unordered-containers,
      urlpath,
      wai,
      wai-logger,
      wai-transformers,
      warp,
    }:
    mkDerivation {
      pname = "wai-middleware-content-type";
      version = "0.7.0";
      sha256 = "1gh4fgc9c4cy32ifq7wxmxk3px2827bji7159xmh06n41c1bv14s";
      libraryHaskellDepends = [
        aeson
        base
        blaze-builder
        blaze-html
        bytestring
        clay
        exceptions
        extractable-singleton
        hashable
        http-media
        http-types
        lucid
        mmorph
        monad-control
        monad-control-aligned
        monad-logger
        mtl
        resourcet
        shakespeare
        text
        transformers
        transformers-base
        unordered-containers
        urlpath
        wai
        wai-logger
        wai-transformers
      ];
      testHaskellDepends = [
        aeson
        base
        blaze-builder
        blaze-html
        bytestring
        clay
        exceptions
        extractable-singleton
        hashable
        hspec
        hspec-wai
        http-media
        http-types
        lucid
        mmorph
        monad-control
        monad-control-aligned
        monad-logger
        mtl
        resourcet
        shakespeare
        tasty
        tasty-hspec
        text
        transformers
        transformers-base
        unordered-containers
        urlpath
        wai
        wai-logger
        wai-transformers
        warp
      ];
      description = "Route to different middlewares based on the incoming Accept header";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-crowd = callPackage (
    {
      mkDerivation,
      authenticate,
      base,
      base64-bytestring,
      binary,
      blaze-builder,
      bytestring,
      case-insensitive,
      clientsession,
      containers,
      cookie,
      gitrev,
      http-client,
      http-client-tls,
      http-reverse-proxy,
      http-types,
      optparse-applicative,
      resourcet,
      template-haskell,
      text,
      time,
      transformers,
      unix-compat,
      vault,
      wai,
      wai-app-static,
      wai-extra,
      warp,
    }:
    mkDerivation {
      pname = "wai-middleware-crowd";
      version = "0.1.4.2";
      sha256 = "0n5h4s3b2fdn2j0pl32bsdbf6wyyf2ms8qsbcs9r0wp7dhdbcdhi";
      revision = "1";
      editedCabalFile = "0qvh92p9s80kmzg5w7rga54kfqbwcrkkv5p03pd92px04j2h5lbm";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        authenticate
        base
        base64-bytestring
        binary
        blaze-builder
        bytestring
        case-insensitive
        clientsession
        containers
        cookie
        http-client
        http-client-tls
        http-types
        resourcet
        text
        time
        unix-compat
        vault
        wai
      ];
      executableHaskellDepends = [
        base
        bytestring
        clientsession
        gitrev
        http-client
        http-client-tls
        http-reverse-proxy
        http-types
        optparse-applicative
        template-haskell
        text
        transformers
        wai
        wai-app-static
        wai-extra
        warp
      ];
      description = "Middleware and utilities for using Atlassian Crowd authentication";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "wai-crowd";
      broken = true;
    }
  ) { };

  wai-middleware-delegate = callPackage (
    {
      mkDerivation,
      async,
      base,
      blaze-builder,
      bytestring,
      bytestring-lexing,
      case-insensitive,
      conduit,
      conduit-extra,
      crypton-connection,
      data-default,
      directory,
      filepath,
      fmt,
      hspec,
      hspec-tmp-proc,
      http-client,
      http-client-tls,
      http-types,
      network,
      random,
      resourcet,
      streaming-commons,
      temporary,
      test-certs,
      text,
      tmp-proc,
      unix,
      vault,
      wai,
      wai-conduit,
      warp,
      warp-tls,
    }:
    mkDerivation {
      pname = "wai-middleware-delegate";
      version = "0.2.0.1";
      sha256 = "1xqrfi6rqpa8k2iix9mcgyscavjjz3qdpm3gp1dijvyxfbwwp95m";
      libraryHaskellDepends = [
        async
        base
        blaze-builder
        bytestring
        case-insensitive
        conduit
        conduit-extra
        http-client
        http-client-tls
        http-types
        streaming-commons
        text
        wai
        wai-conduit
      ];
      testHaskellDepends = [
        async
        base
        blaze-builder
        bytestring
        bytestring-lexing
        case-insensitive
        conduit
        conduit-extra
        crypton-connection
        data-default
        directory
        filepath
        fmt
        hspec
        hspec-tmp-proc
        http-client
        http-client-tls
        http-types
        network
        random
        resourcet
        temporary
        test-certs
        text
        tmp-proc
        unix
        vault
        wai
        wai-conduit
        warp
        warp-tls
      ];
      description = "WAI middleware that delegates handling of requests";
      license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
    }
  ) { };

  wai-middleware-etag = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      bytestring,
      cryptohash,
      filepath,
      http-date,
      http-types,
      unix-compat,
      unordered-containers,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-etag";
      version = "0.1.1.1";
      sha256 = "1r3v4f70lvl5qcgs4h3bacg2vy4hlwqfmnw8ffiwigf01qygyyb2";
      libraryHaskellDepends = [
        base
        base64-bytestring
        bytestring
        cryptohash
        filepath
        http-date
        http-types
        unix-compat
        unordered-containers
        wai
      ];
      description = "WAI ETag middleware for static files";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-gunzip = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-types,
      streaming-commons,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-gunzip";
      version = "0.0.2";
      sha256 = "0rbvpw4y4qr2mhijlybzwwd12mkhrwmxlrhj2q0mq9diwhp597dx";
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        streaming-commons
        wai
      ];
      description = "WAI middleware to unzip request bodies";
      license = lib.licenses.mpl20;
    }
  ) { };

  wai-middleware-headers = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-types,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-headers";
      version = "0.1";
      sha256 = "10ap355j4dx42y7ycf1plpbg04wazv0q62mi3ibza8sb33hiiprh";
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        wai
      ];
      description = "cors and addHeaders for WAI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-hmac = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      byteable,
      bytestring,
      case-insensitive,
      cryptohash,
      doctest,
      Glob,
      hlint,
      hspec,
      http-types,
      HUnit,
      process,
      regex-compat,
      transformers,
      wai,
      wai-extra,
      word8,
    }:
    mkDerivation {
      pname = "wai-middleware-hmac";
      version = "0.1.0.0";
      sha256 = "01xd1nhi96lflh6ssaz3m5dkacrp2b2kwk611jc8q5j3kmyc0zqs";
      libraryHaskellDepends = [
        base
        base64-bytestring
        byteable
        bytestring
        case-insensitive
        cryptohash
        http-types
        transformers
        wai
        word8
      ];
      testHaskellDepends = [
        base
        bytestring
        doctest
        Glob
        hlint
        hspec
        http-types
        HUnit
        process
        regex-compat
        wai
        wai-extra
      ];
      description = "HMAC Authentication Middleware for WAI";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-hmac-client = callPackage (
    {
      mkDerivation,
      base,
      base64-bytestring,
      byteable,
      bytestring,
      case-insensitive,
      cryptohash,
      http-client,
      http-types,
      mtl,
      old-locale,
      time,
      transformers,
      word8,
    }:
    mkDerivation {
      pname = "wai-middleware-hmac-client";
      version = "0.1.0.2";
      sha256 = "1jmfmcdv1js6rgadfhwb071qp418440ij0hm0fmyf03dk879qhds";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        base64-bytestring
        byteable
        bytestring
        case-insensitive
        cryptohash
        http-client
        http-types
        mtl
        old-locale
        time
        transformers
        word8
      ];
      description = "WAI HMAC Authentication Middleware Client";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-json-errors = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      binary,
      bytestring,
      http-types,
      text,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-json-errors";
      version = "0.1.2";
      sha256 = "0zid8by1d4rqnbigvj6wbikfnq5gc0k3k75is46zf66y8i3bcd4l";
      libraryHaskellDepends = [
        aeson
        base
        binary
        bytestring
        http-types
        text
        wai
      ];
      testHaskellDepends = [
        aeson
        base
        binary
        bytestring
        http-types
        text
        wai
      ];
      description = "Converts errors from plaintext to json";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-metrics = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      criterion,
      ekg-core,
      http-types,
      QuickCheck,
      scotty,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      text,
      time,
      transformers,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-middleware-metrics";
      version = "0.2.4";
      sha256 = "0x7c53lqbf55p3ba6naj9xwjz07k4gf0ql3bjlb6vfph92kqadp7";
      libraryHaskellDepends = [
        base
        ekg-core
        http-types
        text
        time
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        ekg-core
        http-types
        QuickCheck
        scotty
        tasty
        tasty-hunit
        tasty-quickcheck
        text
        time
        transformers
        wai
        wai-extra
      ];
      benchmarkHaskellDepends = [
        base
        bytestring
        criterion
        ekg-core
        http-types
        scotty
        text
        time
        wai
        wai-extra
      ];
      description = "A WAI middleware to collect EKG request metrics";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-preprocessor = callPackage (
    {
      mkDerivation,
      base,
      Cabal,
      directory,
      mtl,
      split,
      text,
      wai,
      wai-middleware-static,
      warp,
    }:
    mkDerivation {
      pname = "wai-middleware-preprocessor";
      version = "0.2.0.0";
      sha256 = "1n9z00v5a75pas22cdm26hj888s6kc98bddh2gfs3ffrazdmgbj1";
      libraryHaskellDepends = [
        base
        directory
        mtl
        split
        text
        wai
        wai-middleware-static
      ];
      testHaskellDepends = [
        base
        Cabal
        directory
        mtl
        split
        text
        wai
        wai-middleware-static
        warp
      ];
      description = "WAI middleware for preprocessing static files";
      license = lib.licenses.gpl3Only;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-prometheus = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      clock,
      data-default,
      doctest,
      http-types,
      prometheus-client,
      text,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-prometheus";
      version = "1.0.1.0";
      sha256 = "0c96zzkpfyfas9x9h8zlkba9qpdf6bjrkp0px80rw4bjr6vvn32i";
      libraryHaskellDepends = [
        base
        bytestring
        clock
        data-default
        http-types
        prometheus-client
        text
        wai
      ];
      testHaskellDepends = [
        base
        doctest
        prometheus-client
      ];
      description = "WAI middlware for exposing http://prometheus.io metrics.";
      license = lib.licenses.asl20;
    }
  ) { };

  wai-middleware-rollbar = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      hostname,
      http-client,
      http-conduit,
      http-types,
      rollbar-hs,
      text,
      time,
      uuid,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-rollbar";
      version = "0.11.0";
      sha256 = "1nsnkf9wk61lj092z56knwfrdjyazql16y2kj5h0iamnf4gmxa7w";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        hostname
        http-client
        http-conduit
        http-types
        rollbar-hs
        text
        time
        uuid
        wai
      ];
      description = "Middleware that communicates to Rollbar";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-middleware-route = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-types,
      HUnit,
      test-framework,
      test-framework-hunit,
      text,
      wai,
      wai-test,
      yesod-routes,
    }:
    mkDerivation {
      pname = "wai-middleware-route";
      version = "0.7.3";
      sha256 = "0zgiaxc5rqjlkfwkb11a5zkmbybrfcqr74mq5vpj03mqz1q0lmx7";
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        text
        wai
        yesod-routes
      ];
      testHaskellDepends = [
        base
        bytestring
        http-types
        HUnit
        test-framework
        test-framework-hunit
        text
        wai
        wai-test
      ];
      description = "Wai dispatch middleware";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-middleware-slack-verify = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cryptonite,
      errors,
      hspec,
      http-types,
      HUnit,
      memory,
      time,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-middleware-slack-verify";
      version = "0.1.0.0";
      sha256 = "18kcvr2w9zgl2hv3w6hfl5ll1jsc2idd2fh1hv4kh7b8mw71s605";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        cryptonite
        errors
        http-types
        memory
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        cryptonite
        errors
        hspec
        http-types
        HUnit
        memory
        time
        wai
        wai-extra
      ];
      description = "WAI Slack request verification middleware";
      license = lib.licenses.mit;
    }
  ) { };

  wai-middleware-static = callPackage (
    {
      mkDerivation,
      base,
      base16-bytestring,
      bytestring,
      cryptohash-sha1,
      directory,
      expiring-cache-map,
      filepath,
      hspec,
      hspec-discover,
      hspec-expectations-lifted,
      hspec-wai,
      http-types,
      mime-types,
      mockery,
      scotty,
      text,
      time,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-middleware-static";
      version = "0.9.4";
      sha256 = "1p28br8ll417wc56sds8sk11hvjljq47h9swd2bpa8n5vvbdjmfq";
      libraryHaskellDepends = [
        base
        base16-bytestring
        bytestring
        cryptohash-sha1
        directory
        expiring-cache-map
        filepath
        http-types
        mime-types
        text
        time
        wai
      ];
      testHaskellDepends = [
        base
        hspec
        hspec-expectations-lifted
        hspec-wai
        http-types
        mockery
        scotty
        wai-extra
      ];
      testToolDepends = [ hspec-discover ];
      description = "WAI middleware that serves requests to static files";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-static-caching = callPackage (
    {
      mkDerivation,
      base,
      base16-bytestring,
      bytestring,
      containers,
      cryptohash,
      directory,
      expiring-cache-map,
      filepath,
      http-types,
      mtl,
      old-locale,
      text,
      time,
      unix,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-static-caching";
      version = "0.6.0.1";
      sha256 = "0xj4r1fr1g0fybgsq65gxcvh5zn9hafvm0f73p6dnj6jhz6dryhk";
      libraryHaskellDepends = [
        base
        base16-bytestring
        bytestring
        containers
        cryptohash
        directory
        expiring-cache-map
        filepath
        http-types
        mtl
        old-locale
        text
        time
        unix
        wai
      ];
      description = "WAI middleware that serves requests to static files";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-static-embedded = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cryptonite,
      http-types,
      memory,
      mime-types,
      text,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-middleware-static-embedded";
      version = "0.1.0.0";
      sha256 = "1b8n514yp7kqvz2z0qfp9hf6vai6117p62h8hprw5kkla456lb6y";
      revision = "1";
      editedCabalFile = "1qrkfhdw5qanqggvc05vlp56704qskrhw9qyzv8m5576lliphsq3";
      libraryHaskellDepends = [
        base
        bytestring
        cryptonite
        http-types
        memory
        mime-types
        text
        wai
        wai-extra
      ];
      description = "Serve embedded static files as a Wai middleware";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-throttle = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      bytestring-builder,
      cache,
      clock,
      containers,
      hashable,
      hspec,
      http-types,
      HUnit,
      mtl,
      network,
      QuickCheck,
      safe-exceptions,
      stm,
      text,
      token-bucket,
      transformers,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-middleware-throttle";
      version = "0.3.0.1";
      sha256 = "0mpw7b56k1a89kzwa3v4c4ff66m0py9s9p2jan2zhp8k3b8862jq";
      revision = "1";
      editedCabalFile = "1d6zyjpvjm03vsmi04n9zdmaxlq5by326lyf0xlvh05562jnvrqc";
      libraryHaskellDepends = [
        base
        bytestring
        bytestring-builder
        cache
        clock
        containers
        hashable
        http-types
        mtl
        network
        safe-exceptions
        stm
        text
        token-bucket
        transformers
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        cache
        clock
        hspec
        http-types
        HUnit
        QuickCheck
        stm
        transformers
        wai
        wai-extra
      ];
      description = "WAI Middleware for Request Throttling";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-middleware-travisci = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      base64-bytestring,
      bytestring,
      cryptonite,
      http-types,
      text,
      transformers,
      vault,
      wai,
    }:
    mkDerivation {
      pname = "wai-middleware-travisci";
      version = "0.1.0";
      sha256 = "0a58mlgimr6137aiwcdxjk15zy3y58dds4zxffd3vvn0lkzg5jdv";
      revision = "2";
      editedCabalFile = "0j1k2y75gwbny72zf5nrwzanh7sn2plscnrjd4hw5npccxi4dchx";
      libraryHaskellDepends = [
        aeson
        base
        base64-bytestring
        bytestring
        cryptonite
        http-types
        text
        transformers
        vault
        wai
      ];
      description = "WAI middleware for authenticating webhook payloads from Travis CI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-validation = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      containers,
      doctest,
      filepath,
      here,
      hspec,
      http-types,
      insert-ordered-containers,
      lens,
      openapi3,
      text,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-middleware-validation";
      version = "0.1.0.2";
      sha256 = "1qrkfy31slmlbiw9gkz96yd9q6mrw72rjyjl0a5pnjif5ps12vpq";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        containers
        filepath
        http-types
        insert-ordered-containers
        lens
        openapi3
        text
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        doctest
        here
        hspec
        http-types
        openapi3
        wai
        wai-extra
      ];
      description = "WAI Middleware to validate the request and response bodies";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-middleware-verbs = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      exceptions,
      hashable,
      http-types,
      mmorph,
      monad-control,
      monad-control-aligned,
      monad-logger,
      mtl,
      resourcet,
      transformers,
      transformers-base,
      unordered-containers,
      wai,
      wai-transformers,
    }:
    mkDerivation {
      pname = "wai-middleware-verbs";
      version = "0.4.0.1";
      sha256 = "1x4x41b1gbr2xvfw1q766wcvdl13wwv9spa9zxvjdykg71knnw93";
      libraryHaskellDepends = [
        base
        bytestring
        exceptions
        hashable
        http-types
        mmorph
        monad-control
        monad-control-aligned
        monad-logger
        mtl
        resourcet
        transformers
        transformers-base
        unordered-containers
        wai
        wai-transformers
      ];
      description = "Route Wai middlewares based on HTTP verbs";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-predicates = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      blaze-builder,
      bytestring,
      bytestring-conversion,
      case-insensitive,
      cookie,
      http-types,
      singletons,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      text,
      transformers,
      vault,
      vector,
      wai,
    }:
    mkDerivation {
      pname = "wai-predicates";
      version = "1.0.0";
      sha256 = "0m6aqpafc7rgcp81g0kilshz9bxsp4vxllrya2wjccan3n5pajji";
      libraryHaskellDepends = [
        attoparsec
        base
        bytestring
        bytestring-conversion
        case-insensitive
        cookie
        http-types
        singletons
        text
        transformers
        vault
        vector
        wai
      ];
      testHaskellDepends = [
        base
        blaze-builder
        bytestring
        case-insensitive
        http-types
        tasty
        tasty-hunit
        tasty-quickcheck
        wai
      ];
      description = "WAI request predicates";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-problem-details = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      bytestring,
      data-default,
      deriving-aeson,
      hspec,
      hspec-wai,
      hspec-wai-json,
      http-types,
      network-uri,
      text,
      wai,
    }:
    mkDerivation {
      pname = "wai-problem-details";
      version = "0.1.1.0";
      sha256 = "1pi7r3c0b5gi6z2hc6m498kf1xs93gn4m2nbkm5ixnja2670qjq8";
      libraryHaskellDepends = [
        aeson
        base
        bytestring
        data-default
        deriving-aeson
        http-types
        network-uri
        text
        wai
      ];
      testHaskellDepends = [
        base
        data-default
        hspec
        hspec-wai
        hspec-wai-json
        http-types
        wai
      ];
      description = "Problem details middleware for WAI";
      license = lib.meta.getLicenseFromSpdxId "MIT";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-rate-limit = callPackage (
    {
      mkDerivation,
      base,
      http-types,
      time-units,
      wai,
    }:
    mkDerivation {
      pname = "wai-rate-limit";
      version = "0.3.0.0";
      sha256 = "04w146xpw5zlzwrcjq8facmi39izfngmg121bkahyxwsbbnz3adx";
      libraryHaskellDepends = [
        base
        http-types
        time-units
        wai
      ];
      description = "Rate limiting as WAI middleware";
      license = lib.licenses.mit;
    }
  ) { };

  wai-rate-limit-postgres = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-client,
      http-types,
      postgresql-simple,
      postgresql-simple-url,
      resource-pool,
      tasty,
      tasty-hunit,
      text,
      time-units,
      wai,
      wai-rate-limit,
      warp,
    }:
    mkDerivation {
      pname = "wai-rate-limit-postgres";
      version = "0.6.0.0";
      sha256 = "1pfdy2gsk5kbxlkjy9f31y45s6jd06ji8mr5qhqh6sxf4gynkmn7";
      libraryHaskellDepends = [
        base
        bytestring
        postgresql-simple
        resource-pool
        text
        wai-rate-limit
      ];
      testHaskellDepends = [
        base
        bytestring
        http-client
        http-types
        postgresql-simple
        postgresql-simple-url
        resource-pool
        tasty
        tasty-hunit
        text
        time-units
        wai
        wai-rate-limit
        warp
      ];
      description = "See README for more info";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-rate-limit-redis = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      hedis,
      http-types,
      tasty,
      tasty-hedgehog,
      tasty-hunit,
      wai,
      wai-extra,
      wai-rate-limit,
      warp,
    }:
    mkDerivation {
      pname = "wai-rate-limit-redis";
      version = "0.2.0.1";
      sha256 = "1gizywhdrpngs5l6qh5ggnnfkcgplwsigcjj3z8l7vwif74j6qsd";
      revision = "1";
      editedCabalFile = "17rz0q3aki4qcci4mywx5g38zs80j5hs1l8a8yspwa2vj1zjklag";
      libraryHaskellDepends = [
        base
        bytestring
        hedis
        wai-rate-limit
      ];
      testHaskellDepends = [
        base
        bytestring
        hedis
        http-types
        tasty
        tasty-hedgehog
        tasty-hunit
        wai
        wai-extra
        wai-rate-limit
        warp
      ];
      description = "Redis backend for rate limiting as WAI middleware";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-request-spec = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      case-insensitive,
      containers,
      criterion,
      http-types,
      text,
      wai,
    }:
    mkDerivation {
      pname = "wai-request-spec";
      version = "0.10.2.4";
      sha256 = "046nxqqlv4wv1kgc634f691jcq6rbs1ld7324hz059s1xw9fvq8y";
      libraryHaskellDepends = [
        base
        bytestring
        case-insensitive
        containers
        http-types
        text
        wai
      ];
      benchmarkHaskellDepends = [
        base
        bytestring
        criterion
        http-types
        text
        wai
      ];
      description = "Declarative request parsing";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-responsible = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      http-types,
      wai,
    }:
    mkDerivation {
      pname = "wai-responsible";
      version = "0.0.0.0";
      sha256 = "0qf64g11113gl45bfn12j2ikdjwrdxg9r8cicfs4pmh0dq5vj0va";
      libraryHaskellDepends = [
        base
        bytestring
        http-types
        wai
      ];
      description = "Response interface for WAI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-route = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      deepseq,
      doctest,
      http-api-data,
      http-types,
      mtl,
      pattern-trie,
      QuickCheck,
      tasty,
      tasty-quickcheck,
      text,
      unordered-containers,
      wai,
    }:
    mkDerivation {
      pname = "wai-route";
      version = "1.0.0";
      sha256 = "1hm947mzp3lynsjlhbl9nawa3p35cca15xj32cv5dyyllf0lac8w";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        deepseq
        http-api-data
        http-types
        pattern-trie
        text
        unordered-containers
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        containers
        deepseq
        doctest
        http-types
        mtl
        pattern-trie
        QuickCheck
        tasty
        tasty-quickcheck
        text
        unordered-containers
        wai
      ];
      description = "WAI middleware for path-based request routing with captures";
      license = lib.licenses.mpl20;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-router = callPackage (
    {
      mkDerivation,
      base,
      text,
      wai,
    }:
    mkDerivation {
      pname = "wai-router";
      version = "1.0.0.1";
      sha256 = "1827mk64vyivdc12z4h230c4b993i6g8wl4sl0364jda586z58p7";
      libraryHaskellDepends = [
        base
        text
        wai
      ];
      description = "Provides basic routing on URL paths for WAI";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-routes = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      blaze-builder,
      bytestring,
      case-insensitive,
      containers,
      cookie,
      data-default-class,
      filepath,
      hspec,
      hspec-wai,
      hspec-wai-json,
      http-types,
      mime-types,
      monad-loops,
      mtl,
      path-pieces,
      random,
      safe-exceptions,
      template-haskell,
      text,
      vault,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-routes";
      version = "0.10.4";
      sha256 = "04qmwq29iqkpz1j5ffwqxlf5afxiw3ng8akwydcpdx7xlcxf72i4";
      libraryHaskellDepends = [
        aeson
        base
        blaze-builder
        bytestring
        case-insensitive
        containers
        cookie
        data-default-class
        filepath
        http-types
        mime-types
        monad-loops
        mtl
        path-pieces
        random
        safe-exceptions
        template-haskell
        text
        vault
        wai
        wai-extra
      ];
      testHaskellDepends = [
        aeson
        base
        hspec
        hspec-wai
        hspec-wai-json
        text
        wai
      ];
      description = "Typesafe URLs for Wai applications";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-routing = callPackage (
    {
      mkDerivation,
      attoparsec,
      base,
      blaze-builder,
      bytestring,
      bytestring-conversion,
      case-insensitive,
      containers,
      cookie,
      criterion,
      http-types,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      transformers,
      wai,
      wai-predicates,
      wai-route,
    }:
    mkDerivation {
      pname = "wai-routing";
      version = "0.13.0";
      sha256 = "13yybkl2wdsfmgkr46ij4428az259z04fcni2wv9xx10iq11p17l";
      libraryHaskellDepends = [
        attoparsec
        base
        bytestring
        bytestring-conversion
        case-insensitive
        cookie
        http-types
        transformers
        wai
        wai-predicates
        wai-route
      ];
      testHaskellDepends = [
        base
        blaze-builder
        bytestring
        bytestring-conversion
        case-insensitive
        containers
        http-types
        tasty
        tasty-hunit
        tasty-quickcheck
        wai
        wai-predicates
      ];
      benchmarkHaskellDepends = [
        base
        criterion
        http-types
        wai
        wai-predicates
      ];
      description = "Declarative routing for WAI";
      license = lib.licenses.mpl20;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-saml2 = callPackage (
    {
      mkDerivation,
      base,
      base16-bytestring,
      base64-bytestring,
      bytestring,
      c14n,
      containers,
      crypton,
      crypton-x509,
      crypton-x509-store,
      data-default-class,
      filepath,
      http-types,
      mtl,
      network-uri,
      pretty-show,
      tasty,
      tasty-golden,
      text,
      time,
      vault,
      wai,
      wai-extra,
      xml-conduit,
      zlib,
    }:
    mkDerivation {
      pname = "wai-saml2";
      version = "0.6";
      sha256 = "0lxyh93f0581r5b1wzrxrv4binz4df2vxndbmnfnmp6hql61ayx3";
      libraryHaskellDepends = [
        base
        base16-bytestring
        base64-bytestring
        bytestring
        c14n
        containers
        crypton
        crypton-x509
        crypton-x509-store
        data-default-class
        http-types
        mtl
        network-uri
        text
        time
        vault
        wai
        wai-extra
        xml-conduit
        zlib
      ];
      testHaskellDepends = [
        base
        base16-bytestring
        base64-bytestring
        bytestring
        c14n
        containers
        crypton
        crypton-x509
        crypton-x509-store
        data-default-class
        filepath
        http-types
        mtl
        network-uri
        pretty-show
        tasty
        tasty-golden
        text
        time
        vault
        wai
        wai-extra
        xml-conduit
        zlib
      ];
      description = "SAML2 assertion validation as WAI middleware";
      license = lib.licenses.mit;
    }
  ) { };

  wai-saml2_0_7_0 = callPackage (
    {
      mkDerivation,
      base,
      base16-bytestring,
      base64-bytestring,
      bytestring,
      c14n,
      containers,
      crypton,
      crypton-x509,
      crypton-x509-store,
      data-default-class,
      filepath,
      http-types,
      mtl,
      network-uri,
      pretty-show,
      tasty,
      tasty-expected-failure,
      tasty-golden,
      tasty-hunit,
      text,
      time,
      transformers,
      vault,
      wai,
      wai-extra,
      xml-conduit,
      zlib,
    }:
    mkDerivation {
      pname = "wai-saml2";
      version = "0.7.0";
      sha256 = "1crfhrzap4rpw2fais2rpgkls3gdnr2xypy9ay1xbb21yc38ymzs";
      libraryHaskellDepends = [
        base
        base16-bytestring
        base64-bytestring
        bytestring
        c14n
        containers
        crypton
        crypton-x509
        crypton-x509-store
        data-default-class
        http-types
        mtl
        network-uri
        text
        time
        vault
        wai
        wai-extra
        xml-conduit
        zlib
      ];
      testHaskellDepends = [
        base
        base16-bytestring
        base64-bytestring
        bytestring
        c14n
        containers
        crypton
        crypton-x509
        crypton-x509-store
        data-default-class
        filepath
        http-types
        mtl
        network-uri
        pretty-show
        tasty
        tasty-expected-failure
        tasty-golden
        tasty-hunit
        text
        time
        transformers
        vault
        wai
        wai-extra
        xml-conduit
        zlib
      ];
      description = "SAML2 assertion validation as WAI middleware";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-secure-cookies = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      crypton,
      hspec,
      hspec-discover,
      hspec-expectations,
      hspec-wai,
      http-types,
      memory,
      random,
      split,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-secure-cookies";
      version = "0.1.0.8";
      sha256 = "04h9vxinzwnfn45knjgs59kvkv3hwysavlh0h3ap95xxajbarsh2";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        crypton
        http-types
        memory
        random
        split
        wai
      ];
      executableHaskellDepends = [
        base
        bytestring
        crypton
        memory
      ];
      testHaskellDepends = [
        base
        bytestring
        hspec
        hspec-expectations
        hspec-wai
        http-types
        wai
        wai-extra
      ];
      testToolDepends = [ hspec-discover ];
      description = "WAI middleware to automatically encrypt and sign cookies";
      license = lib.meta.getLicenseFromSpdxId "MIT";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "waicookie-genkey";
      broken = true;
    }
  ) { };

  wai-session = callPackage (
    {
      mkDerivation,
      base,
      blaze-builder,
      bytestring,
      bytestring-builder,
      containers,
      cookie,
      entropy,
      http-types,
      StateVar,
      time,
      transformers,
      vault,
      wai,
    }:
    mkDerivation {
      pname = "wai-session";
      version = "0.3.3";
      sha256 = "0lq0gqndb9simd1zkz355m604dwrpcdwxcl3bgagi6kb8h12fffj";
      libraryHaskellDepends = [
        base
        blaze-builder
        bytestring
        bytestring-builder
        containers
        cookie
        entropy
        http-types
        StateVar
        time
        transformers
        vault
        wai
      ];
      description = "Flexible session middleware for WAI";
      license = "unknown";
    }
  ) { };

  wai-session-alt = callPackage (
    {
      mkDerivation,
      base,
      blaze-builder,
      bytestring,
      cookie,
      http-types,
      time,
      vault,
      wai-transformers,
    }:
    mkDerivation {
      pname = "wai-session-alt";
      version = "0.0.0";
      sha256 = "0dy3wqfgqx8vjr6x7g94s0fvsxdkdw2xnb6hba2qw7ipymg8sh49";
      libraryHaskellDepends = [
        base
        blaze-builder
        bytestring
        cookie
        http-types
        time
        vault
        wai-transformers
      ];
      description = "An alternative session middleware for WAI";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-session-clientsession = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      clientsession,
      errors,
      transformers,
      wai-session,
    }:
    mkDerivation {
      pname = "wai-session-clientsession";
      version = "0.1";
      sha256 = "0kczhsmkv88g0x8mk4cfy5z9wv3fzv8v3r4z0q7jkyda0grx3gwf";
      libraryHaskellDepends = [
        base
        bytestring
        cereal
        clientsession
        errors
        transformers
        wai-session
      ];
      description = "Session store based on clientsession";
      license = "unknown";
    }
  ) { };

  wai-session-mysql = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      cookie,
      data-default,
      entropy,
      mysql-simple,
      resource-pool,
      text,
      time,
      transformers,
      wai,
      wai-session,
    }:
    mkDerivation {
      pname = "wai-session-mysql";
      version = "0.2.1.0";
      sha256 = "01wz6v0v6sd4iyn4kk0zyiz44ysyizy4npx1l708dvgnlxdqaisb";
      libraryHaskellDepends = [
        base
        bytestring
        cereal
        cookie
        data-default
        entropy
        mysql-simple
        resource-pool
        text
        time
        transformers
        wai
        wai-session
      ];
      testHaskellDepends = [
        base
        bytestring
        data-default
        mysql-simple
        text
        wai-session
      ];
      description = "MySQL backed Wai session store";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-session-postgresql = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      cookie,
      data-default,
      entropy,
      hspec,
      postgresql-simple,
      resource-pool,
      text,
      time,
      transformers,
      wai,
      wai-session,
    }:
    mkDerivation {
      pname = "wai-session-postgresql";
      version = "0.2.1.3";
      sha256 = "1l3ws8bkflrk5gnvw0dd98fw83kfhf78mn9z6l2v6yv3gvdfzj6l";
      libraryHaskellDepends = [
        base
        bytestring
        cereal
        cookie
        data-default
        entropy
        postgresql-simple
        resource-pool
        text
        time
        transformers
        wai
        wai-session
      ];
      testHaskellDepends = [
        base
        bytestring
        data-default
        hspec
        postgresql-simple
        text
        wai-session
      ];
      description = "PostgreSQL backed Wai session store";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-session-redis = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      data-default,
      hedis,
      hspec,
      http-types,
      vault,
      wai,
      wai-session,
      warp,
    }:
    mkDerivation {
      pname = "wai-session-redis";
      version = "0.1.0.5";
      sha256 = "0lfyj0id6gm6cfx7dmfiw0mx26m7ah5c4mb5xhnzmh65s538l2zs";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        cereal
        data-default
        hedis
        vault
        wai
        wai-session
      ];
      executableHaskellDepends = [
        base
        bytestring
        cereal
        data-default
        hedis
        http-types
        vault
        wai
        wai-session
        warp
      ];
      testHaskellDepends = [
        base
        bytestring
        cereal
        data-default
        hedis
        hspec
        vault
        wai
        wai-session
      ];
      description = "Simple Redis backed wai-session backend";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "wai-session-redis-example-exe";
      broken = true;
    }
  ) { };

  wai-session-tokyocabinet = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cereal,
      errors,
      tokyocabinet-haskell,
      transformers,
      wai-session,
    }:
    mkDerivation {
      pname = "wai-session-tokyocabinet";
      version = "0.1";
      sha256 = "0cd4x3byc8kaarjpfczqaiv5y3ixrdcilnnypkhcavk3vj7w7pmr";
      libraryHaskellDepends = [
        base
        bytestring
        cereal
        errors
        tokyocabinet-haskell
        transformers
        wai-session
      ];
      description = "Session store based on Tokyo Cabinet";
      license = "unknown";
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-slack-middleware = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      http-client,
      http-types,
      wai,
    }:
    mkDerivation {
      pname = "wai-slack-middleware";
      version = "0.2.0";
      sha256 = "0l2pd61vxnfjdjzkvmwqfgf07a3nir3mnbr8qw2nzqa767s84i6i";
      libraryHaskellDepends = [
        aeson
        base
        http-client
        http-types
        wai
      ];
      testHaskellDepends = [ base ];
      description = "A Slack middleware for WAI";
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-static-cache = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      cityhash,
      conduit,
      conduit-combinators,
      containers,
      http-types,
      resourcet,
      system-filepath,
      text,
      transformers,
      vector,
      vector-algorithms,
      wai,
    }:
    mkDerivation {
      pname = "wai-static-cache";
      version = "0.1.0.1";
      sha256 = "0vlkh9izxx1qsb61fak57kk9k35i3vph8qbyvlmgwcw7nplagq6l";
      libraryHaskellDepends = [
        base
        bytestring
        cityhash
        conduit
        conduit-combinators
        containers
        http-types
        resourcet
        system-filepath
        text
        transformers
        vector
        vector-algorithms
        wai
      ];
      description = "A simple cache for serving static files in a WAI middleware";
      license = lib.licenses.agpl3Only;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-static-pages = callPackage (
    {
      mkDerivation,
      base,
      blaze-builder,
      bytestring,
      conduit,
      directory,
      http-types,
      text,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-static-pages";
      version = "0.3";
      sha256 = "0xam283gvcjryq541dzrymv9qy7asyfz8k44b6dwrvm5bqphjz9h";
      libraryHaskellDepends = [
        base
        blaze-builder
        bytestring
        conduit
        directory
        http-types
        text
        wai
        wai-extra
      ];
      description = "generate static html pages from a WAI application";
      license = lib.licenses.mit;
    }
  ) { };

  wai-test = callPackage (
    { mkDerivation, wai }:
    mkDerivation {
      pname = "wai-test";
      version = "3.0.0";
      sha256 = "0xys01jniib0pnhadcm7s0v5z0wcxfgi0bf5ax808zm9qzvl3xfx";
      libraryHaskellDepends = [ wai ];
      doHaddock = false;
      description = "Unit test framework (built on HUnit) for WAI applications. (deprecated)";
      license = lib.licenses.mit;
    }
  ) { };

  wai-thrift = callPackage (
    {
      mkDerivation,
      base,
      blaze-builder,
      bytestring,
      http-types,
      thrift,
      wai,
    }:
    mkDerivation {
      pname = "wai-thrift";
      version = "0.0.1.3";
      sha256 = "1gvrz0izfvbd6k66ki2nvp19x4gq52bkrw8i9qn4lhmal91c18hd";
      libraryHaskellDepends = [
        base
        blaze-builder
        bytestring
        http-types
        thrift
        wai
      ];
      description = "Thrift transport layer for Wai";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-throttler = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      http-types,
      time,
      wai,
    }:
    mkDerivation {
      pname = "wai-throttler";
      version = "0.1.0.5";
      sha256 = "1jh53ac1q4zksxdrmwjgsyidvx8zlhx57nnf3ca4spa3paz9n9g6";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        http-types
        time
        wai
      ];
      description = "Wai middleware for request throttling";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wai-token-bucket-ratelimiter = callPackage (
    {
      mkDerivation,
      async,
      base,
      bytestring,
      clock,
      criterion,
      hashable,
      hspec,
      hspec-discover,
      http-client,
      http-types,
      unordered-containers,
      wai,
      warp,
    }:
    mkDerivation {
      pname = "wai-token-bucket-ratelimiter";
      version = "0.1.0.1";
      sha256 = "1s5l0blfiyyj28qb3qrj4jb35xf1nwhgd1vsmnm8m9l9zjh04hch";
      libraryHaskellDepends = [
        base
        clock
        hashable
        http-types
        unordered-containers
        wai
      ];
      testHaskellDepends = [
        base
        bytestring
        hspec
        http-client
        http-types
        wai
        warp
      ];
      testToolDepends = [ hspec-discover ];
      benchmarkHaskellDepends = [
        async
        base
        criterion
      ];
      description = "A request rate limiting middleware using token buckets";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
    }
  ) { };

  wai-transformers = callPackage (
    {
      mkDerivation,
      base,
      exceptions,
      extractable-singleton,
      monad-control-aligned,
      transformers,
      wai,
      wai-websockets,
      websockets,
    }:
    mkDerivation {
      pname = "wai-transformers";
      version = "0.1.0";
      sha256 = "14l5ihyvg2n0kmmkxy0r5mx1jk3p5jhv1vynsnnrb2md1g4318qp";
      libraryHaskellDepends = [
        base
        exceptions
        extractable-singleton
        monad-control-aligned
        transformers
        wai
        wai-websockets
        websockets
      ];
      license = lib.licenses.bsd3;
    }
  ) { };

  wai-transformers_0_2_0 = callPackage (
    {
      mkDerivation,
      base,
      exceptions,
      transformers,
      unliftio-core,
      wai,
      wai-websockets,
      websockets,
    }:
    mkDerivation {
      pname = "wai-transformers";
      version = "0.2.0";
      sha256 = "19pvm7h9igja6q3id725km96k91080chz19nq3smsz9r0qld6r1q";
      libraryHaskellDepends = [
        base
        exceptions
        transformers
        unliftio-core
        wai
        wai-websockets
        websockets
      ];
      description = "Monad transformers for WAI and WebSockets";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  wai-util = callPackage (
    {
      mkDerivation,
      aeson,
      base,
      blaze-builder,
      bytestring,
      conduit,
      http-accept,
      http-types,
      network-uri,
      text,
      transformers,
      wai,
      wai-extra,
    }:
    mkDerivation {
      pname = "wai-util";
      version = "0.8";
      sha256 = "10rkrhs7xv6qmx31ll891c2nnaqpblyfxqmn8xwjhafp7ks1wqjm";
      libraryHaskellDepends = [
        aeson
        base
        blaze-builder
        bytestring
        conduit
        http-accept
        http-types
        network-uri
        text
        transformers
        wai
        wai-extra
      ];
      description = "Collection of utility functions for use with WAI";
      license = "unknown";
    }
  ) { };

  wai-websockets = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      case-insensitive,
      file-embed,
      http-types,
      network,
      text,
      transformers,
      wai,
      wai-app-static,
      warp,
      websockets,
    }:
    mkDerivation {
      pname = "wai-websockets";
      version = "3.0.1.2";
      sha256 = "0b2xmdsrsqpssyib53wbr6r8hf75789ndyyanv37sv99iyqcwz4i";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        bytestring
        case-insensitive
        http-types
        network
        transformers
        wai
        websockets
      ];
      executableHaskellDepends = [
        base
        bytestring
        case-insensitive
        file-embed
        http-types
        network
        text
        transformers
        wai
        wai-app-static
        warp
        websockets
      ];
      description = "Provide a bridge between WAI and the websockets package";
      license = lib.licenses.mit;
      mainProgram = "wai-websockets-example";
    }
  ) { };

}
