# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  WashNGo = callPackage (
    {
      mkDerivation,
      base,
      containers,
      directory,
      ghc-paths,
      haskell98,
      parsec,
      process,
      regex-compat,
    }:
    mkDerivation {
      pname = "WashNGo";
      version = "2.12.0.1";
      sha256 = "11d9cwqfpvf999a5fi3a3v5b4gdrszzgf4gbdhx63afy42ylbnfj";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
        haskell98
        parsec
        regex-compat
      ];
      executableHaskellDepends = [
        directory
        ghc-paths
        process
      ];
      description = "WASH is a family of EDSLs for programming Web applications in Haskell";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

}
