# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  wrap = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "wrap";
      version = "0.0.0";
      sha256 = "03pmfwwx2ykjglzrc4k09q2lv8piq107j32dg0r1aadj2ysc9fzq";
      libraryHaskellDepends = [ base ];
      description = "Wrap a function's return value with another function";
      license = lib.licenses.bsd3;
    }
  ) { };

  wraparound = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "wraparound";
      version = "0.0.2";
      sha256 = "161mz5bfmx13s9azh3dss64fw98vbaab8krysr9pbbp9dh79i1cf";
      libraryHaskellDepends = [ base ];
      description = "Convenient handling of points on a seamless 2-dimensional plane";
      license = lib.licenses.bsd3;
    }
  ) { };

  wrapped = callPackage (
    { mkDerivation, base }:
    mkDerivation {
      pname = "wrapped";
      version = "0.1.0.1";
      sha256 = "00fvammhn4dlna5d1dc8lpwrdrigj9cnlyi8scwslibr6bjsjzfp";
      revision = "5";
      editedCabalFile = "15h2s7flixws54mv8kxbl17jvp0qfqjflg0fn6iwb8yf4qn96pfa";
      libraryHaskellDepends = [ base ];
      description = "Newtypes to carry DerivingVia instances";
      license = lib.licenses.asl20;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

  wrapped-generic-default = callPackage (
    {
      mkDerivation,
      base,
      data-default-class,
      wrapped,
    }:
    mkDerivation {
      pname = "wrapped-generic-default";
      version = "0.1.0.1";
      sha256 = "10hbz8m98cw8lr2xj0wkc017pnypagb11ss1ihpp6lnc4w1hpj3f";
      revision = "4";
      editedCabalFile = "1zyrdx018xz6xqpw0x3nz98nx9zw4kpr5l8c1q3fdk9jw2afa5sq";
      libraryHaskellDepends = [
        base
        data-default-class
        wrapped
      ];
      description = "A Generic instance of Default";
      license = lib.licenses.asl20;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
