# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  xdcc = callPackage (
    {
      mkDerivation,
      ascii-progress,
      async,
      base,
      bytestring,
      case-insensitive,
      concurrent-output,
      errors,
      iproute,
      irc-client,
      irc-dcc,
      monad-control,
      network,
      optparse-applicative,
      path,
      random,
      safe-exceptions,
      signal,
      stm,
      text,
      transformers,
      transformers-base,
      unix-compat,
    }:
    mkDerivation {
      pname = "xdcc";
      version = "1.1.4";
      sha256 = "0r344vgkiwc7lkb7x78swnz0rimbgdcb0ki29dilqvdv0k4z9i59";
      revision = "3";
      editedCabalFile = "11swld2awjp5l1386c1c1lpkrw53g9l77agvz1y43kh00c2a6yaa";
      isLibrary = false;
      isExecutable = true;
      executableHaskellDepends = [
        ascii-progress
        async
        base
        bytestring
        case-insensitive
        concurrent-output
        errors
        iproute
        irc-client
        irc-dcc
        monad-control
        network
        optparse-applicative
        path
        random
        safe-exceptions
        signal
        stm
        text
        transformers
        transformers-base
        unix-compat
      ];
      description = "A wget-like utility for retrieving files from XDCC bots on IRC";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      mainProgram = "xdcc";
    }
  ) { };

}
