# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  xhtml_3000_4_0_0 = callPackage (
    {
      mkDerivation,
      base,
      bytestring,
      containers,
      text,
    }:
    mkDerivation {
      pname = "xhtml";
      version = "3000.4.0.0";
      sha256 = "1qald32plg2yh587hi2mvp66yryzw0lw6fm65hc1m09g2yf7vbg6";
      libraryHaskellDepends = [
        base
        bytestring
        containers
        text
      ];
      description = "An XHTML combinator library";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
    }
  ) { };

  xhtml-combinators = callPackage (
    {
      mkDerivation,
      base,
      containers,
      random,
      text,
      transformers,
      xml,
    }:
    mkDerivation {
      pname = "xhtml-combinators";
      version = "0.3";
      sha256 = "06bmdl34kly965qj7phw1hm7p7siwjprflr72n7ck32lrknmy2hk";
      libraryHaskellDepends = [
        base
        containers
        random
        text
        transformers
        xml
      ];
      description = "Fast and easy to use XHTML combinators";
      license = lib.licenses.bsd3;
    }
  ) { };

}
