# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  xleb = callPackage (
    {
      mkDerivation,
      base,
      containers,
      mtl,
      xml,
    }:
    mkDerivation {
      pname = "xleb";
      version = "0.1.0";
      sha256 = "15nsfnvca9x5z0pcmv949ni2avi7gi159vmx5hw99jxzm0ql5shb";
      revision = "1";
      editedCabalFile = "0258818bvkhviqgxa6srm5rvhqw2kiik4i590h0431vjs5c12k72";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        base
        containers
        mtl
        xml
      ];
      description = "A simple monadic language for parsing XML structures";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
