# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  xsd = callPackage (
    {
      mkDerivation,
      base,
      lens,
      parsec,
      parsers,
      semigroupoids,
      text,
      time,
    }:
    mkDerivation {
      pname = "xsd";
      version = "0.6.2";
      sha256 = "0m8xb12bfcr03w5b15xx5s2wwy7kz735vwaxyk3qbny3wkq7m0fw";
      libraryHaskellDepends = [
        base
        lens
        parsec
        parsers
        semigroupoids
        text
        time
      ];
      description = "XML Schema data structures";
      license = lib.licenses.bsd3;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
