# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  xsha1 = callPackage (
    {
      mkDerivation,
      base,
      HUnit,
      QuickCheck,
      uniplate,
      vector,
    }:
    mkDerivation {
      pname = "xsha1";
      version = "0.0.0";
      sha256 = "0xljcmc8rsvkpchrdam3lpp4igq1gmym9v3drp15a9k8rfa8irmi";
      libraryHaskellDepends = [
        base
        HUnit
        QuickCheck
        uniplate
        vector
      ];
      description = "cryptanalysis of Blizzard's broken SHA-1 implementation";
      license = lib.licenses.mit;
      hydraPlatforms = lib.platforms.none;
      broken = true;
    }
  ) { };

}
