# auto-generated by split-hackage-packages.sh — do not edit
{ pkgs, lib, callPackage }:
self: {
  zuul = callPackage (
    {
      mkDerivation,
      aeson,
      aeson-pretty,
      base,
      bytestring,
      containers,
      directory,
      filepath,
      http-client,
      http-client-tls,
      optparse-generic,
      tasty,
      tasty-hunit,
      text,
      xdg-basedir,
    }:
    mkDerivation {
      pname = "zuul";
      version = "0.1.1.0";
      sha256 = "0pwiy690z32c9b5x2x1pmcczby7xwby6z8jsgl25zkrb07yagxz4";
      isLibrary = true;
      isExecutable = true;
      libraryHaskellDepends = [
        aeson
        base
        containers
        http-client
        http-client-tls
        text
      ];
      executableHaskellDepends = [
        aeson
        aeson-pretty
        base
        containers
        directory
        filepath
        optparse-generic
        text
        xdg-basedir
      ];
      testHaskellDepends = [
        aeson
        base
        bytestring
        tasty
        tasty-hunit
      ];
      description = "A zuul client library";
      license = lib.meta.getLicenseFromSpdxId "Apache-2.0";
      hydraPlatforms = lib.platforms.none;
      mainProgram = "zuul-cli";
      broken = true;
    }
  ) { };

}
