#!/usr/bin/env bash
# Split the auto-generated hackage-packages.nix monolith into per-prefix
# shard files plus a static name list, so a haskell closure parses only
# the shards it touches instead of the full ~16 MB / ~775 K-line file on
# first haskellPackages.* access.
#
# Idempotent — re-run after every regenerate-hackage-packages.sh.
#
# Layout produced:
#   hackage-packages.nix         (the monolith — left in place; build
#                                 input for this script, not imported)
#   hackage-packages/<pfx>.nix   one shard per HACKAGE_SHARD_PREFIX-char
#                                lowercased prefix (default 4)
#   hackage-names.nix            attrset mapping name → shard filename
#
# Prefix length 2 is too coarse: a pandoc-sized closure hits the densest
# prefixes (ha/st/co/re/…) and still parses ~60 % of the bytes.  Length
# 3 brings that to ~25 %; length 4 (~5.7 K shards, largest ~14 K lines)
# to ~13 % which is where the wall-time curve flattens.
#
# The lazy dispatcher lives in initial-packages.nix (hand-written, not
# regenerated here).
set -euo pipefail

cd "$(dirname "$0")/../../.."   # nixpkgs root
src=pkgs/development/haskell-modules/hackage-packages.nix
out=pkgs/development/haskell-modules/hackage-packages
names=pkgs/development/haskell-modules/hackage-names.nix

[[ -f $src ]] || { echo "split-hackage-packages: $src not found" >&2; exit 1; }

rm -rf "$out"
mkdir -p "$out"

# Single awk pass: walk the nixfmt-formatted monolith, route each
# top-level binding (always at exactly 2-space indent) into its prefix
# shard, and emit the names list as a side effect.
awk -v out="$out" -v names="$names" -v plen="${HACKAGE_SHARD_PREFIX:-4}" '
  function flush() {
    if (cur == "") return
    f = out "/" cur ".nix"
    if (!(cur in seen)) {
      print "# auto-generated by split-hackage-packages.sh — do not edit" > f
      print "{ pkgs, lib, callPackage }:" > f
      print "self: {" > f
      seen[cur] = 1
      order[++nshards] = cur
    }
    printf "%s", buf >> f
    buf = ""
  }
  BEGIN {
    print "# auto-generated by split-hackage-packages.sh — do not edit" > names
    print "# Maps every hackage attr name to its shard filename so the" > names
    print "# dispatcher can expose the full name set without parsing any" > names
    print "# shard body." > names
    print "{" > names
  }
  # Top-level binding at 2-space indent.  hackage2nix + nixfmt only ever
  # produce unquoted identifiers here.
  /^  [_A-Za-z][_A-Za-z0-9-]* =/ {
    flush()
    name = $1
    p = tolower(substr(name, 1, plen))
    print "  \"" name "\" = \"" p ".nix\";" > names
    nnames++
    cur = p
    buf = $0 "\n"
    next
  }
  # End of attrset.
  /^}$/ {
    flush()
    cur = ""
    next
  }
  # Inside an entry: accumulate verbatim. Lines before the first entry
  # (header) are dropped — each shard gets its own header.
  cur != "" { buf = buf $0 "\n" }
  END {
    flush()
    print "}" > names
    for (i = 1; i <= nshards; i++) {
      f = out "/" order[i] ".nix"
      print "}" >> f
    }
    printf "split-hackage-packages: %d names → %d shards\n", nnames, nshards > "/dev/stderr"
  }
' "$src"
